// Copyright (c) 2026 Jakub Melka and Collaborators
// SPDX-License-Identifier: MIT
// See LICENSE file in the project root for full license text.
// -----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by ExyokiOffice OpenXML generator.
//     Manual changes to this file may cause unexpected behaviour.
// </auto-generated>
// -----------------------------------------------------------------------------

#include "ExyokiOffice/DOM/DocumentFormat/OpenXml/Office2019/Excel/CalcFeatures.hpp"
#include "ExyokiOffice/FileFormatVersions.h"
#include "ExyokiOffice/StandardTypes.hpp"

#include <array>
#include <memory>
#include <optional>
#include <span>
#include <string_view>
#include <utility>
#include <vector>

namespace ExyokiOffice {
namespace DocumentFormat {
namespace OpenXml {
namespace Office2019 {
namespace Excel {
namespace CalcFeatures {

namespace {
class CalcFeatureMetaClass final : public ExyokiOffice::OpenXMLElementClass
{
public:
    const ExyokiOffice::OpenXMLElementClass* GetBaseMetaClass() const noexcept override
    {
        return OpenXmlLeafElement::StaticMetaClass();
    }

    ExyokiOffice::OpenXmlQualifiedName QualifiedName() const noexcept override
    {
        return ExyokiOffice::OpenXmlQualifiedName("http://schemas.microsoft.com/office/spreadsheetml/2018/calcfeatures", "feature");
    }

    ExyokiOffice::OpenXmlQualifiedName TypeQualifiedName() const noexcept override
    {
        return ExyokiOffice::OpenXmlQualifiedName("http://schemas.microsoft.com/office/spreadsheetml/2018/calcfeatures", "CT_CalcFeature");
    }

    ExyokiOffice::OpenXml::FileFormatVersions GetVersion() const noexcept override
    {
        return ExyokiOffice::OpenXml::FileFormatVersions::Office2019;
    }

    std::span<const ExyokiOffice::OpenXmlAttribute> GetAttributes() const noexcept override
    {
        static constexpr std::array<ExyokiOffice::OpenXmlAttribute, 1> kAttributes = {
            ExyokiOffice::OpenXmlAttribute(ExyokiOffice::OpenXmlQualifiedName("", "name"), "StringValue", ExyokiOffice::OpenXml::FileFormatVersions::Office2019, "name"),
        };
        return kAttributes;
    }

    ExyokiOffice::OpenXmlElementClassFlags GetFlags() const noexcept override
    {
        return ExyokiOffice::OpenXmlElementClassFlags{ExyokiOffice::OpenXmlElementClassFlag::IsLeafElement};
    }

    std::shared_ptr<ExyokiOffice::OpenXMLElement> Create() const override
    {
        return std::make_shared<CalcFeature>();
    }

    void ConfigureMetadata(ExyokiOffice::MetadataBuilder& builder) const override
    {
        builder.SetSchemaName("schemas_microsoft_com_office_spreadsheetml_2018_calcfeatures.json");
        builder.SetAvailability(ExyokiOffice::OpenXml::FileFormatVersions::Office2019);
        auto& metadataAttribute0 = builder.AddAttribute(ExyokiOffice::OpenXmlQualifiedName("", "name"), "Name", "StringValue", ExyokiOffice::OpenXml::FileFormatVersions::Office2019, "name");
        metadataAttribute0.Validators.push_back(std::make_shared<ExyokiOffice::MetadataRequiredConstraint>(ExyokiOffice::OpenXmlQualifiedName("", "name"), "Name", true));
    }
};
} // namespace

const ExyokiOffice::OpenXMLElementClass* CalcFeature::StaticMetaClass() noexcept
{
    static const CalcFeatureMetaClass kMeta{};
    return &kMeta;
}

const ExyokiOffice::OpenXMLElementClass* CalcFeature::ElementMetaClass() const noexcept
{
    return CalcFeature::StaticMetaClass();
}

StringValue CalcFeature::GetName() const
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "name"));
    return GetAttributeValue<StringValue>(kAttribute);
}

void CalcFeature::SetName(const StringValue& value)
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "name"));
    SetAttributeValue(kAttribute, value);
}

ExyokiOffice::MetadataParticlePtr CreateCalcFeaturesParticleMetadata()
{
    auto particleNode0 = std::make_shared<ExyokiOffice::MetadataSequenceParticle>(0, std::optional<ExyokiOffice::UInt32>{1}, ExyokiOffice::OpenXml::FileFormatVersions::Office2007, false);
    auto particleNode1 = std::make_shared<ExyokiOffice::MetadataElementParticle>(ExyokiOffice::OpenXmlQualifiedName("http://schemas.microsoft.com/office/spreadsheetml/2018/calcfeatures", "feature"), "ExyokiOffice::DocumentFormat::OpenXml::Office2019::Excel::CalcFeatures::CalcFeature", "CT_CalcFeature/xcalcf:feature", 1, std::optional<ExyokiOffice::UInt32>{}, ExyokiOffice::OpenXml::FileFormatVersions::Office2019);
    particleNode0->AddChild(particleNode1);
    return particleNode0;
}

namespace {
class CalcFeaturesMetaClass final : public ExyokiOffice::OpenXMLElementClass
{
public:
    const ExyokiOffice::OpenXMLElementClass* GetBaseMetaClass() const noexcept override
    {
        return OpenXmlCompositeElement::StaticMetaClass();
    }

    ExyokiOffice::OpenXmlQualifiedName QualifiedName() const noexcept override
    {
        return ExyokiOffice::OpenXmlQualifiedName("http://schemas.microsoft.com/office/spreadsheetml/2018/calcfeatures", "calcFeatures");
    }

    ExyokiOffice::OpenXmlQualifiedName TypeQualifiedName() const noexcept override
    {
        return ExyokiOffice::OpenXmlQualifiedName("http://schemas.microsoft.com/office/spreadsheetml/2018/calcfeatures", "CT_CalcFeatures");
    }

    ExyokiOffice::OpenXml::FileFormatVersions GetVersion() const noexcept override
    {
        return ExyokiOffice::OpenXml::FileFormatVersions::Office2019;
    }

    ExyokiOffice::OpenXmlElementClassFlags GetFlags() const noexcept override
    {
        return ExyokiOffice::OpenXmlElementClassFlags{};
    }

    std::shared_ptr<ExyokiOffice::OpenXMLElement> Create() const override
    {
        return std::make_shared<CalcFeatures>();
    }

    void ConfigureMetadata(ExyokiOffice::MetadataBuilder& builder) const override
    {
        builder.SetSchemaName("schemas_microsoft_com_office_spreadsheetml_2018_calcfeatures.json");
        builder.SetAvailability(ExyokiOffice::OpenXml::FileFormatVersions::Office2019);
        builder.SetParticleTree(CreateCalcFeaturesParticleMetadata());
    }
};
} // namespace

const ExyokiOffice::OpenXMLElementClass* CalcFeatures::StaticMetaClass() noexcept
{
    static const CalcFeaturesMetaClass kMeta{};
    return &kMeta;
}

const ExyokiOffice::OpenXMLElementClass* CalcFeatures::ElementMetaClass() const noexcept
{
    return CalcFeatures::StaticMetaClass();
}

} // namespace CalcFeatures
} // namespace Excel
} // namespace Office2019
} // namespace OpenXml
} // namespace DocumentFormat
} // namespace ExyokiOffice
