// Copyright (c) 2026 Jakub Melka and Contributors
// SPDX-License-Identifier: MIT
// See LICENSE file in the project root for full license text.
//
// Derived from the Open-XML-SDK metadata under data/, which is
// Copyright (c) .NET Foundation and Contributors and MIT-licensed.
// See data/LICENSE and THIRD-PARTY-LICENSES.md in the project root.
// -----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by ExyokiOffice OpenXML generator.
//     Manual changes to this file may cause unexpected behaviour.
// </auto-generated>
// -----------------------------------------------------------------------------

#include "ExyokiOffice/DOM/DocumentFormat/OpenXml/Office2019/Excel/ThreadedComments.hpp"
#include "ExyokiOffice/FileFormatVersions.h"
#include "ExyokiOffice/StandardTypes.hpp"

#include <array>
#include <memory>
#include <optional>
#include <span>
#include <string_view>
#include <utility>
#include <vector>

namespace ExyokiOffice {
namespace DocumentFormat {
namespace OpenXml {
namespace Office2019 {
namespace Excel {
namespace ThreadedComments {

namespace {
class MentionMetaClass final : public ExyokiOffice::OpenXMLElementClass
{
public:
    const ExyokiOffice::OpenXMLElementClass* GetBaseMetaClass() const noexcept override
    {
        return OpenXmlLeafElement::StaticMetaClass();
    }

    ExyokiOffice::OpenXmlQualifiedName QualifiedName() const noexcept override
    {
        return ExyokiOffice::OpenXmlQualifiedName("http://schemas.microsoft.com/office/spreadsheetml/2018/threadedcomments", "mention");
    }

    ExyokiOffice::OpenXmlQualifiedName TypeQualifiedName() const noexcept override
    {
        return ExyokiOffice::OpenXmlQualifiedName("http://schemas.microsoft.com/office/spreadsheetml/2018/threadedcomments", "CT_Mention");
    }

    ExyokiOffice::OpenXml::FileFormatVersions GetVersion() const noexcept override
    {
        return ExyokiOffice::OpenXml::FileFormatVersions::Office2019;
    }

    std::span<const ExyokiOffice::OpenXmlAttribute> GetAttributes() const noexcept override
    {
        static constexpr std::array<ExyokiOffice::OpenXmlAttribute, 4> kAttributes = {
            ExyokiOffice::OpenXmlAttribute(ExyokiOffice::OpenXmlQualifiedName("", "mentionpersonId"), "StringValue", ExyokiOffice::OpenXml::FileFormatVersions::Office2019, "mentionpersonId"),
            ExyokiOffice::OpenXmlAttribute(ExyokiOffice::OpenXmlQualifiedName("", "mentionId"), "StringValue", ExyokiOffice::OpenXml::FileFormatVersions::Office2019, "mentionId"),
            ExyokiOffice::OpenXmlAttribute(ExyokiOffice::OpenXmlQualifiedName("", "startIndex"), "UInt32Value", ExyokiOffice::OpenXml::FileFormatVersions::Office2019, "startIndex"),
            ExyokiOffice::OpenXmlAttribute(ExyokiOffice::OpenXmlQualifiedName("", "length"), "UInt32Value", ExyokiOffice::OpenXml::FileFormatVersions::Office2019, "length"),
        };
        return kAttributes;
    }

    ExyokiOffice::OpenXmlElementClassFlags GetFlags() const noexcept override
    {
        return ExyokiOffice::OpenXmlElementClassFlags{ExyokiOffice::OpenXmlElementClassFlag::IsLeafElement};
    }

    std::shared_ptr<ExyokiOffice::OpenXMLElement> Create() const override
    {
        return std::make_shared<Mention>();
    }

    void ConfigureMetadata(ExyokiOffice::MetadataBuilder& builder) const override
    {
        builder.SetSchemaName("schemas_microsoft_com_office_spreadsheetml_2018_threadedcomments.json");
        builder.SetAvailability(ExyokiOffice::OpenXml::FileFormatVersions::Office2019);
        auto& metadataAttribute0 = builder.AddAttribute(ExyokiOffice::OpenXmlQualifiedName("", "mentionpersonId"), "MentionpersonId", "StringValue", ExyokiOffice::OpenXml::FileFormatVersions::Office2019, "mentionpersonId");
        metadataAttribute0.Validators.push_back(std::make_shared<ExyokiOffice::MetadataRequiredConstraint>(ExyokiOffice::OpenXmlQualifiedName("", "mentionpersonId"), "MentionpersonId", true));
        metadataAttribute0.Validators.push_back(std::make_shared<ExyokiOffice::MetadataStringConstraint>(ExyokiOffice::OpenXmlQualifiedName("", "mentionpersonId"), "MentionpersonId", std::optional<ExyokiOffice::Size>{}, std::optional<ExyokiOffice::Size>{}, std::optional<ExyokiOffice::Size>{}, std::optional<std::string>{std::string("\\{[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}\\}")}, true, false, false, false, false));
        auto& metadataAttribute1 = builder.AddAttribute(ExyokiOffice::OpenXmlQualifiedName("", "mentionId"), "MentionId", "StringValue", ExyokiOffice::OpenXml::FileFormatVersions::Office2019, "mentionId");
        metadataAttribute1.Validators.push_back(std::make_shared<ExyokiOffice::MetadataRequiredConstraint>(ExyokiOffice::OpenXmlQualifiedName("", "mentionId"), "MentionId", true));
        metadataAttribute1.Validators.push_back(std::make_shared<ExyokiOffice::MetadataStringConstraint>(ExyokiOffice::OpenXmlQualifiedName("", "mentionId"), "MentionId", std::optional<ExyokiOffice::Size>{}, std::optional<ExyokiOffice::Size>{}, std::optional<ExyokiOffice::Size>{}, std::optional<std::string>{std::string("\\{[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}\\}")}, true, false, false, false, false));
        auto& metadataAttribute2 = builder.AddAttribute(ExyokiOffice::OpenXmlQualifiedName("", "startIndex"), "StartIndex", "UInt32Value", ExyokiOffice::OpenXml::FileFormatVersions::Office2019, "startIndex");
        metadataAttribute2.Validators.push_back(std::make_shared<ExyokiOffice::MetadataRequiredConstraint>(ExyokiOffice::OpenXmlQualifiedName("", "startIndex"), "StartIndex", true));
        auto& metadataAttribute3 = builder.AddAttribute(ExyokiOffice::OpenXmlQualifiedName("", "length"), "Length", "UInt32Value", ExyokiOffice::OpenXml::FileFormatVersions::Office2019, "length");
        metadataAttribute3.Validators.push_back(std::make_shared<ExyokiOffice::MetadataRequiredConstraint>(ExyokiOffice::OpenXmlQualifiedName("", "length"), "Length", true));
    }
};
} // namespace

const ExyokiOffice::OpenXMLElementClass* Mention::StaticMetaClass() noexcept
{
    static const MentionMetaClass kMeta{};
    return &kMeta;
}

const ExyokiOffice::OpenXMLElementClass* Mention::ElementMetaClass() const noexcept
{
    return Mention::StaticMetaClass();
}

StringValue Mention::GetMentionpersonId() const
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "mentionpersonId"));
    return GetAttributeValue<StringValue>(kAttribute);
}

void Mention::SetMentionpersonId(const StringValue& value)
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "mentionpersonId"));
    SetAttributeValue(kAttribute, value);
}

StringValue Mention::GetMentionId() const
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "mentionId"));
    return GetAttributeValue<StringValue>(kAttribute);
}

void Mention::SetMentionId(const StringValue& value)
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "mentionId"));
    SetAttributeValue(kAttribute, value);
}

UInt32Value Mention::GetStartIndex() const
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "startIndex"));
    return GetAttributeValue<UInt32Value>(kAttribute);
}

void Mention::SetStartIndex(const UInt32Value& value)
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "startIndex"));
    SetAttributeValue(kAttribute, value);
}

UInt32Value Mention::GetLength() const
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "length"));
    return GetAttributeValue<UInt32Value>(kAttribute);
}

void Mention::SetLength(const UInt32Value& value)
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "length"));
    SetAttributeValue(kAttribute, value);
}

ExyokiOffice::MetadataParticlePtr CreateThreadedCommentMentionsParticleMetadata()
{
    auto particleNode0 = std::make_shared<ExyokiOffice::MetadataSequenceParticle>(1, std::optional<ExyokiOffice::UInt32>{1}, ExyokiOffice::OpenXml::FileFormatVersions::Office2007, false);
    auto particleNode1 = std::make_shared<ExyokiOffice::MetadataElementParticle>(ExyokiOffice::OpenXmlQualifiedName("http://schemas.microsoft.com/office/spreadsheetml/2018/threadedcomments", "mention"), "ExyokiOffice::DocumentFormat::OpenXml::Office2019::Excel::ThreadedComments::Mention", "CT_Mention/xltc:mention", 0, std::optional<ExyokiOffice::UInt32>{}, ExyokiOffice::OpenXml::FileFormatVersions::Office2019);
    particleNode0->AddChild(particleNode1);
    return particleNode0;
}

namespace {
class ThreadedCommentMentionsMetaClass final : public ExyokiOffice::OpenXMLElementClass
{
public:
    const ExyokiOffice::OpenXMLElementClass* GetBaseMetaClass() const noexcept override
    {
        return OpenXmlCompositeElement::StaticMetaClass();
    }

    ExyokiOffice::OpenXmlQualifiedName QualifiedName() const noexcept override
    {
        return ExyokiOffice::OpenXmlQualifiedName("http://schemas.microsoft.com/office/spreadsheetml/2018/threadedcomments", "mentions");
    }

    ExyokiOffice::OpenXmlQualifiedName TypeQualifiedName() const noexcept override
    {
        return ExyokiOffice::OpenXmlQualifiedName("http://schemas.microsoft.com/office/spreadsheetml/2018/threadedcomments", "CT_ThreadedCommentMentions");
    }

    ExyokiOffice::OpenXml::FileFormatVersions GetVersion() const noexcept override
    {
        return ExyokiOffice::OpenXml::FileFormatVersions::Office2019;
    }

    ExyokiOffice::OpenXmlElementClassFlags GetFlags() const noexcept override
    {
        return ExyokiOffice::OpenXmlElementClassFlags{};
    }

    std::shared_ptr<ExyokiOffice::OpenXMLElement> Create() const override
    {
        return std::make_shared<ThreadedCommentMentions>();
    }

    void ConfigureMetadata(ExyokiOffice::MetadataBuilder& builder) const override
    {
        builder.SetSchemaName("schemas_microsoft_com_office_spreadsheetml_2018_threadedcomments.json");
        builder.SetAvailability(ExyokiOffice::OpenXml::FileFormatVersions::Office2019);
        builder.SetParticleTree(CreateThreadedCommentMentionsParticleMetadata());
    }
};
} // namespace

const ExyokiOffice::OpenXMLElementClass* ThreadedCommentMentions::StaticMetaClass() noexcept
{
    static const ThreadedCommentMentionsMetaClass kMeta{};
    return &kMeta;
}

const ExyokiOffice::OpenXMLElementClass* ThreadedCommentMentions::ElementMetaClass() const noexcept
{
    return ThreadedCommentMentions::StaticMetaClass();
}

namespace {
class ThreadedCommentTextMetaClass final : public ExyokiOffice::OpenXMLElementClass
{
public:
    const ExyokiOffice::OpenXMLElementClass* GetBaseMetaClass() const noexcept override
    {
        return OpenXmlLeafTextElement::StaticMetaClass();
    }

    ExyokiOffice::OpenXmlQualifiedName QualifiedName() const noexcept override
    {
        return ExyokiOffice::OpenXmlQualifiedName("http://schemas.microsoft.com/office/spreadsheetml/2018/threadedcomments", "text");
    }

    ExyokiOffice::OpenXmlQualifiedName TypeQualifiedName() const noexcept override
    {
        return ExyokiOffice::OpenXmlQualifiedName("http://schemas.openxmlformats.org/spreadsheetml/2006/main", "ST_Xstring");
    }

    ExyokiOffice::OpenXml::FileFormatVersions GetVersion() const noexcept override
    {
        return ExyokiOffice::OpenXml::FileFormatVersions::Office2019;
    }

    ExyokiOffice::OpenXmlElementClassFlags GetFlags() const noexcept override
    {
        return ExyokiOffice::OpenXmlElementClassFlags{ExyokiOffice::OpenXmlElementClassFlag::IsLeafText};
    }

    std::shared_ptr<ExyokiOffice::OpenXMLElement> Create() const override
    {
        return std::make_shared<ThreadedCommentText>();
    }

    void ConfigureMetadata(ExyokiOffice::MetadataBuilder& builder) const override
    {
        builder.SetSchemaName("schemas_microsoft_com_office_spreadsheetml_2018_threadedcomments.json");
        builder.SetAvailability(ExyokiOffice::OpenXml::FileFormatVersions::Office2019);
    }
};
} // namespace

const ExyokiOffice::OpenXMLElementClass* ThreadedCommentText::StaticMetaClass() noexcept
{
    static const ThreadedCommentTextMetaClass kMeta{};
    return &kMeta;
}

const ExyokiOffice::OpenXMLElementClass* ThreadedCommentText::ElementMetaClass() const noexcept
{
    return ThreadedCommentText::StaticMetaClass();
}

ExyokiOffice::MetadataParticlePtr CreateThreadedCommentParticleMetadata()
{
    auto particleNode0 = std::make_shared<ExyokiOffice::MetadataSequenceParticle>(1, std::optional<ExyokiOffice::UInt32>{1}, ExyokiOffice::OpenXml::FileFormatVersions::Office2007, false);
    auto particleNode1 = std::make_shared<ExyokiOffice::MetadataElementParticle>(ExyokiOffice::OpenXmlQualifiedName("http://schemas.microsoft.com/office/spreadsheetml/2018/threadedcomments", "text"), "ExyokiOffice::DocumentFormat::OpenXml::Office2019::Excel::ThreadedComments::ThreadedCommentText", "ThreadedCommentText", 0, std::optional<ExyokiOffice::UInt32>{1}, ExyokiOffice::OpenXml::FileFormatVersions::Office2019);
    particleNode0->AddChild(particleNode1);
    auto particleNode2 = std::make_shared<ExyokiOffice::MetadataElementParticle>(ExyokiOffice::OpenXmlQualifiedName("http://schemas.microsoft.com/office/spreadsheetml/2018/threadedcomments", "mentions"), "ExyokiOffice::DocumentFormat::OpenXml::Office2019::Excel::ThreadedComments::ThreadedCommentMentions", "ThreadedCommentMentions", 0, std::optional<ExyokiOffice::UInt32>{1}, ExyokiOffice::OpenXml::FileFormatVersions::Office2019);
    particleNode0->AddChild(particleNode2);
    auto particleNode3 = std::make_shared<ExyokiOffice::MetadataElementParticle>(ExyokiOffice::OpenXmlQualifiedName("http://schemas.microsoft.com/office/spreadsheetml/2018/threadedcomments", "extLst"), "ExyokiOffice::DocumentFormat::OpenXml::Office2019::Excel::ThreadedComments::ExtensionList", "ExtensionList", 0, std::optional<ExyokiOffice::UInt32>{1}, ExyokiOffice::OpenXml::FileFormatVersions::Office2019);
    particleNode0->AddChild(particleNode3);
    return particleNode0;
}

namespace {
class ThreadedCommentMetaClass final : public ExyokiOffice::OpenXMLElementClass
{
public:
    const ExyokiOffice::OpenXMLElementClass* GetBaseMetaClass() const noexcept override
    {
        return OpenXmlCompositeElement::StaticMetaClass();
    }

    ExyokiOffice::OpenXmlQualifiedName QualifiedName() const noexcept override
    {
        return ExyokiOffice::OpenXmlQualifiedName("http://schemas.microsoft.com/office/spreadsheetml/2018/threadedcomments", "threadedComment");
    }

    ExyokiOffice::OpenXmlQualifiedName TypeQualifiedName() const noexcept override
    {
        return ExyokiOffice::OpenXmlQualifiedName("http://schemas.microsoft.com/office/spreadsheetml/2018/threadedcomments", "CT_ThreadedComment");
    }

    ExyokiOffice::OpenXml::FileFormatVersions GetVersion() const noexcept override
    {
        return ExyokiOffice::OpenXml::FileFormatVersions::Office2019;
    }

    std::span<const ExyokiOffice::OpenXmlAttribute> GetAttributes() const noexcept override
    {
        static constexpr std::array<ExyokiOffice::OpenXmlAttribute, 6> kAttributes = {
            ExyokiOffice::OpenXmlAttribute(ExyokiOffice::OpenXmlQualifiedName("", "ref"), "StringValue", ExyokiOffice::OpenXml::FileFormatVersions::Office2019, "ref"),
            ExyokiOffice::OpenXmlAttribute(ExyokiOffice::OpenXmlQualifiedName("", "dT"), "DateTimeValue", ExyokiOffice::OpenXml::FileFormatVersions::Office2019, "dT"),
            ExyokiOffice::OpenXmlAttribute(ExyokiOffice::OpenXmlQualifiedName("", "personId"), "StringValue", ExyokiOffice::OpenXml::FileFormatVersions::Office2019, "personId"),
            ExyokiOffice::OpenXmlAttribute(ExyokiOffice::OpenXmlQualifiedName("", "id"), "StringValue", ExyokiOffice::OpenXml::FileFormatVersions::Office2019, "id"),
            ExyokiOffice::OpenXmlAttribute(ExyokiOffice::OpenXmlQualifiedName("", "parentId"), "StringValue", ExyokiOffice::OpenXml::FileFormatVersions::Office2019, "parentId"),
            ExyokiOffice::OpenXmlAttribute(ExyokiOffice::OpenXmlQualifiedName("", "done"), "BooleanValue", ExyokiOffice::OpenXml::FileFormatVersions::Office2019, "done"),
        };
        return kAttributes;
    }

    ExyokiOffice::OpenXmlElementClassFlags GetFlags() const noexcept override
    {
        return ExyokiOffice::OpenXmlElementClassFlags{};
    }

    std::shared_ptr<ExyokiOffice::OpenXMLElement> Create() const override
    {
        return std::make_shared<ThreadedComment>();
    }

    void ConfigureMetadata(ExyokiOffice::MetadataBuilder& builder) const override
    {
        builder.SetSchemaName("schemas_microsoft_com_office_spreadsheetml_2018_threadedcomments.json");
        builder.SetAvailability(ExyokiOffice::OpenXml::FileFormatVersions::Office2019);
        auto& metadataAttribute0 = builder.AddAttribute(ExyokiOffice::OpenXmlQualifiedName("", "ref"), "Ref", "StringValue", ExyokiOffice::OpenXml::FileFormatVersions::Office2019, "ref");
        auto& metadataAttribute1 = builder.AddAttribute(ExyokiOffice::OpenXmlQualifiedName("", "dT"), "DT", "DateTimeValue", ExyokiOffice::OpenXml::FileFormatVersions::Office2019, "dT");
        auto& metadataAttribute2 = builder.AddAttribute(ExyokiOffice::OpenXmlQualifiedName("", "personId"), "PersonId", "StringValue", ExyokiOffice::OpenXml::FileFormatVersions::Office2019, "personId");
        metadataAttribute2.Validators.push_back(std::make_shared<ExyokiOffice::MetadataRequiredConstraint>(ExyokiOffice::OpenXmlQualifiedName("", "personId"), "PersonId", true));
        metadataAttribute2.Validators.push_back(std::make_shared<ExyokiOffice::MetadataStringConstraint>(ExyokiOffice::OpenXmlQualifiedName("", "personId"), "PersonId", std::optional<ExyokiOffice::Size>{}, std::optional<ExyokiOffice::Size>{}, std::optional<ExyokiOffice::Size>{}, std::optional<std::string>{std::string("\\{[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}\\}")}, true, false, false, false, false));
        auto& metadataAttribute3 = builder.AddAttribute(ExyokiOffice::OpenXmlQualifiedName("", "id"), "Id", "StringValue", ExyokiOffice::OpenXml::FileFormatVersions::Office2019, "id");
        metadataAttribute3.Validators.push_back(std::make_shared<ExyokiOffice::MetadataRequiredConstraint>(ExyokiOffice::OpenXmlQualifiedName("", "id"), "Id", true));
        metadataAttribute3.Validators.push_back(std::make_shared<ExyokiOffice::MetadataStringConstraint>(ExyokiOffice::OpenXmlQualifiedName("", "id"), "Id", std::optional<ExyokiOffice::Size>{}, std::optional<ExyokiOffice::Size>{}, std::optional<ExyokiOffice::Size>{}, std::optional<std::string>{std::string("\\{[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}\\}")}, true, false, false, false, false));
        auto& metadataAttribute4 = builder.AddAttribute(ExyokiOffice::OpenXmlQualifiedName("", "parentId"), "ParentId", "StringValue", ExyokiOffice::OpenXml::FileFormatVersions::Office2019, "parentId");
        metadataAttribute4.Validators.push_back(std::make_shared<ExyokiOffice::MetadataStringConstraint>(ExyokiOffice::OpenXmlQualifiedName("", "parentId"), "ParentId", std::optional<ExyokiOffice::Size>{}, std::optional<ExyokiOffice::Size>{}, std::optional<ExyokiOffice::Size>{}, std::optional<std::string>{std::string("\\{[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}\\}")}, true, false, false, false, false));
        auto& metadataAttribute5 = builder.AddAttribute(ExyokiOffice::OpenXmlQualifiedName("", "done"), "Done", "BooleanValue", ExyokiOffice::OpenXml::FileFormatVersions::Office2019, "done");
        builder.SetParticleTree(CreateThreadedCommentParticleMetadata());
    }
};
} // namespace

const ExyokiOffice::OpenXMLElementClass* ThreadedComment::StaticMetaClass() noexcept
{
    static const ThreadedCommentMetaClass kMeta{};
    return &kMeta;
}

const ExyokiOffice::OpenXMLElementClass* ThreadedComment::ElementMetaClass() const noexcept
{
    return ThreadedComment::StaticMetaClass();
}

StringValue ThreadedComment::GetRef() const
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "ref"));
    return GetAttributeValue<StringValue>(kAttribute);
}

void ThreadedComment::SetRef(const StringValue& value)
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "ref"));
    SetAttributeValue(kAttribute, value);
}

DateTimeValue ThreadedComment::GetDT() const
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "dT"));
    return GetAttributeValue<DateTimeValue>(kAttribute);
}

void ThreadedComment::SetDT(const DateTimeValue& value)
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "dT"));
    SetAttributeValue(kAttribute, value);
}

StringValue ThreadedComment::GetPersonId() const
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "personId"));
    return GetAttributeValue<StringValue>(kAttribute);
}

void ThreadedComment::SetPersonId(const StringValue& value)
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "personId"));
    SetAttributeValue(kAttribute, value);
}

StringValue ThreadedComment::GetId() const
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "id"));
    return GetAttributeValue<StringValue>(kAttribute);
}

void ThreadedComment::SetId(const StringValue& value)
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "id"));
    SetAttributeValue(kAttribute, value);
}

StringValue ThreadedComment::GetParentId() const
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "parentId"));
    return GetAttributeValue<StringValue>(kAttribute);
}

void ThreadedComment::SetParentId(const StringValue& value)
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "parentId"));
    SetAttributeValue(kAttribute, value);
}

BooleanValue ThreadedComment::GetDone() const
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "done"));
    return GetAttributeValue<BooleanValue>(kAttribute);
}

void ThreadedComment::SetDone(const BooleanValue& value)
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "done"));
    SetAttributeValue(kAttribute, value);
}

ExyokiOffice::MetadataParticlePtr CreateExtensionListParticleMetadata()
{
    auto particleNode0 = std::make_shared<ExyokiOffice::MetadataSequenceParticle>(1, std::optional<ExyokiOffice::UInt32>{1}, ExyokiOffice::OpenXml::FileFormatVersions::Office2007, false);
    auto particleNode1 = std::make_shared<ExyokiOffice::MetadataGroupParticle>(0, std::optional<ExyokiOffice::UInt32>{1}, ExyokiOffice::OpenXml::FileFormatVersions::Office2007, false);
    auto particleNode2 = std::make_shared<ExyokiOffice::MetadataSequenceParticle>(1, std::optional<ExyokiOffice::UInt32>{1}, ExyokiOffice::OpenXml::FileFormatVersions::Office2007, false);
    auto particleNode3 = std::make_shared<ExyokiOffice::MetadataElementParticle>(ExyokiOffice::OpenXmlQualifiedName("http://schemas.openxmlformats.org/spreadsheetml/2006/main", "ext"), "ExyokiOffice::DocumentFormat::OpenXml::Spreadsheet::Extension", "CT_Extension/x:ext", 0, std::optional<ExyokiOffice::UInt32>{}, ExyokiOffice::OpenXml::FileFormatVersions::Office2007);
    particleNode2->AddChild(particleNode3);
    particleNode1->AddChild(particleNode2);
    particleNode0->AddChild(particleNode1);
    return particleNode0;
}

namespace {
class ExtensionListMetaClass final : public ExyokiOffice::OpenXMLElementClass
{
public:
    const ExyokiOffice::OpenXMLElementClass* GetBaseMetaClass() const noexcept override
    {
        return OpenXmlCompositeElement::StaticMetaClass();
    }

    ExyokiOffice::OpenXmlQualifiedName QualifiedName() const noexcept override
    {
        return ExyokiOffice::OpenXmlQualifiedName("http://schemas.microsoft.com/office/spreadsheetml/2018/threadedcomments", "extLst");
    }

    ExyokiOffice::OpenXmlQualifiedName TypeQualifiedName() const noexcept override
    {
        return ExyokiOffice::OpenXmlQualifiedName("http://schemas.openxmlformats.org/spreadsheetml/2006/main", "CT_ExtensionList");
    }

    ExyokiOffice::OpenXml::FileFormatVersions GetVersion() const noexcept override
    {
        return ExyokiOffice::OpenXml::FileFormatVersions::Office2019;
    }

    ExyokiOffice::OpenXmlElementClassFlags GetFlags() const noexcept override
    {
        return ExyokiOffice::OpenXmlElementClassFlags{};
    }

    std::shared_ptr<ExyokiOffice::OpenXMLElement> Create() const override
    {
        return std::make_shared<ExtensionList>();
    }

    void ConfigureMetadata(ExyokiOffice::MetadataBuilder& builder) const override
    {
        builder.SetSchemaName("schemas_microsoft_com_office_spreadsheetml_2018_threadedcomments.json");
        builder.SetAvailability(ExyokiOffice::OpenXml::FileFormatVersions::Office2019);
        builder.SetParticleTree(CreateExtensionListParticleMetadata());
    }
};
} // namespace

const ExyokiOffice::OpenXMLElementClass* ExtensionList::StaticMetaClass() noexcept
{
    static const ExtensionListMetaClass kMeta{};
    return &kMeta;
}

const ExyokiOffice::OpenXMLElementClass* ExtensionList::ElementMetaClass() const noexcept
{
    return ExtensionList::StaticMetaClass();
}

ExyokiOffice::MetadataParticlePtr CreatePersonParticleMetadata()
{
    auto particleNode0 = std::make_shared<ExyokiOffice::MetadataSequenceParticle>(1, std::optional<ExyokiOffice::UInt32>{1}, ExyokiOffice::OpenXml::FileFormatVersions::Office2007, false);
    auto particleNode1 = std::make_shared<ExyokiOffice::MetadataElementParticle>(ExyokiOffice::OpenXmlQualifiedName("http://schemas.microsoft.com/office/spreadsheetml/2018/threadedcomments", "extLst"), "ExyokiOffice::DocumentFormat::OpenXml::Office2019::Excel::ThreadedComments::ExtensionList", "ExtensionList", 0, std::optional<ExyokiOffice::UInt32>{1}, ExyokiOffice::OpenXml::FileFormatVersions::Office2019);
    particleNode0->AddChild(particleNode1);
    return particleNode0;
}

namespace {
class PersonMetaClass final : public ExyokiOffice::OpenXMLElementClass
{
public:
    const ExyokiOffice::OpenXMLElementClass* GetBaseMetaClass() const noexcept override
    {
        return OpenXmlCompositeElement::StaticMetaClass();
    }

    ExyokiOffice::OpenXmlQualifiedName QualifiedName() const noexcept override
    {
        return ExyokiOffice::OpenXmlQualifiedName("http://schemas.microsoft.com/office/spreadsheetml/2018/threadedcomments", "person");
    }

    ExyokiOffice::OpenXmlQualifiedName TypeQualifiedName() const noexcept override
    {
        return ExyokiOffice::OpenXmlQualifiedName("http://schemas.microsoft.com/office/spreadsheetml/2018/threadedcomments", "CT_Person");
    }

    ExyokiOffice::OpenXml::FileFormatVersions GetVersion() const noexcept override
    {
        return ExyokiOffice::OpenXml::FileFormatVersions::Office2019;
    }

    std::span<const ExyokiOffice::OpenXmlAttribute> GetAttributes() const noexcept override
    {
        static constexpr std::array<ExyokiOffice::OpenXmlAttribute, 4> kAttributes = {
            ExyokiOffice::OpenXmlAttribute(ExyokiOffice::OpenXmlQualifiedName("", "displayName"), "StringValue", ExyokiOffice::OpenXml::FileFormatVersions::Office2019, "displayName"),
            ExyokiOffice::OpenXmlAttribute(ExyokiOffice::OpenXmlQualifiedName("", "id"), "StringValue", ExyokiOffice::OpenXml::FileFormatVersions::Office2019, "id"),
            ExyokiOffice::OpenXmlAttribute(ExyokiOffice::OpenXmlQualifiedName("", "userId"), "StringValue", ExyokiOffice::OpenXml::FileFormatVersions::Office2019, "userId"),
            ExyokiOffice::OpenXmlAttribute(ExyokiOffice::OpenXmlQualifiedName("", "providerId"), "StringValue", ExyokiOffice::OpenXml::FileFormatVersions::Office2019, "providerId"),
        };
        return kAttributes;
    }

    ExyokiOffice::OpenXmlElementClassFlags GetFlags() const noexcept override
    {
        return ExyokiOffice::OpenXmlElementClassFlags{};
    }

    std::shared_ptr<ExyokiOffice::OpenXMLElement> Create() const override
    {
        return std::make_shared<Person>();
    }

    void ConfigureMetadata(ExyokiOffice::MetadataBuilder& builder) const override
    {
        builder.SetSchemaName("schemas_microsoft_com_office_spreadsheetml_2018_threadedcomments.json");
        builder.SetAvailability(ExyokiOffice::OpenXml::FileFormatVersions::Office2019);
        auto& metadataAttribute0 = builder.AddAttribute(ExyokiOffice::OpenXmlQualifiedName("", "displayName"), "DisplayName", "StringValue", ExyokiOffice::OpenXml::FileFormatVersions::Office2019, "displayName");
        metadataAttribute0.Validators.push_back(std::make_shared<ExyokiOffice::MetadataRequiredConstraint>(ExyokiOffice::OpenXmlQualifiedName("", "displayName"), "DisplayName", true));
        auto& metadataAttribute1 = builder.AddAttribute(ExyokiOffice::OpenXmlQualifiedName("", "id"), "Id", "StringValue", ExyokiOffice::OpenXml::FileFormatVersions::Office2019, "id");
        metadataAttribute1.Validators.push_back(std::make_shared<ExyokiOffice::MetadataRequiredConstraint>(ExyokiOffice::OpenXmlQualifiedName("", "id"), "Id", true));
        metadataAttribute1.Validators.push_back(std::make_shared<ExyokiOffice::MetadataStringConstraint>(ExyokiOffice::OpenXmlQualifiedName("", "id"), "Id", std::optional<ExyokiOffice::Size>{}, std::optional<ExyokiOffice::Size>{}, std::optional<ExyokiOffice::Size>{}, std::optional<std::string>{std::string("\\{[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}\\}")}, true, false, false, false, false));
        auto& metadataAttribute2 = builder.AddAttribute(ExyokiOffice::OpenXmlQualifiedName("", "userId"), "UserId", "StringValue", ExyokiOffice::OpenXml::FileFormatVersions::Office2019, "userId");
        auto& metadataAttribute3 = builder.AddAttribute(ExyokiOffice::OpenXmlQualifiedName("", "providerId"), "ProviderId", "StringValue", ExyokiOffice::OpenXml::FileFormatVersions::Office2019, "providerId");
        builder.SetParticleTree(CreatePersonParticleMetadata());
    }
};
} // namespace

const ExyokiOffice::OpenXMLElementClass* Person::StaticMetaClass() noexcept
{
    static const PersonMetaClass kMeta{};
    return &kMeta;
}

const ExyokiOffice::OpenXMLElementClass* Person::ElementMetaClass() const noexcept
{
    return Person::StaticMetaClass();
}

StringValue Person::GetDisplayName() const
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "displayName"));
    return GetAttributeValue<StringValue>(kAttribute);
}

void Person::SetDisplayName(const StringValue& value)
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "displayName"));
    SetAttributeValue(kAttribute, value);
}

StringValue Person::GetId() const
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "id"));
    return GetAttributeValue<StringValue>(kAttribute);
}

void Person::SetId(const StringValue& value)
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "id"));
    SetAttributeValue(kAttribute, value);
}

StringValue Person::GetUserId() const
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "userId"));
    return GetAttributeValue<StringValue>(kAttribute);
}

void Person::SetUserId(const StringValue& value)
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "userId"));
    SetAttributeValue(kAttribute, value);
}

StringValue Person::GetProviderId() const
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "providerId"));
    return GetAttributeValue<StringValue>(kAttribute);
}

void Person::SetProviderId(const StringValue& value)
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "providerId"));
    SetAttributeValue(kAttribute, value);
}

ExyokiOffice::MetadataParticlePtr CreateThreadedCommentsParticleMetadata()
{
    auto particleNode0 = std::make_shared<ExyokiOffice::MetadataSequenceParticle>(1, std::optional<ExyokiOffice::UInt32>{1}, ExyokiOffice::OpenXml::FileFormatVersions::Office2007, false);
    auto particleNode1 = std::make_shared<ExyokiOffice::MetadataElementParticle>(ExyokiOffice::OpenXmlQualifiedName("http://schemas.microsoft.com/office/spreadsheetml/2018/threadedcomments", "threadedComment"), "ExyokiOffice::DocumentFormat::OpenXml::Office2019::Excel::ThreadedComments::ThreadedComment", "CT_ThreadedComment/xltc:threadedComment", 0, std::optional<ExyokiOffice::UInt32>{}, ExyokiOffice::OpenXml::FileFormatVersions::Office2019);
    particleNode0->AddChild(particleNode1);
    auto particleNode2 = std::make_shared<ExyokiOffice::MetadataElementParticle>(ExyokiOffice::OpenXmlQualifiedName("http://schemas.microsoft.com/office/spreadsheetml/2018/threadedcomments", "extLst"), "ExyokiOffice::DocumentFormat::OpenXml::Office2019::Excel::ThreadedComments::ExtensionList", "CT_ExtensionList/xltc:extLst", 0, std::optional<ExyokiOffice::UInt32>{1}, ExyokiOffice::OpenXml::FileFormatVersions::Office2019);
    particleNode0->AddChild(particleNode2);
    return particleNode0;
}

namespace {
class ThreadedCommentsMetaClass final : public ExyokiOffice::OpenXMLElementClass
{
public:
    const ExyokiOffice::OpenXMLElementClass* GetBaseMetaClass() const noexcept override
    {
        return OpenXmlCompositeElement::StaticMetaClass();
    }

    ExyokiOffice::OpenXmlQualifiedName QualifiedName() const noexcept override
    {
        return ExyokiOffice::OpenXmlQualifiedName("http://schemas.microsoft.com/office/spreadsheetml/2018/threadedcomments", "ThreadedComments");
    }

    ExyokiOffice::OpenXmlQualifiedName TypeQualifiedName() const noexcept override
    {
        return ExyokiOffice::OpenXmlQualifiedName("http://schemas.microsoft.com/office/spreadsheetml/2018/threadedcomments", "CT_ThreadedComments");
    }

    ExyokiOffice::OpenXml::FileFormatVersions GetVersion() const noexcept override
    {
        return ExyokiOffice::OpenXml::FileFormatVersions::Office2019;
    }

    ExyokiOffice::OpenXmlElementClassFlags GetFlags() const noexcept override
    {
        return ExyokiOffice::OpenXmlElementClassFlags{};
    }

    std::shared_ptr<ExyokiOffice::OpenXMLElement> Create() const override
    {
        return std::make_shared<ThreadedComments>();
    }

    void ConfigureMetadata(ExyokiOffice::MetadataBuilder& builder) const override
    {
        builder.SetSchemaName("schemas_microsoft_com_office_spreadsheetml_2018_threadedcomments.json");
        builder.SetAvailability(ExyokiOffice::OpenXml::FileFormatVersions::Office2019);
        builder.SetParticleTree(CreateThreadedCommentsParticleMetadata());
    }
};
} // namespace

const ExyokiOffice::OpenXMLElementClass* ThreadedComments::StaticMetaClass() noexcept
{
    static const ThreadedCommentsMetaClass kMeta{};
    return &kMeta;
}

const ExyokiOffice::OpenXMLElementClass* ThreadedComments::ElementMetaClass() const noexcept
{
    return ThreadedComments::StaticMetaClass();
}

ExyokiOffice::MetadataParticlePtr CreatePersonListParticleMetadata()
{
    auto particleNode0 = std::make_shared<ExyokiOffice::MetadataSequenceParticle>(1, std::optional<ExyokiOffice::UInt32>{1}, ExyokiOffice::OpenXml::FileFormatVersions::Office2007, false);
    auto particleNode1 = std::make_shared<ExyokiOffice::MetadataElementParticle>(ExyokiOffice::OpenXmlQualifiedName("http://schemas.microsoft.com/office/spreadsheetml/2018/threadedcomments", "person"), "ExyokiOffice::DocumentFormat::OpenXml::Office2019::Excel::ThreadedComments::Person", "CT_Person/xltc:person", 0, std::optional<ExyokiOffice::UInt32>{}, ExyokiOffice::OpenXml::FileFormatVersions::Office2019);
    particleNode0->AddChild(particleNode1);
    auto particleNode2 = std::make_shared<ExyokiOffice::MetadataElementParticle>(ExyokiOffice::OpenXmlQualifiedName("http://schemas.microsoft.com/office/spreadsheetml/2018/threadedcomments", "extLst"), "ExyokiOffice::DocumentFormat::OpenXml::Office2019::Excel::ThreadedComments::ExtensionList", "CT_ExtensionList/xltc:extLst", 0, std::optional<ExyokiOffice::UInt32>{1}, ExyokiOffice::OpenXml::FileFormatVersions::Office2019);
    particleNode0->AddChild(particleNode2);
    return particleNode0;
}

namespace {
class PersonListMetaClass final : public ExyokiOffice::OpenXMLElementClass
{
public:
    const ExyokiOffice::OpenXMLElementClass* GetBaseMetaClass() const noexcept override
    {
        return OpenXmlCompositeElement::StaticMetaClass();
    }

    ExyokiOffice::OpenXmlQualifiedName QualifiedName() const noexcept override
    {
        return ExyokiOffice::OpenXmlQualifiedName("http://schemas.microsoft.com/office/spreadsheetml/2018/threadedcomments", "personList");
    }

    ExyokiOffice::OpenXmlQualifiedName TypeQualifiedName() const noexcept override
    {
        return ExyokiOffice::OpenXmlQualifiedName("http://schemas.microsoft.com/office/spreadsheetml/2018/threadedcomments", "CT_PersonList");
    }

    ExyokiOffice::OpenXml::FileFormatVersions GetVersion() const noexcept override
    {
        return ExyokiOffice::OpenXml::FileFormatVersions::Office2019;
    }

    ExyokiOffice::OpenXmlElementClassFlags GetFlags() const noexcept override
    {
        return ExyokiOffice::OpenXmlElementClassFlags{};
    }

    std::shared_ptr<ExyokiOffice::OpenXMLElement> Create() const override
    {
        return std::make_shared<PersonList>();
    }

    void ConfigureMetadata(ExyokiOffice::MetadataBuilder& builder) const override
    {
        builder.SetSchemaName("schemas_microsoft_com_office_spreadsheetml_2018_threadedcomments.json");
        builder.SetAvailability(ExyokiOffice::OpenXml::FileFormatVersions::Office2019);
        builder.SetParticleTree(CreatePersonListParticleMetadata());
    }
};
} // namespace

const ExyokiOffice::OpenXMLElementClass* PersonList::StaticMetaClass() noexcept
{
    static const PersonListMetaClass kMeta{};
    return &kMeta;
}

const ExyokiOffice::OpenXMLElementClass* PersonList::ElementMetaClass() const noexcept
{
    return PersonList::StaticMetaClass();
}

} // namespace ThreadedComments
} // namespace Excel
} // namespace Office2019
} // namespace OpenXml
} // namespace DocumentFormat
} // namespace ExyokiOffice
