// Copyright (c) 2026 Jakub Melka and Collaborators
// SPDX-License-Identifier: MIT
// See LICENSE file in the project root for full license text.
// -----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by ExyokiOffice OpenXML generator.
//     Manual changes to this file may cause unexpected behaviour.
// </auto-generated>
// -----------------------------------------------------------------------------

#include "ExyokiOffice/DOM/DocumentFormat/OpenXml/CustomXmlDataProperties.hpp"
#include "ExyokiOffice/FileFormatVersions.h"
#include "ExyokiOffice/StandardTypes.hpp"

#include <array>
#include <memory>
#include <optional>
#include <span>
#include <string_view>
#include <utility>
#include <vector>

namespace ExyokiOffice {
namespace DocumentFormat {
namespace OpenXml {
namespace CustomXmlDataProperties {

ExyokiOffice::MetadataParticlePtr CreateSchemaReferencesParticleMetadata()
{
    auto particleNode0 = std::make_shared<ExyokiOffice::MetadataSequenceParticle>(0, std::optional<ExyokiOffice::UInt32>{1}, ExyokiOffice::OpenXml::FileFormatVersions::Office2007, false);
    auto particleNode1 = std::make_shared<ExyokiOffice::MetadataElementParticle>(ExyokiOffice::OpenXmlQualifiedName("http://schemas.openxmlformats.org/officeDocument/2006/customXml", "schemaRef"), "ExyokiOffice::DocumentFormat::OpenXml::CustomXmlDataProperties::SchemaReference", "CT_DatastoreSchemaRef/ds:schemaRef", 0, std::optional<ExyokiOffice::UInt32>{}, ExyokiOffice::OpenXml::FileFormatVersions::Office2007);
    particleNode0->AddChild(particleNode1);
    return particleNode0;
}

namespace {
class SchemaReferencesMetaClass final : public ExyokiOffice::OpenXMLElementClass
{
public:
    const ExyokiOffice::OpenXMLElementClass* GetBaseMetaClass() const noexcept override
    {
        return OpenXmlCompositeElement::StaticMetaClass();
    }

    ExyokiOffice::OpenXmlQualifiedName QualifiedName() const noexcept override
    {
        return ExyokiOffice::OpenXmlQualifiedName("http://schemas.openxmlformats.org/officeDocument/2006/customXml", "schemaRefs");
    }

    ExyokiOffice::OpenXmlQualifiedName TypeQualifiedName() const noexcept override
    {
        return ExyokiOffice::OpenXmlQualifiedName("http://schemas.openxmlformats.org/officeDocument/2006/customXml", "CT_DatastoreSchemaRefs");
    }

    ExyokiOffice::OpenXml::FileFormatVersions GetVersion() const noexcept override
    {
        return ExyokiOffice::OpenXml::FileFormatVersions::Office2007;
    }

    ExyokiOffice::OpenXmlElementClassFlags GetFlags() const noexcept override
    {
        return ExyokiOffice::OpenXmlElementClassFlags{};
    }

    std::shared_ptr<ExyokiOffice::OpenXMLElement> Create() const override
    {
        return std::make_shared<SchemaReferences>();
    }

    void ConfigureMetadata(ExyokiOffice::MetadataBuilder& builder) const override
    {
        builder.SetSchemaName("schemas_openxmlformats_org_officeDocument_2006_customXml.json");
        builder.SetAvailability(ExyokiOffice::OpenXml::FileFormatVersions::Office2007);
        builder.SetParticleTree(CreateSchemaReferencesParticleMetadata());
    }
};
} // namespace

const ExyokiOffice::OpenXMLElementClass* SchemaReferences::StaticMetaClass() noexcept
{
    static const SchemaReferencesMetaClass kMeta{};
    return &kMeta;
}

const ExyokiOffice::OpenXMLElementClass* SchemaReferences::ElementMetaClass() const noexcept
{
    return SchemaReferences::StaticMetaClass();
}

namespace {
class SchemaReferenceMetaClass final : public ExyokiOffice::OpenXMLElementClass
{
public:
    const ExyokiOffice::OpenXMLElementClass* GetBaseMetaClass() const noexcept override
    {
        return OpenXmlLeafElement::StaticMetaClass();
    }

    ExyokiOffice::OpenXmlQualifiedName QualifiedName() const noexcept override
    {
        return ExyokiOffice::OpenXmlQualifiedName("http://schemas.openxmlformats.org/officeDocument/2006/customXml", "schemaRef");
    }

    ExyokiOffice::OpenXmlQualifiedName TypeQualifiedName() const noexcept override
    {
        return ExyokiOffice::OpenXmlQualifiedName("http://schemas.openxmlformats.org/officeDocument/2006/customXml", "CT_DatastoreSchemaRef");
    }

    ExyokiOffice::OpenXml::FileFormatVersions GetVersion() const noexcept override
    {
        return ExyokiOffice::OpenXml::FileFormatVersions::Office2007;
    }

    std::span<const ExyokiOffice::OpenXmlAttribute> GetAttributes() const noexcept override
    {
        static constexpr std::array<ExyokiOffice::OpenXmlAttribute, 1> kAttributes = {
            ExyokiOffice::OpenXmlAttribute(ExyokiOffice::OpenXmlQualifiedName("http://schemas.openxmlformats.org/officeDocument/2006/customXml", "uri"), "StringValue", ExyokiOffice::OpenXml::FileFormatVersions::Office2007, "Target Namespace of Associated XML Schema"),
        };
        return kAttributes;
    }

    ExyokiOffice::OpenXmlElementClassFlags GetFlags() const noexcept override
    {
        return ExyokiOffice::OpenXmlElementClassFlags{ExyokiOffice::OpenXmlElementClassFlag::IsLeafElement};
    }

    std::shared_ptr<ExyokiOffice::OpenXMLElement> Create() const override
    {
        return std::make_shared<SchemaReference>();
    }

    void ConfigureMetadata(ExyokiOffice::MetadataBuilder& builder) const override
    {
        builder.SetSchemaName("schemas_openxmlformats_org_officeDocument_2006_customXml.json");
        builder.SetAvailability(ExyokiOffice::OpenXml::FileFormatVersions::Office2007);
        auto& metadataAttribute0 = builder.AddAttribute(ExyokiOffice::OpenXmlQualifiedName("http://schemas.openxmlformats.org/officeDocument/2006/customXml", "uri"), "Uri", "StringValue", ExyokiOffice::OpenXml::FileFormatVersions::Office2007, "Target Namespace of Associated XML Schema");
        metadataAttribute0.Validators.push_back(std::make_shared<ExyokiOffice::MetadataRequiredConstraint>(ExyokiOffice::OpenXmlQualifiedName("http://schemas.openxmlformats.org/officeDocument/2006/customXml", "uri"), "Uri", true));
    }
};
} // namespace

const ExyokiOffice::OpenXMLElementClass* SchemaReference::StaticMetaClass() noexcept
{
    static const SchemaReferenceMetaClass kMeta{};
    return &kMeta;
}

const ExyokiOffice::OpenXMLElementClass* SchemaReference::ElementMetaClass() const noexcept
{
    return SchemaReference::StaticMetaClass();
}

StringValue SchemaReference::GetUri() const
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("http://schemas.openxmlformats.org/officeDocument/2006/customXml", "uri"));
    return GetAttributeValue<StringValue>(kAttribute);
}

void SchemaReference::SetUri(const StringValue& value)
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("http://schemas.openxmlformats.org/officeDocument/2006/customXml", "uri"));
    SetAttributeValue(kAttribute, value);
}

ExyokiOffice::MetadataParticlePtr CreateDataStoreItemParticleMetadata()
{
    auto particleNode0 = std::make_shared<ExyokiOffice::MetadataSequenceParticle>(0, std::optional<ExyokiOffice::UInt32>{1}, ExyokiOffice::OpenXml::FileFormatVersions::Office2007, false);
    auto particleNode1 = std::make_shared<ExyokiOffice::MetadataElementParticle>(ExyokiOffice::OpenXmlQualifiedName("http://schemas.openxmlformats.org/officeDocument/2006/customXml", "schemaRefs"), "ExyokiOffice::DocumentFormat::OpenXml::CustomXmlDataProperties::SchemaReferences", "SchemaReferences", 0, std::optional<ExyokiOffice::UInt32>{1}, ExyokiOffice::OpenXml::FileFormatVersions::Office2007);
    particleNode0->AddChild(particleNode1);
    return particleNode0;
}

namespace {
class DataStoreItemMetaClass final : public ExyokiOffice::OpenXMLElementClass
{
public:
    const ExyokiOffice::OpenXMLElementClass* GetBaseMetaClass() const noexcept override
    {
        return OpenXmlCompositeElement::StaticMetaClass();
    }

    ExyokiOffice::OpenXmlQualifiedName QualifiedName() const noexcept override
    {
        return ExyokiOffice::OpenXmlQualifiedName("http://schemas.openxmlformats.org/officeDocument/2006/customXml", "datastoreItem");
    }

    ExyokiOffice::OpenXmlQualifiedName TypeQualifiedName() const noexcept override
    {
        return ExyokiOffice::OpenXmlQualifiedName("http://schemas.openxmlformats.org/officeDocument/2006/customXml", "CT_DatastoreItem");
    }

    ExyokiOffice::OpenXml::FileFormatVersions GetVersion() const noexcept override
    {
        return ExyokiOffice::OpenXml::FileFormatVersions::Office2007;
    }

    std::span<const ExyokiOffice::OpenXmlAttribute> GetAttributes() const noexcept override
    {
        static constexpr std::array<ExyokiOffice::OpenXmlAttribute, 1> kAttributes = {
            ExyokiOffice::OpenXmlAttribute(ExyokiOffice::OpenXmlQualifiedName("http://schemas.openxmlformats.org/officeDocument/2006/customXml", "itemID"), "StringValue", ExyokiOffice::OpenXml::FileFormatVersions::Office2007, "Custom XML Data ID"),
        };
        return kAttributes;
    }

    ExyokiOffice::OpenXmlElementClassFlags GetFlags() const noexcept override
    {
        return ExyokiOffice::OpenXmlElementClassFlags{};
    }

    std::shared_ptr<ExyokiOffice::OpenXMLElement> Create() const override
    {
        return std::make_shared<DataStoreItem>();
    }

    void ConfigureMetadata(ExyokiOffice::MetadataBuilder& builder) const override
    {
        builder.SetSchemaName("schemas_openxmlformats_org_officeDocument_2006_customXml.json");
        builder.SetAvailability(ExyokiOffice::OpenXml::FileFormatVersions::Office2007);
        auto& metadataAttribute0 = builder.AddAttribute(ExyokiOffice::OpenXmlQualifiedName("http://schemas.openxmlformats.org/officeDocument/2006/customXml", "itemID"), "ItemId", "StringValue", ExyokiOffice::OpenXml::FileFormatVersions::Office2007, "Custom XML Data ID");
        metadataAttribute0.Validators.push_back(std::make_shared<ExyokiOffice::MetadataRequiredConstraint>(ExyokiOffice::OpenXmlQualifiedName("http://schemas.openxmlformats.org/officeDocument/2006/customXml", "itemID"), "ItemId", true));
        metadataAttribute0.Validators.push_back(std::make_shared<ExyokiOffice::MetadataStringConstraint>(ExyokiOffice::OpenXmlQualifiedName("http://schemas.openxmlformats.org/officeDocument/2006/customXml", "itemID"), "ItemId", std::optional<ExyokiOffice::Size>{}, std::optional<ExyokiOffice::Size>{}, std::optional<ExyokiOffice::Size>{}, std::optional<std::string>{std::string("\\{[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}\\}")}, true, false, false, false, false));
        builder.SetParticleTree(CreateDataStoreItemParticleMetadata());
    }
};
} // namespace

const ExyokiOffice::OpenXMLElementClass* DataStoreItem::StaticMetaClass() noexcept
{
    static const DataStoreItemMetaClass kMeta{};
    return &kMeta;
}

const ExyokiOffice::OpenXMLElementClass* DataStoreItem::ElementMetaClass() const noexcept
{
    return DataStoreItem::StaticMetaClass();
}

StringValue DataStoreItem::GetItemId() const
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("http://schemas.openxmlformats.org/officeDocument/2006/customXml", "itemID"));
    return GetAttributeValue<StringValue>(kAttribute);
}

void DataStoreItem::SetItemId(const StringValue& value)
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("http://schemas.openxmlformats.org/officeDocument/2006/customXml", "itemID"));
    SetAttributeValue(kAttribute, value);
}

} // namespace CustomXmlDataProperties
} // namespace OpenXml
} // namespace DocumentFormat
} // namespace ExyokiOffice
