// Copyright (c) 2026 Jakub Melka and Collaborators
// SPDX-License-Identifier: MIT
// See LICENSE file in the project root for full license text.
// -----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by ExyokiOffice OpenXML generator.
//     Manual changes to this file may cause unexpected behaviour.
// </auto-generated>
// -----------------------------------------------------------------------------

#pragma once

#include "ExyokiOffice/OpenXMLElement.hpp"

#include <memory>
#include <span>
#include <string_view>

namespace ExyokiOffice {
namespace DocumentFormat {
namespace OpenXml {
namespace Office2013 {
namespace WebExtentionPane {


using OpenXMLElement = ExyokiOffice::OpenXMLElement;
using OpenXmlCompositeElement = ExyokiOffice::OpenXmlCompositeElement;
using OpenXmlPartRootElement = ExyokiOffice::OpenXmlPartRootElement;
using OpenXmlLeafElement = ExyokiOffice::OpenXmlLeafElement;
using OpenXmlLeafTextElement = ExyokiOffice::OpenXmlLeafTextElement;

/// \brief Defines the WebExtensionTaskpane Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office2013.WebExtentionPane
/// Type QName: wetp:CT_OsfTaskpane
/// Element QName: wetp:taskpane
/// Source: schemas_microsoft_com_office_webextensions_taskpanes_2010_11.json
class EXYOKIOFFICE_EXPORT WebExtensionTaskpane : public OpenXmlCompositeElement
{
public:
    using Ptr = std::shared_ptr<WebExtensionTaskpane>;

    inline WebExtensionTaskpane() = default;
    inline ~WebExtensionTaskpane() = default;

    /// dockstate
    StringValue GetDockState() const;
    void SetDockState(const StringValue& value);

    /// visibility
    BooleanValue GetVisibility() const;
    void SetVisibility(const BooleanValue& value);

    /// width
    DoubleValue GetWidth() const;
    void SetWidth(const DoubleValue& value);

    /// row
    UInt32Value GetRow() const;
    void SetRow(const UInt32Value& value);

    /// locked
    BooleanValue GetLocked() const;
    void SetLocked(const BooleanValue& value);

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the OfficeArtExtensionList Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office2013.WebExtentionPane
/// Type QName: a:CT_OfficeArtExtensionList
/// Element QName: wetp:extLst
/// Source: schemas_microsoft_com_office_webextensions_taskpanes_2010_11.json
class EXYOKIOFFICE_EXPORT OfficeArtExtensionList : public OpenXmlCompositeElement
{
public:
    using Ptr = std::shared_ptr<OfficeArtExtensionList>;

    inline OfficeArtExtensionList() = default;
    inline ~OfficeArtExtensionList() = default;

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the WebExtensionPartReference Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office2013.WebExtentionPane
/// Type QName: we:CT_WebExtensionPartRef
/// Element QName: wetp:webextensionref
/// Source: schemas_microsoft_com_office_webextensions_taskpanes_2010_11.json
class EXYOKIOFFICE_EXPORT WebExtensionPartReference : public OpenXmlLeafElement
{
public:
    using Ptr = std::shared_ptr<WebExtensionPartReference>;

    inline WebExtensionPartReference() = default;
    inline ~WebExtensionPartReference() = default;

    /// id
    StringValue GetId() const;
    void SetId(const StringValue& value);

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the Taskpanes Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office2013.WebExtentionPane
/// Type QName: wetp:CT_OsfTaskpanes
/// Element QName: wetp:taskpanes
/// Source: schemas_microsoft_com_office_webextensions_taskpanes_2010_11.json
class EXYOKIOFFICE_EXPORT Taskpanes : public OpenXmlCompositeElement
{
public:
    using Ptr = std::shared_ptr<Taskpanes>;

    inline Taskpanes() = default;
    inline ~Taskpanes() = default;

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

} // namespace WebExtentionPane
} // namespace Office2013
} // namespace OpenXml
} // namespace DocumentFormat
} // namespace ExyokiOffice
