// Copyright (c) 2026 Jakub Melka and Collaborators
// SPDX-License-Identifier: MIT
// See LICENSE file in the project root for full license text.
// -----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by ExyokiOffice OpenXML generator.
//     Manual changes to this file may cause unexpected behaviour.
// </auto-generated>
// -----------------------------------------------------------------------------

#pragma once

#include "ExyokiOffice/OpenXMLElement.hpp"

namespace ExyokiOffice {
namespace DocumentFormat {
namespace OpenXml {
namespace Drawing {


/// \brief Font Collection Index
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Drawing
/// Type QName: a:ST_FontCollectionIndex
/// Element QName: (none)
/// Source: schemas_openxmlformats_org_drawingml_2006_main.json
class FontCollectionIndexValues : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        Major, ///< Major Font
        Minor, ///< Minor Font
        None, ///< None
    };

    constexpr FontCollectionIndexValues() noexcept = default;
    constexpr FontCollectionIndexValues(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Theme Color Reference
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Drawing
/// Type QName: a:ST_ColorSchemeIndex
/// Element QName: (none)
/// Source: schemas_openxmlformats_org_drawingml_2006_main.json
class ColorSchemeIndexValues : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        Dark1, ///< Dark 1
        Light1, ///< Light 1
        Dark2, ///< Dark 2
        Light2, ///< Light 2
        Accent1, ///< Accent 1
        Accent2, ///< Accent 2
        Accent3, ///< Accent 3
        Accent4, ///< Accent 4
        Accent5, ///< Accent 5
        Accent6, ///< Accent 6
        Hyperlink, ///< Hyperlink
        FollowedHyperlink, ///< Followed Hyperlink
    };

    constexpr ColorSchemeIndexValues() noexcept = default;
    constexpr ColorSchemeIndexValues(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief System Color Value
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Drawing
/// Type QName: a:ST_SystemColorVal
/// Element QName: (none)
/// Source: schemas_openxmlformats_org_drawingml_2006_main.json
class SystemColorValues : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        ScrollBar, ///< Scroll Bar System Color
        Background, ///< Background System Color
        ActiveCaption, ///< Active Caption System Color
        InactiveCaption, ///< Inactive Caption System Color
        Menu, ///< Menu System Color
        Window, ///< Window System Color
        WindowFrame, ///< Window Frame System Color
        MenuText, ///< Menu Text System Color
        WindowText, ///< Window Text System Color
        CaptionText, ///< Caption Text System Color
        ActiveBorder, ///< Active Border System Color
        InactiveBorder, ///< Inactive Border System Color
        ApplicationWorkspace, ///< Application Workspace System Color
        Highlight, ///< Highlight System Color
        HighlightText, ///< Highlight Text System Color
        ButtonFace, ///< Button Face System Color
        ButtonShadow, ///< Button Shadow System Color
        GrayText, ///< Gray Text System Color
        ButtonText, ///< Button Text System Color
        InactiveCaptionText, ///< Inactive Caption Text System Color
        ButtonHighlight, ///< Button Highlight System Color
        ThreeDDarkShadow, ///< 3D Dark System Color
        ThreeDLight, ///< 3D Light System Color
        InfoText, ///< Info Text System Color
        InfoBack, ///< Info Back System Color
        HotLight, ///< Hot Light System Color
        GradientActiveCaption, ///< Gradient Active Caption System Color
        GradientInactiveCaption, ///< Gradient Inactive Caption System Color
        MenuHighlight, ///< Menu Highlight System Color
        MenuBar, ///< Menu Bar System Color
    };

    constexpr SystemColorValues() noexcept = default;
    constexpr SystemColorValues(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Scheme Color
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Drawing
/// Type QName: a:ST_SchemeColorVal
/// Element QName: (none)
/// Source: schemas_openxmlformats_org_drawingml_2006_main.json
class SchemeColorValues : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        Background1, ///< Background Color 1
        Text1, ///< Text Color 1
        Background2, ///< Background Color 2
        Text2, ///< Text Color 2
        Accent1, ///< Accent Color 1
        Accent2, ///< Accent Color 2
        Accent3, ///< Accent Color 3
        Accent4, ///< Accent Color 4
        Accent5, ///< Accent Color 5
        Accent6, ///< Accent Color 6
        Hyperlink, ///< Hyperlink Color
        FollowedHyperlink, ///< Followed Hyperlink Color
        PhColor, ///< Style Color
        Dark1, ///< Dark Color 1
        Light1, ///< Light Color 1
        Dark2, ///< Dark Color 2
        Light2, ///< Light Color 2
    };

    constexpr SchemeColorValues() noexcept = default;
    constexpr SchemeColorValues(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Rectangle Alignments
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Drawing
/// Type QName: a:ST_RectAlignment
/// Element QName: (none)
/// Source: schemas_openxmlformats_org_drawingml_2006_main.json
class RectangleAlignmentValues : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        TopLeft, ///< Rectangle Alignment Enum ( Top Left )
        Top, ///< Rectangle Alignment Enum ( Top )
        TopRight, ///< Rectangle Alignment Enum ( Top Right )
        Left, ///< Rectangle Alignment Enum ( Left )
        Center, ///< Rectangle Alignment Enum ( Center )
        Right, ///< Rectangle Alignment Enum ( Right )
        BottomLeft, ///< Rectangle Alignment Enum ( Bottom Left )
        Bottom, ///< Rectangle Alignment Enum ( Bottom )
        BottomRight, ///< Rectangle Alignment Enum ( Bottom Right )
    };

    constexpr RectangleAlignmentValues() noexcept = default;
    constexpr RectangleAlignmentValues(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Black and White Mode
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Drawing
/// Type QName: a:ST_BlackWhiteMode
/// Element QName: (none)
/// Source: schemas_openxmlformats_org_drawingml_2006_main.json
class BlackWhiteModeValues : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        Color, ///< Color
        Auto, ///< Automatic
        Gray, ///< Gray
        LightGray, ///< Light Gray
        InvGray, ///< Inverse Gray
        GrayWhite, ///< Gray and White
        BlackGray, ///< Black and Gray
        BlackWhite, ///< Black and White
        Black, ///< Black
        White, ///< White
        Hidden, ///< Hidden
    };

    constexpr BlackWhiteModeValues() noexcept = default;
    constexpr BlackWhiteModeValues(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Chart Animation Build Step
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Drawing
/// Type QName: a:ST_ChartBuildStep
/// Element QName: (none)
/// Source: schemas_openxmlformats_org_drawingml_2006_main.json
class ChartBuildStepValues : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        Category, ///< Category
        CategoryPoints, ///< Category Points
        Series, ///< Series
        SeriesPoints, ///< Series Points
        AllPoints, ///< All Points
        GridLegend, ///< Grid and Legend
    };

    constexpr ChartBuildStepValues() noexcept = default;
    constexpr ChartBuildStepValues(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Diagram Animation Build Steps
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Drawing
/// Type QName: a:ST_DgmBuildStep
/// Element QName: (none)
/// Source: schemas_openxmlformats_org_drawingml_2006_main.json
class DiagramBuildStepValues : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        Shape, ///< Shape
        Background, ///< Background
    };

    constexpr DiagramBuildStepValues() noexcept = default;
    constexpr DiagramBuildStepValues(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Animation Build Type
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Drawing
/// Type QName: a:ST_AnimationBuildType
/// Element QName: (none)
/// Source: schemas_openxmlformats_org_drawingml_2006_main.json
class AnimationBuildValues : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        AllAtOnce, ///< Animate At Once
    };

    constexpr AnimationBuildValues() noexcept = default;
    constexpr AnimationBuildValues(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Diagram only Animation Types
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Drawing
/// Type QName: a:ST_AnimationDgmOnlyBuildType
/// Element QName: (none)
/// Source: schemas_openxmlformats_org_drawingml_2006_main.json
class AnimationDiagramOnlyBuildValues : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        One, ///< Elements One-by-One
        LevelOne, ///< Level One-by-One
        LevelAtOnce, ///< Each Level at Once
    };

    constexpr AnimationDiagramOnlyBuildValues() noexcept = default;
    constexpr AnimationDiagramOnlyBuildValues(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Chart only Animation Types
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Drawing
/// Type QName: a:ST_AnimationChartOnlyBuildType
/// Element QName: (none)
/// Source: schemas_openxmlformats_org_drawingml_2006_main.json
class AnimationChartOnlyBuildValues : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        Series, ///< Series
        Category, ///< Category
        SeriesElement, ///< Series Element
        CategoryElement, ///< Category Element
    };

    constexpr AnimationChartOnlyBuildValues() noexcept = default;
    constexpr AnimationChartOnlyBuildValues(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Preset Camera Type
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Drawing
/// Type QName: a:ST_PresetCameraType
/// Element QName: (none)
/// Source: schemas_openxmlformats_org_drawingml_2006_main.json
class PresetCameraValues : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        LegacyObliqueTopLeft, ///< Legacy Oblique Top Left
        LegacyObliqueTop, ///< Legacy Oblique Top
        LegacyObliqueTopRight, ///< Legacy Oblique Top Right
        LegacyObliqueLeft, ///< Legacy Oblique Left
        LegacyObliqueFront, ///< Legacy Oblique Front
        LegacyObliqueRight, ///< Legacy Oblique Right
        LegacyObliqueBottomLeft, ///< Legacy Oblique Bottom Left
        LegacyObliqueBottom, ///< Legacy Oblique Bottom
        LegacyObliqueBottomRight, ///< Legacy Oblique Bottom Right
        LegacyPerspectiveTopLeft, ///< Legacy Perspective Top Left
        LegacyPerspectiveTop, ///< Legacy Perspective Top
        LegacyPerspectiveTopRight, ///< Legacy Perspective Top Right
        LegacyPerspectiveLeft, ///< Legacy Perspective Left
        LegacyPerspectiveFront, ///< Legacy Perspective Front
        LegacyPerspectiveRight, ///< Legacy Perspective Right
        LegacyPerspectiveBottomLeft, ///< Legacy Perspective Bottom Left
        LegacyPerspectiveBottom, ///< Legacy Perspective Bottom
        LegacyPerspectiveBottomRight, ///< Legacy Perspective Bottom Right
        OrthographicFront, ///< Orthographic Front
        IsometricTopUp, ///< Isometric Top Up
        IsometricTopDown, ///< Isometric Top Down
        IsometricBottomUp, ///< Isometric Bottom Up
        IsometricBottomDown, ///< Isometric Bottom Down
        IsometricLeftUp, ///< Isometric Left Up
        IsometricLeftDown, ///< Isometric Left Down
        IsometricRightUp, ///< Isometric Right Up
        IsometricRightDown, ///< Isometric Right Down
        IsometricOffAxis1Left, ///< Isometric Off Axis 1 Left
        IsometricOffAxis1Right, ///< Isometric Off Axis 1 Right
        IsometricOffAxis1Top, ///< Isometric Off Axis 1 Top
        IsometricOffAxis2Left, ///< Isometric Off Axis 2 Left
        IsometricOffAxis2Right, ///< Isometric Off Axis 2 Right
        IsometricOffAxis2Top, ///< Isometric Off Axis 2 Top
        IsometricOffAxis3Left, ///< Isometric Off Axis 3 Left
        IsometricOffAxis3Right, ///< Isometric Off Axis 3 Right
        IsometricOffAxis3Bottom, ///< Isometric Off Axis 3 Bottom
        IsometricOffAxis4Left, ///< Isometric Off Axis 4 Left
        IsometricOffAxis4Right, ///< Isometric Off Axis 4 Right
        IsometricOffAxis4Bottom, ///< Isometric Off Axis 4 Bottom
        ObliqueTopLeft, ///< Oblique Top Left
        ObliqueTop, ///< Oblique Top
        ObliqueTopRight, ///< Oblique Top Right
        ObliqueLeft, ///< Oblique Left
        ObliqueRight, ///< Oblique Right
        ObliqueBottomLeft, ///< Oblique Bottom Left
        ObliqueBottom, ///< Oblique Bottom
        ObliqueBottomRight, ///< Oblique Bottom Right
        PerspectiveFront, ///< Perspective Front
        PerspectiveLeft, ///< Perspective Left
        PerspectiveRight, ///< Perspective Right
        PerspectiveAbove, ///< Orthographic Above
        PerspectiveBelow, ///< Perspective Below
        PerspectiveAboveLeftFacing, ///< Perspective Above Left Facing
        PerspectiveAboveRightFacing, ///< Perspective Above Right Facing
        PerspectiveContrastingLeftFacing, ///< Perspective Contrasting Left Facing
        PerspectiveContrastingRightFacing, ///< Perspective Contrasting Right Facing
        PerspectiveHeroicLeftFacing, ///< Perspective Heroic Left Facing
        PerspectiveHeroicRightFacing, ///< Perspective Heroic Right Facing
        PerspectiveHeroicExtremeLeftFacing, ///< Perspective Heroic Extreme Left Facing
        PerspectiveHeroicExtremeRightFacing, ///< Perspective Heroic Extreme Right Facing
        PerspectiveRelaxed, ///< Perspective Relaxed
        PerspectiveRelaxedModerately, ///< Perspective Relaxed Moderately
    };

    constexpr PresetCameraValues() noexcept = default;
    constexpr PresetCameraValues(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Light Rig Direction
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Drawing
/// Type QName: a:ST_LightRigDirection
/// Element QName: (none)
/// Source: schemas_openxmlformats_org_drawingml_2006_main.json
class LightRigDirectionValues : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        TopLeft, ///< Top Left
        Top, ///< Top
        TopRight, ///< Top Right
        Left, ///< Left
        Right, ///< Right
        BottomLeft, ///< Bottom Left
        Bottom, ///< Bottom
        BottomRight, ///< Bottom Right
    };

    constexpr LightRigDirectionValues() noexcept = default;
    constexpr LightRigDirectionValues(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Light Rig Type
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Drawing
/// Type QName: a:ST_LightRigType
/// Element QName: (none)
/// Source: schemas_openxmlformats_org_drawingml_2006_main.json
class LightRigValues : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        LegacyFlat1, ///< Legacy Flat 1
        LegacyFlat2, ///< Legacy Flat 2
        LegacyFlat3, ///< Legacy Flat 3
        LegacyFlat4, ///< Legacy Flat 4
        LegacyNormal1, ///< Legacy Normal 1
        LegacyNormal2, ///< Legacy Normal 2
        LegacyNormal3, ///< Legacy Normal 3
        LegacyNormal4, ///< Legacy Normal 4
        LegacyHarsh1, ///< Legacy Harsh 1
        LegacyHarsh2, ///< Legacy Harsh 2
        LegacyHarsh3, ///< Legacy Harsh 3
        LegacyHarsh4, ///< Legacy Harsh 4
        ThreePoints, ///< Three Point
        Balanced, ///< Light Rig Enum ( Balanced )
        Soft, ///< Soft
        Harsh, ///< Harsh
        Flood, ///< Flood
        Contrasting, ///< Contrasting
        Morning, ///< Morning
        Sunrise, ///< Sunrise
        Sunset, ///< Sunset
        Chilly, ///< Chilly
        Freezing, ///< Freezing
        Flat, ///< Flat
        TwoPoints, ///< Two Point
        Glow, ///< Glow
        BrightRoom, ///< Bright Room
    };

    constexpr LightRigValues() noexcept = default;
    constexpr LightRigValues(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Bevel Presets
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Drawing
/// Type QName: a:ST_BevelPresetType
/// Element QName: (none)
/// Source: schemas_openxmlformats_org_drawingml_2006_main.json
class BevelPresetValues : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        RelaxedInset, ///< Relaxed Inset
        Circle, ///< Circle
        Slope, ///< Slope
        Cross, ///< Cross
        Angle, ///< Angle
        SoftRound, ///< Soft Round
        Convex, ///< Convex
        CoolSlant, ///< Cool Slant
        Divot, ///< Divot
        Riblet, ///< Riblet
        HardEdge, ///< Hard Edge
        ArtDeco, ///< Art Deco
    };

    constexpr BevelPresetValues() noexcept = default;
    constexpr BevelPresetValues(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Preset Material Type
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Drawing
/// Type QName: a:ST_PresetMaterialType
/// Element QName: (none)
/// Source: schemas_openxmlformats_org_drawingml_2006_main.json
class PresetMaterialTypeValues : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        LegacyMatte, ///< Legacy Matte
        LegacyPlastic, ///< Legacy Plastic
        LegacyMetal, ///< Legacy Metal
        LegacyWireframe, ///< Legacy Wireframe
        Matte, ///< Matte
        Plastic, ///< Plastic
        Metal, ///< Metal
        WarmMatte, ///< Warm Matte
        TranslucentPowder, ///< Translucent Powder
        Powder, ///< Powder
        DarkEdge, ///< Dark Edge
        SoftEdge, ///< Soft Edge
        Clear, ///< Clear
        Flat, ///< Flat
        SoftMetal, ///< Soft Metal
    };

    constexpr PresetMaterialTypeValues() noexcept = default;
    constexpr PresetMaterialTypeValues(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Preset Shadow Type
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Drawing
/// Type QName: a:ST_PresetShadowVal
/// Element QName: (none)
/// Source: schemas_openxmlformats_org_drawingml_2006_main.json
class PresetShadowValues : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        TopLeftDropShadow, ///< Top Left Drop Shadow
        TopRightDropShadow, ///< Top Right Drop Shadow
        BackLeftPerspectiveShadow, ///< Back Left Perspective Shadow
        BackRightPerspectiveShadow, ///< Back Right Perspective Shadow
        BottomLeftDropShadow, ///< Bottom Left Drop Shadow
        BottomRightDropShadow, ///< Bottom Right Drop Shadow
        FrontLeftPerspectiveShadow, ///< Front Left Perspective Shadow
        FrontRightPerspectiveShadow, ///< Front Right Perspective Shadow
        TopLeftSmallDropShadow, ///< Top Left Small Drop Shadow
        TopLeftLargeDropShadow, ///< Top Left Large Drop Shadow
        BackLeftLongPerspectiveShadow, ///< Back Left Long Perspective Shadow
        BackRightLongPerspectiveShadow, ///< Back Right Long Perspective Shadow
        TopLeftDoubleDropShadow, ///< Top Left Double Drop Shadow
        BottomRightSmallDropShadow, ///< Bottom Right Small Drop Shadow
        FrontLeftLongPerspectiveShadow, ///< Front Left Long Perspective Shadow
        FrontRightLongPerspectiveShadow, ///< Front Right LongPerspective Shadow
        ThreeDimensionalOuterBoxShadow, ///< 3D Outer Box Shadow
        ThreeDimensionalInnerBoxShadow, ///< 3D Inner Box Shadow
        BackCenterPerspectiveShadow, ///< Back Center Perspective Shadow
        FrontBottomShadow, ///< Front Bottom Shadow
    };

    constexpr PresetShadowValues() noexcept = default;
    constexpr PresetShadowValues(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Path Shade Type
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Drawing
/// Type QName: a:ST_PathShadeType
/// Element QName: (none)
/// Source: schemas_openxmlformats_org_drawingml_2006_main.json
class PathShadeValues : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        Shape, ///< Shape
        Circle, ///< Circle
        Rectangle, ///< Rectangle
    };

    constexpr PathShadeValues() noexcept = default;
    constexpr PathShadeValues(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Tile Flip Mode
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Drawing
/// Type QName: a:ST_TileFlipMode
/// Element QName: (none)
/// Source: schemas_openxmlformats_org_drawingml_2006_main.json
class TileFlipValues : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        None, ///< None
        Horizontal, ///< Horizontal
        Vertical, ///< Vertical
        HorizontalAndVertical, ///< Horizontal and Vertical
    };

    constexpr TileFlipValues() noexcept = default;
    constexpr TileFlipValues(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Blip Compression Type
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Drawing
/// Type QName: a:ST_BlipCompression
/// Element QName: (none)
/// Source: schemas_openxmlformats_org_drawingml_2006_main.json
class BlipCompressionValues : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        Email, ///< Email Compression
        Screen, ///< Screen Viewing Compression
        Print, ///< Printing Compression
        HighQualityPrint, ///< High Quality Printing Compression
        None, ///< No Compression
    };

    constexpr BlipCompressionValues() noexcept = default;
    constexpr BlipCompressionValues(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Preset Pattern Value
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Drawing
/// Type QName: a:ST_PresetPatternVal
/// Element QName: (none)
/// Source: schemas_openxmlformats_org_drawingml_2006_main.json
class PresetPatternValues : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        Percent5, ///< 5%
        Percent10, ///< 10%
        Percent20, ///< 20%
        Percent25, ///< 25%
        Percent30, ///< 30%
        Percent40, ///< 40%
        Percent50, ///< 50%
        Percent60, ///< 60%
        Percent70, ///< 70%
        Percent75, ///< 75%
        Percent80, ///< 80%
        Percent90, ///< 90%
        Horizontal, ///< Horizontal
        Vertical, ///< Vertical
        LightHorizontal, ///< Light Horizontal
        LightVertical, ///< Light Vertical
        DarkHorizontal, ///< Dark Horizontal
        DarkVertical, ///< Dark Vertical
        NarrowHorizontal, ///< Narrow Horizontal
        NarrowVertical, ///< Narrow Vertical
        DashedHorizontal, ///< Dashed Horizontal
        DashedVertical, ///< Dashed Vertical
        Cross, ///< Cross
        DownwardDiagonal, ///< Downward Diagonal
        UpwardDiagonal, ///< Upward Diagonal
        LightDownwardDiagonal, ///< Light Downward Diagonal
        LightUpwardDiagonal, ///< Light Upward Diagonal
        DarkDownwardDiagonal, ///< Dark Downward Diagonal
        DarkUpwardDiagonal, ///< Dark Upward Diagonal
        WideDownwardDiagonal, ///< Wide Downward Diagonal
        WideUpwardDiagonal, ///< Wide Upward Diagonal
        DashedDownwardDiagonal, ///< Dashed Downward Diagonal
        DashedUpwardDiagonal, ///< Dashed Upward DIagonal
        DiagonalCross, ///< Diagonal Cross
        SmallCheck, ///< Small Checker Board
        LargeCheck, ///< Large Checker Board
        SmallGrid, ///< Small Grid
        LargeGrid, ///< Large Grid
        DotGrid, ///< Dotted Grid
        SmallConfetti, ///< Small Confetti
        LargeConfetti, ///< Large Confetti
        HorizontalBrick, ///< Horizontal Brick
        DiagonalBrick, ///< Diagonal Brick
        SolidDiamond, ///< Solid Diamond
        OpenDiamond, ///< Open Diamond
        DottedDiamond, ///< Dotted Diamond
        Plaid, ///< Plaid
        Sphere, ///< Sphere
        Weave, ///< Weave
        Divot, ///< Divot
        Shingle, ///< Shingle
        Wave, ///< Wave
        Trellis, ///< Trellis
        ZigZag, ///< Zig Zag
    };

    constexpr PresetPatternValues() noexcept = default;
    constexpr PresetPatternValues(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Blend Mode
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Drawing
/// Type QName: a:ST_BlendMode
/// Element QName: (none)
/// Source: schemas_openxmlformats_org_drawingml_2006_main.json
class BlendModeValues : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        Overlay, ///< Overlay
        Multiply, ///< Multiply
        Screen, ///< Screen
        Darken, ///< Darken
        Lighten, ///< Lighten
    };

    constexpr BlendModeValues() noexcept = default;
    constexpr BlendModeValues(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Effect Container Type
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Drawing
/// Type QName: a:ST_EffectContainerType
/// Element QName: (none)
/// Source: schemas_openxmlformats_org_drawingml_2006_main.json
class EffectContainerValues : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        Sibling, ///< Sibling
        Tree, ///< Tree
    };

    constexpr EffectContainerValues() noexcept = default;
    constexpr EffectContainerValues(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Preset Shape Types
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Drawing
/// Type QName: a:ST_ShapeType
/// Element QName: (none)
/// Source: schemas_openxmlformats_org_drawingml_2006_main.json
class ShapeTypeValues : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        Line, ///< Line Shape
        LineInverse, ///< Line Inverse Shape
        Triangle, ///< Triangle Shape
        RightTriangle, ///< Right Triangle Shape
        Rectangle, ///< Rectangle Shape
        Diamond, ///< Diamond Shape
        Parallelogram, ///< Parallelogram Shape
        Trapezoid, ///< Trapezoid Shape
        NonIsoscelesTrapezoid, ///< Non-Isosceles Trapezoid Shape
        Pentagon, ///< Pentagon Shape
        Hexagon, ///< Hexagon Shape
        Heptagon, ///< Heptagon Shape
        Octagon, ///< Octagon Shape
        Decagon, ///< Decagon Shape
        Dodecagon, ///< Dodecagon Shape
        Star4, ///< Four Pointed Star Shape
        Star5, ///< Five Pointed Star Shape
        Star6, ///< Six Pointed Star Shape
        Star7, ///< Seven Pointed Star Shape
        Star8, ///< Eight Pointed Star Shape
        Star10, ///< Ten Pointed Star Shape
        Star12, ///< Twelve Pointed Star Shape
        Star16, ///< Sixteen Pointed Star Shape
        Star24, ///< Twenty Four Pointed Star Shape
        Star32, ///< Thirty Two Pointed Star Shape
        RoundRectangle, ///< Round Corner Rectangle Shape
        Round1Rectangle, ///< One Round Corner Rectangle Shape
        Round2SameRectangle, ///< Two Same-side Round Corner Rectangle Shape
        Round2DiagonalRectangle, ///< Two Diagonal Round Corner Rectangle Shape
        SnipRoundRectangle, ///< One Snip One Round Corner Rectangle Shape
        Snip1Rectangle, ///< One Snip Corner Rectangle Shape
        Snip2SameRectangle, ///< Two Same-side Snip Corner Rectangle Shape
        Snip2DiagonalRectangle, ///< Two Diagonal Snip Corner Rectangle Shape
        Plaque, ///< Plaque Shape
        Ellipse, ///< Ellipse Shape
        Teardrop, ///< Teardrop Shape
        HomePlate, ///< Home Plate Shape
        Chevron, ///< Chevron Shape
        PieWedge, ///< Pie Wedge Shape
        Pie, ///< Pie Shape
        BlockArc, ///< Block Arc Shape
        Donut, ///< Donut Shape
        NoSmoking, ///< No Smoking Shape
        RightArrow, ///< Right Arrow Shape
        LeftArrow, ///< Left Arrow Shape
        UpArrow, ///< Up Arrow Shape
        DownArrow, ///< Down Arrow Shape
        StripedRightArrow, ///< Striped Right Arrow Shape
        NotchedRightArrow, ///< Notched Right Arrow Shape
        BentUpArrow, ///< Bent Up Arrow Shape
        LeftRightArrow, ///< Left Right Arrow Shape
        UpDownArrow, ///< Up Down Arrow Shape
        LeftUpArrow, ///< Left Up Arrow Shape
        LeftRightUpArrow, ///< Left Right Up Arrow Shape
        QuadArrow, ///< Quad-Arrow Shape
        LeftArrowCallout, ///< Callout Left Arrow Shape
        RightArrowCallout, ///< Callout Right Arrow Shape
        UpArrowCallout, ///< Callout Up Arrow Shape
        DownArrowCallout, ///< Callout Down Arrow Shape
        LeftRightArrowCallout, ///< Callout Left Right Arrow Shape
        UpDownArrowCallout, ///< Callout Up Down Arrow Shape
        QuadArrowCallout, ///< Callout Quad-Arrow Shape
        BentArrow, ///< Bent Arrow Shape
        UTurnArrow, ///< U-Turn Arrow Shape
        CircularArrow, ///< Circular Arrow Shape
        LeftCircularArrow, ///< Left Circular Arrow Shape
        LeftRightCircularArrow, ///< Left Right Circular Arrow Shape
        CurvedRightArrow, ///< Curved Right Arrow Shape
        CurvedLeftArrow, ///< Curved Left Arrow Shape
        CurvedUpArrow, ///< Curved Up Arrow Shape
        CurvedDownArrow, ///< Curved Down Arrow Shape
        SwooshArrow, ///< Swoosh Arrow Shape
        Cube, ///< Cube Shape
        Can, ///< Can Shape
        LightningBolt, ///< Lightning Bolt Shape
        Heart, ///< Heart Shape
        Sun, ///< Sun Shape
        Moon, ///< Moon Shape
        SmileyFace, ///< Smiley Face Shape
        IrregularSeal1, ///< Irregular Seal 1 Shape
        IrregularSeal2, ///< Irregular Seal 2 Shape
        FoldedCorner, ///< Folded Corner Shape
        Bevel, ///< Bevel Shape
        Frame, ///< Frame Shape
        HalfFrame, ///< Half Frame Shape
        Corner, ///< Corner Shape
        DiagonalStripe, ///< Diagonal Stripe Shape
        Chord, ///< Chord Shape
        Arc, ///< Curved Arc Shape
        LeftBracket, ///< Left Bracket Shape
        RightBracket, ///< Right Bracket Shape
        LeftBrace, ///< Left Brace Shape
        RightBrace, ///< Right Brace Shape
        BracketPair, ///< Bracket Pair Shape
        BracePair, ///< Brace Pair Shape
        StraightConnector1, ///< Straight Connector 1 Shape
        BentConnector2, ///< Bent Connector 2 Shape
        BentConnector3, ///< Bent Connector 3 Shape
        BentConnector4, ///< Bent Connector 4 Shape
        BentConnector5, ///< Bent Connector 5 Shape
        CurvedConnector2, ///< Curved Connector 2 Shape
        CurvedConnector3, ///< Curved Connector 3 Shape
        CurvedConnector4, ///< Curved Connector 4 Shape
        CurvedConnector5, ///< Curved Connector 5 Shape
        Callout1, ///< Callout 1 Shape
        Callout2, ///< Callout 2 Shape
        Callout3, ///< Callout 3 Shape
        AccentCallout1, ///< Callout 1 Shape
        AccentCallout2, ///< Callout 2 Shape
        AccentCallout3, ///< Callout 3 Shape
        BorderCallout1, ///< Callout 1 with Border Shape
        BorderCallout2, ///< Callout 2 with Border Shape
        BorderCallout3, ///< Callout 3 with Border Shape
        AccentBorderCallout1, ///< Callout 1 with Border and Accent Shape
        AccentBorderCallout2, ///< Callout 2 with Border and Accent Shape
        AccentBorderCallout3, ///< Callout 3 with Border and Accent Shape
        WedgeRectangleCallout, ///< Callout Wedge Rectangle Shape
        WedgeRoundRectangleCallout, ///< Callout Wedge Round Rectangle Shape
        WedgeEllipseCallout, ///< Callout Wedge Ellipse Shape
        CloudCallout, ///< Callout Cloud Shape
        Cloud, ///< Cloud Shape
        Ribbon, ///< Ribbon Shape
        Ribbon2, ///< Ribbon 2 Shape
        EllipseRibbon, ///< Ellipse Ribbon Shape
        EllipseRibbon2, ///< Ellipse Ribbon 2 Shape
        LeftRightRibbon, ///< Left Right Ribbon Shape
        VerticalScroll, ///< Vertical Scroll Shape
        HorizontalScroll, ///< Horizontal Scroll Shape
        Wave, ///< Wave Shape
        DoubleWave, ///< Double Wave Shape
        Plus, ///< Plus Shape
        FlowChartProcess, ///< Process Flow Shape
        FlowChartDecision, ///< Decision Flow Shape
        FlowChartInputOutput, ///< Input Output Flow Shape
        FlowChartPredefinedProcess, ///< Predefined Process Flow Shape
        FlowChartInternalStorage, ///< Internal Storage Flow Shape
        FlowChartDocument, ///< Document Flow Shape
        FlowChartMultidocument, ///< Multi-Document Flow Shape
        FlowChartTerminator, ///< Terminator Flow Shape
        FlowChartPreparation, ///< Preparation Flow Shape
        FlowChartManualInput, ///< Manual Input Flow Shape
        FlowChartManualOperation, ///< Manual Operation Flow Shape
        FlowChartConnector, ///< Connector Flow Shape
        FlowChartPunchedCard, ///< Punched Card Flow Shape
        FlowChartPunchedTape, ///< Punched Tape Flow Shape
        FlowChartSummingJunction, ///< Summing Junction Flow Shape
        FlowChartOr, ///< Or Flow Shape
        FlowChartCollate, ///< Collate Flow Shape
        FlowChartSort, ///< Sort Flow Shape
        FlowChartExtract, ///< Extract Flow Shape
        FlowChartMerge, ///< Merge Flow Shape
        FlowChartOfflineStorage, ///< Offline Storage Flow Shape
        FlowChartOnlineStorage, ///< Online Storage Flow Shape
        FlowChartMagneticTape, ///< Magnetic Tape Flow Shape
        FlowChartMagneticDisk, ///< Magnetic Disk Flow Shape
        FlowChartMagneticDrum, ///< Magnetic Drum Flow Shape
        FlowChartDisplay, ///< Display Flow Shape
        FlowChartDelay, ///< Delay Flow Shape
        FlowChartAlternateProcess, ///< Alternate Process Flow Shape
        FlowChartOffpageConnector, ///< Off-Page Connector Flow Shape
        ActionButtonBlank, ///< Blank Button Shape
        ActionButtonHome, ///< Home Button Shape
        ActionButtonHelp, ///< Help Button Shape
        ActionButtonInformation, ///< Information Button Shape
        ActionButtonForwardNext, ///< Forward or Next Button Shape
        ActionButtonBackPrevious, ///< Back or Previous Button Shape
        ActionButtonEnd, ///< End Button Shape
        ActionButtonBeginning, ///< Beginning Button Shape
        ActionButtonReturn, ///< Return Button Shape
        ActionButtonDocument, ///< Document Button Shape
        ActionButtonSound, ///< Sound Button Shape
        ActionButtonMovie, ///< Movie Button Shape
        Gear6, ///< Gear 6 Shape
        Gear9, ///< Gear 9 Shape
        Funnel, ///< Funnel Shape
        MathPlus, ///< Plus Math Shape
        MathMinus, ///< Minus Math Shape
        MathMultiply, ///< Multiply Math Shape
        MathDivide, ///< Divide Math Shape
        MathEqual, ///< Equal Math Shape
        MathNotEqual, ///< Not Equal Math Shape
        CornerTabs, ///< Corner Tabs Shape
        SquareTabs, ///< Square Tabs Shape
        PlaqueTabs, ///< Plaque Tabs Shape
        ChartX, ///< Chart X Shape
        ChartStar, ///< Chart Star Shape
        ChartPlus, ///< Chart Plus Shape
    };

    constexpr ShapeTypeValues() noexcept = default;
    constexpr ShapeTypeValues(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Preset Text Shape Types
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Drawing
/// Type QName: a:ST_TextShapeType
/// Element QName: (none)
/// Source: schemas_openxmlformats_org_drawingml_2006_main.json
class TextShapeValues : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        TextNoShape, ///< No Text Shape
        TextPlain, ///< Plain Text Shape
        TextStop, ///< Stop Sign Text Shape
        TextTriangle, ///< Triangle Text Shape
        TextTriangleInverted, ///< Inverted Triangle Text Shape
        TextChevron, ///< Chevron Text Shape
        TextChevronInverted, ///< Inverted Chevron Text Shape
        TextRingInside, ///< Inside Ring Text Shape
        TextRingOutside, ///< Outside Ring Text Shape
        TextArchUp, ///< Upward Arch Text Shape
        TextArchDown, ///< Downward Arch Text Shape
        TextCircle, ///< Circle Text Shape
        TextButton, ///< Button Text Shape
        TextArchUpPour, ///< Upward Pour Arch Text Shape
        TextArchDownPour, ///< Downward Pour Arch Text Shape
        TextCirclePour, ///< Circle Pour Text Shape
        TextButtonPour, ///< Button Pour Text Shape
        TextCurveUp, ///< Upward Curve Text Shape
        TextCurveDown, ///< Downward Curve Text Shape
        TextCanUp, ///< Upward Can Text Shape
        TextCanDown, ///< Downward Can Text Shape
        TextWave1, ///< Wave 1 Text Shape
        TextWave2, ///< Wave 2 Text Shape
        TextDoubleWave1, ///< Double Wave 1 Text Shape
        TextWave4, ///< Wave 4 Text Shape
        TextInflate, ///< Inflate Text Shape
        TextDeflate, ///< Deflate Text Shape
        TextInflateBottom, ///< Bottom Inflate Text Shape
        TextDeflateBottom, ///< Bottom Deflate Text Shape
        TextInflateTop, ///< Top Inflate Text Shape
        TextDeflateTop, ///< Top Deflate Text Shape
        TextDeflateInflate, ///< Deflate-Inflate Text Shape
        TextDeflateInflateDeflate, ///< Deflate-Inflate-Deflate Text Shape
        TextFadeRight, ///< Right Fade Text Shape
        TextFadeLeft, ///< Left Fade Text Shape
        TextFadeUp, ///< Upward Fade Text Shape
        TextFadeDown, ///< Downward Fade Text Shape
        TextSlantUp, ///< Upward Slant Text Shape
        TextSlantDown, ///< Downward Slant Text Shape
        TextCascadeUp, ///< Upward Cascade Text Shape
        TextCascadeDown, ///< Downward Cascade Text Shape
    };

    constexpr TextShapeValues() noexcept = default;
    constexpr TextShapeValues(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Path Fill Mode
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Drawing
/// Type QName: a:ST_PathFillMode
/// Element QName: (none)
/// Source: schemas_openxmlformats_org_drawingml_2006_main.json
class PathFillModeValues : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        None, ///< No Path Fill
        Norm, ///< Normal Path Fill
        Lighten, ///< Lighten Path Fill
        LightenLess, ///< Lighten Path Fill Less
        Darken, ///< Darken Path Fill
        DarkenLess, ///< Darken Path Fill Less
    };

    constexpr PathFillModeValues() noexcept = default;
    constexpr PathFillModeValues(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Line End Type
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Drawing
/// Type QName: a:ST_LineEndType
/// Element QName: (none)
/// Source: schemas_openxmlformats_org_drawingml_2006_main.json
class LineEndValues : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        None, ///< None
        Triangle, ///< Triangle Arrow Head
        Stealth, ///< Stealth Arrow
        Diamond, ///< Diamond
        Oval, ///< Oval
        Arrow, ///< Arrow Head
    };

    constexpr LineEndValues() noexcept = default;
    constexpr LineEndValues(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Line End Width
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Drawing
/// Type QName: a:ST_LineEndWidth
/// Element QName: (none)
/// Source: schemas_openxmlformats_org_drawingml_2006_main.json
class LineEndWidthValues : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        Small, ///< Small
        Medium, ///< Medium
        Large, ///< Large
    };

    constexpr LineEndWidthValues() noexcept = default;
    constexpr LineEndWidthValues(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Line End Length
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Drawing
/// Type QName: a:ST_LineEndLength
/// Element QName: (none)
/// Source: schemas_openxmlformats_org_drawingml_2006_main.json
class LineEndLengthValues : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        Small, ///< Small
        Medium, ///< Medium
        Large, ///< Large
    };

    constexpr LineEndLengthValues() noexcept = default;
    constexpr LineEndLengthValues(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Preset Line Dash Value
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Drawing
/// Type QName: a:ST_PresetLineDashVal
/// Element QName: (none)
/// Source: schemas_openxmlformats_org_drawingml_2006_main.json
class PresetLineDashValues : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        Solid, ///< Solid
        Dot, ///< Dot
        Dash, ///< Dash
        LargeDash, ///< Large Dash
        DashDot, ///< Dash Dot
        LargeDashDot, ///< Large Dash Dot
        LargeDashDotDot, ///< Large Dash Dot Dot
        SystemDash, ///< System Dash
        SystemDot, ///< System Dot
        SystemDashDot, ///< System Dash Dot
        SystemDashDotDot, ///< System Dash Dot Dot
    };

    constexpr PresetLineDashValues() noexcept = default;
    constexpr PresetLineDashValues(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief End Line Cap
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Drawing
/// Type QName: a:ST_LineCap
/// Element QName: (none)
/// Source: schemas_openxmlformats_org_drawingml_2006_main.json
class LineCapValues : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        Round, ///< Round Line Cap
        Square, ///< Square Line Cap
        Flat, ///< Flat Line Cap
    };

    constexpr LineCapValues() noexcept = default;
    constexpr LineCapValues(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Alignment Type
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Drawing
/// Type QName: a:ST_PenAlignment
/// Element QName: (none)
/// Source: schemas_openxmlformats_org_drawingml_2006_main.json
class PenAlignmentValues : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        Center, ///< Center Alignment
        Insert, ///< Inset Alignment
    };

    constexpr PenAlignmentValues() noexcept = default;
    constexpr PenAlignmentValues(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Compound Line Type
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Drawing
/// Type QName: a:ST_CompoundLine
/// Element QName: (none)
/// Source: schemas_openxmlformats_org_drawingml_2006_main.json
class CompoundLineValues : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        Single, ///< Single Line
        Double, ///< Double Lines
        ThickThin, ///< Thick Thin Double Lines
        ThinThick, ///< Thin Thick Double Lines
        Triple, ///< Thin Thick Thin Triple Lines
    };

    constexpr CompoundLineValues() noexcept = default;
    constexpr CompoundLineValues(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief On/Off Style Type
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Drawing
/// Type QName: a:ST_OnOffStyleType
/// Element QName: (none)
/// Source: schemas_openxmlformats_org_drawingml_2006_main.json
class BooleanStyleValues : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        On, ///< On
        Off, ///< Off
        Default, ///< Default
    };

    constexpr BooleanStyleValues() noexcept = default;
    constexpr BooleanStyleValues(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Text Vertical Overflow
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Drawing
/// Type QName: a:ST_TextVertOverflowType
/// Element QName: (none)
/// Source: schemas_openxmlformats_org_drawingml_2006_main.json
class TextVerticalOverflowValues : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        Overflow, ///< Text Overflow Enum ( Overflow )
        Ellipsis, ///< Text Overflow Enum ( Ellipsis )
        Clip, ///< Text Overflow Enum ( Clip )
    };

    constexpr TextVerticalOverflowValues() noexcept = default;
    constexpr TextVerticalOverflowValues(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Text Horizontal Overflow Types
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Drawing
/// Type QName: a:ST_TextHorzOverflowType
/// Element QName: (none)
/// Source: schemas_openxmlformats_org_drawingml_2006_main.json
class TextHorizontalOverflowValues : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        Overflow, ///< Text Horizontal Overflow Enum ( Overflow )
        Clip, ///< Text Horizontal Overflow Enum ( Clip )
    };

    constexpr TextHorizontalOverflowValues() noexcept = default;
    constexpr TextHorizontalOverflowValues(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Vertical Text Types
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Drawing
/// Type QName: a:ST_TextVerticalType
/// Element QName: (none)
/// Source: schemas_openxmlformats_org_drawingml_2006_main.json
class TextVerticalValues : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        Horizontal, ///< Vertical Text Type Enum ( Horizontal )
        Vertical, ///< Vertical Text Type Enum ( Vertical )
        Vertical270, ///< Vertical Text Type Enum ( Vertical 270 )
        WordArtVertical, ///< Vertical Text Type Enum ( WordArt Vertical )
        EastAsianVetical, ///< Vertical Text Type Enum ( East Asian Vertical )
        MongolianVertical, ///< Vertical Text Type Enum ( Mongolian Vertical )
        WordArtLeftToRight, ///< Vertical WordArt Right to Left
    };

    constexpr TextVerticalValues() noexcept = default;
    constexpr TextVerticalValues(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Text Wrapping Types
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Drawing
/// Type QName: a:ST_TextWrappingType
/// Element QName: (none)
/// Source: schemas_openxmlformats_org_drawingml_2006_main.json
class TextWrappingValues : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        None, ///< Text Wrapping Type Enum ( None )
        Square, ///< Text Wrapping Type Enum ( Square )
    };

    constexpr TextWrappingValues() noexcept = default;
    constexpr TextWrappingValues(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Text Anchoring Types
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Drawing
/// Type QName: a:ST_TextAnchoringType
/// Element QName: (none)
/// Source: schemas_openxmlformats_org_drawingml_2006_main.json
class TextAnchoringTypeValues : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        Top, ///< Text Anchoring Type Enum ( Top )
        Center, ///< Text Anchor Enum ( Center )
        Bottom, ///< Text Anchor Enum ( Bottom )
    };

    constexpr TextAnchoringTypeValues() noexcept = default;
    constexpr TextAnchoringTypeValues(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Text Auto-number Schemes
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Drawing
/// Type QName: a:ST_TextAutonumberScheme
/// Element QName: (none)
/// Source: schemas_openxmlformats_org_drawingml_2006_main.json
class TextAutoNumberSchemeValues : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        AlphaLowerCharacterParenBoth, ///< Autonumber Enum ( alphaLcParenBoth )
        AlphaUpperCharacterParenBoth, ///< Autonumbering Enum ( alphaUcParenBoth )
        AlphaLowerCharacterParenR, ///< Autonumbering Enum ( alphaLcParenR )
        AlphaUpperCharacterParenR, ///< Autonumbering Enum ( alphaUcParenR )
        AlphaLowerCharacterPeriod, ///< Autonumbering Enum ( alphaLcPeriod )
        AlphaUpperCharacterPeriod, ///< Autonumbering Enum ( alphaUcPeriod )
        ArabicParenBoth, ///< Autonumbering Enum ( arabicParenBoth )
        ArabicParenR, ///< Autonumbering Enum ( arabicParenR )
        ArabicPeriod, ///< Autonumbering Enum ( arabicPeriod )
        ArabicPlain, ///< Autonumbering Enum ( arabicPlain )
        RomanLowerCharacterParenBoth, ///< Autonumbering Enum ( romanLcParenBoth )
        RomanUpperCharacterParenBoth, ///< Autonumbering Enum ( romanUcParenBoth )
        RomanLowerCharacterParenR, ///< Autonumbering Enum ( romanLcParenR )
        RomanUpperCharacterParenR, ///< Autonumbering Enum ( romanUcParenR )
        RomanLowerCharacterPeriod, ///< Autonumbering Enum ( romanLcPeriod )
        RomanUpperCharacterPeriod, ///< Autonumbering Enum ( romanUcPeriod )
        CircleNumberDoubleBytePlain, ///< Autonumbering Enum ( circleNumDbPlain )
        CircleNumberWingdingsBlackPlain, ///< Autonumbering Enum ( circleNumWdBlackPlain )
        CircleNumberWingdingsWhitePlain, ///< Autonumbering Enum ( circleNumWdWhitePlain )
        ArabicDoubleBytePeriod, ///< Autonumbering Enum ( arabicDbPeriod )
        ArabicDoubleBytePlain, ///< Autonumbering Enum ( arabicDbPlain )
        EastAsianSimplifiedChinesePeriod, ///< Autonumbering Enum ( ea1ChsPeriod )
        EastAsianSimplifiedChinesePlain, ///< Autonumbering Enum ( ea1ChsPlain )
        EastAsianTraditionalChinesePeriod, ///< Autonumbering Enum ( ea1ChtPeriod )
        EastAsianTraditionalChinesePlain, ///< Autonumbering Enum ( ea1ChtPlain )
        EastAsianJapaneseDoubleBytePeriod, ///< Autonumbering Enum ( ea1JpnChsDbPeriod )
        EastAsianJapaneseKoreanPlain, ///< Autonumbering Enum ( ea1JpnKorPlain )
        EastAsianJapaneseKoreanPeriod, ///< Autonumbering Enum ( ea1JpnKorPeriod )
        Arabic1Minus, ///< Autonumbering Enum ( arabic1Minus )
        Arabic2Minus, ///< Autonumbering Enum ( arabic2Minus )
        Hebrew2Minus, ///< Autonumbering Enum ( hebrew2Minus )
        ThaiAlphaPeriod, ///< Autonumbering Enum ( thaiAlphaPeriod )
        ThaiAlphaParenthesisRight, ///< Autonumbering Enum ( thaiAlphaParenR )
        ThaiAlphaParenthesisBoth, ///< Autonumbering Enum ( thaiAlphaParenBoth )
        ThaiNumberPeriod, ///< Autonumbering Enum ( thaiNumPeriod )
        ThaiNumberParenthesisRight, ///< Autonumbering Enum ( thaiNumParenR )
        ThaiNumberParenthesisBoth, ///< Autonumbering Enum ( thaiNumParenBoth )
        HindiAlphaPeriod, ///< Autonumbering Enum ( hindiAlphaPeriod )
        HindiNumPeriod, ///< Autonumbering Enum ( hindiNumPeriod )
        HindiNumberParenthesisRight, ///< Autonumbering Enum ( hindiNumParenR )
        HindiAlpha1Period, ///< Autonumbering Enum ( hindiAlpha1Period )
    };

    constexpr TextAutoNumberSchemeValues() noexcept = default;
    constexpr TextAutoNumberSchemeValues(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Text Underline Types
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Drawing
/// Type QName: a:ST_TextUnderlineType
/// Element QName: (none)
/// Source: schemas_openxmlformats_org_drawingml_2006_main.json
class TextUnderlineValues : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        None, ///< Text Underline Enum ( None )
        Words, ///< Text Underline Enum ( Words )
        Single, ///< Text Underline Enum ( Single )
        Double, ///< Text Underline Enum ( Double )
        Heavy, ///< Text Underline Enum ( Heavy )
        Dotted, ///< Text Underline Enum ( Dotted )
        HeavyDotted, ///< Text Underline Enum ( Heavy Dotted  )
        Dash, ///< Text Underline Enum ( Dashed )
        DashHeavy, ///< Text Underline Enum ( Heavy Dashed )
        DashLong, ///< Text Underline Enum ( Long Dashed )
        DashLongHeavy, ///< Text Underline Enum ( Heavy Long Dashed )
        DotDash, ///< Text Underline Enum ( Dot Dash )
        DotDashHeavy, ///< Text Underline Enum ( Heavy Dot Dash )
        DotDotDash, ///< Text Underline Enum ( Dot Dot Dash )
        DotDotDashHeavy, ///< Text Underline Enum ( Heavy Dot Dot Dash )
        Wavy, ///< Text Underline Enum ( Wavy )
        WavyHeavy, ///< Text Underline Enum ( Heavy Wavy )
        WavyDouble, ///< Text Underline Enum ( Double Wavy )
    };

    constexpr TextUnderlineValues() noexcept = default;
    constexpr TextUnderlineValues(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Text Strike Type
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Drawing
/// Type QName: a:ST_TextStrikeType
/// Element QName: (none)
/// Source: schemas_openxmlformats_org_drawingml_2006_main.json
class TextStrikeValues : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        NoStrike, ///< Text Strike Enum ( No Strike )
        SingleStrike, ///< Text Strike Enum ( Single Strike )
        DoubleStrike, ///< Text Strike Enum ( Double Strike )
    };

    constexpr TextStrikeValues() noexcept = default;
    constexpr TextStrikeValues(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Text Cap Types
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Drawing
/// Type QName: a:ST_TextCapsType
/// Element QName: (none)
/// Source: schemas_openxmlformats_org_drawingml_2006_main.json
class TextCapsValues : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        None, ///< Text Caps Enum ( None )
        Small, ///< Text Caps Enum ( Small )
        All, ///< Text Caps Enum ( All )
    };

    constexpr TextCapsValues() noexcept = default;
    constexpr TextCapsValues(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Text Tab Alignment Types
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Drawing
/// Type QName: a:ST_TextTabAlignType
/// Element QName: (none)
/// Source: schemas_openxmlformats_org_drawingml_2006_main.json
class TextTabAlignmentValues : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        Left, ///< Text Tab Alignment Enum ( Left)
        Center, ///< Text Tab Alignment Enum ( Center )
        Right, ///< Text Tab Alignment Enum ( Right )
        Decimal, ///< Text Tab Alignment Enum ( Decimal )
    };

    constexpr TextTabAlignmentValues() noexcept = default;
    constexpr TextTabAlignmentValues(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Text Alignment Types
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Drawing
/// Type QName: a:ST_TextAlignType
/// Element QName: (none)
/// Source: schemas_openxmlformats_org_drawingml_2006_main.json
class TextAlignmentTypeValues : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        Left, ///< Text Alignment Enum ( Left )
        Center, ///< Text Alignment Enum ( Center )
        Right, ///< Text Alignment Enum ( Right )
        Justified, ///< Text Alignment Enum ( Justified )
        JustifiedLow, ///< Text Alignment Enum ( Justified Low )
        Distributed, ///< Text Alignment Enum ( Distributed )
        ThaiDistributed, ///< Text Alignment Enum ( Thai Distributed )
    };

    constexpr TextAlignmentTypeValues() noexcept = default;
    constexpr TextAlignmentTypeValues(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Font Alignment Types
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Drawing
/// Type QName: a:ST_TextFontAlignType
/// Element QName: (none)
/// Source: schemas_openxmlformats_org_drawingml_2006_main.json
class TextFontAlignmentValues : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        Automatic, ///< Font Alignment Enum ( Automatic )
        Top, ///< Font Alignment Enum ( Top )
        Center, ///< Font Alignment Enum ( Center )
        Baseline, ///< Font Alignment Enum ( Baseline )
        Bottom, ///< Font Alignment Enum ( Bottom )
    };

    constexpr TextFontAlignmentValues() noexcept = default;
    constexpr TextFontAlignmentValues(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Preset Color Value
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Drawing
/// Type QName: a:ST_PresetColorVal
/// Element QName: (none)
/// Source: schemas_openxmlformats_org_drawingml_2006_main.json
class PresetColorValues : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        AliceBlue, ///< Alice Blue Preset Color
        AntiqueWhite, ///< Antique White Preset Color
        Aqua, ///< Aqua Preset Color
        Aquamarine, ///< Aquamarine Preset Color
        Azure, ///< Azure Preset Color
        Beige, ///< Beige Preset Color
        Bisque, ///< Bisque Preset Color
        Black, ///< Black Preset Color
        BlanchedAlmond, ///< Blanched Almond Preset Color
        Blue, ///< Blue Preset Color
        BlueViolet, ///< Blue Violet Preset Color
        Brown, ///< Brown Preset Color
        BurlyWood, ///< Burly Wood Preset Color
        CadetBlue, ///< Cadet Blue Preset Color
        Chartreuse, ///< Chartreuse Preset Color
        Chocolate, ///< Chocolate Preset Color
        Coral, ///< Coral Preset Color
        CornflowerBlue, ///< Cornflower Blue Preset Color
        Cornsilk, ///< Cornsilk Preset Color
        Crimson, ///< Crimson Preset Color
        Cyan, ///< Cyan Preset Color
        DarkBlue, ///< Dark Blue Preset Color
        DarkCyan, ///< Dark Cyan Preset Color
        DarkGoldenrod, ///< Dark Goldenrod Preset Color
        DarkGray, ///< Dark Gray Preset Color
        DarkGreen, ///< Dark Green Preset Color
        DarkKhaki, ///< Dark Khaki Preset Color
        DarkMagenta, ///< Dark Magenta Preset Color
        DarkOliveGreen, ///< Dark Olive Green Preset Color
        DarkOrange, ///< Dark Orange Preset Color
        DarkOrchid, ///< Dark Orchid Preset Color
        DarkRed, ///< Dark Red Preset Color
        DarkSalmon, ///< Dark Salmon Preset Color
        DarkSeaGreen, ///< Dark Sea Green Preset Color
        DarkSlateBlue, ///< Dark Slate Blue Preset Color
        DarkSlateGray, ///< Dark Slate Gray Preset Color
        DarkTurquoise, ///< Dark Turquoise Preset Color
        DarkViolet, ///< Dark Violet Preset Color
        DeepPink, ///< Deep Pink Preset Color
        DeepSkyBlue, ///< Deep Sky Blue Preset Color
        DimGray, ///< Dim Gray Preset Color
        DodgerBlue, ///< Dodger Blue Preset Color
        Firebrick, ///< Firebrick Preset Color
        FloralWhite, ///< Floral White Preset Color
        ForestGreen, ///< Forest Green Preset Color
        Fuchsia, ///< Fuchsia Preset Color
        Gainsboro, ///< Gainsboro Preset Color
        GhostWhite, ///< Ghost White Preset Color
        Gold, ///< Gold Preset Color
        Goldenrod, ///< Goldenrod Preset Color
        Gray, ///< Gray Preset Color
        Green, ///< Green Preset Color
        GreenYellow, ///< Green Yellow Preset Color
        Honeydew, ///< Honeydew Preset Color
        HotPink, ///< Hot Pink Preset Color
        IndianRed, ///< Indian Red Preset Color
        Indigo, ///< Indigo Preset Color
        Ivory, ///< Ivory Preset Color
        Khaki, ///< Khaki Preset Color
        Lavender, ///< Lavender Preset Color
        LavenderBlush, ///< Lavender Blush Preset Color
        LawnGreen, ///< Lawn Green Preset Color
        LemonChiffon, ///< Lemon Chiffon Preset Color
        LightBlue, ///< Light Blue Preset Color
        LightCoral, ///< Light Coral Preset Color
        LightCyan, ///< Light Cyan Preset Color
        LightGoldenrodYellow, ///< Light Goldenrod Yellow Preset Color
        LightGray, ///< Light Gray Preset Color
        LightGreen, ///< Light Green Preset Color
        LightPink, ///< Light Pink Preset Color
        LightSalmon, ///< Light Salmon Preset Color
        LightSeaGreen, ///< Light Sea Green Preset Color
        LightSkyBlue, ///< Light Sky Blue Preset Color
        LightSlateGray, ///< Light Slate Gray Preset Color
        LightSteelBlue, ///< Light Steel Blue Preset Color
        LightYellow, ///< Light Yellow Preset Color
        Lime, ///< Lime Preset Color
        LimeGreen, ///< Lime Green Preset Color
        Linen, ///< Linen Preset Color
        Magenta, ///< Magenta Preset Color
        Maroon, ///< Maroon Preset Color
        MedAquamarine, ///< Medium Aquamarine Preset Color
        MediumBlue, ///< Medium Blue Preset Color
        MediumOrchid, ///< Medium Orchid Preset Color
        MediumPurple, ///< Medium Purple Preset Color
        MediumSeaGreen, ///< Medium Sea Green Preset Color
        MediumSlateBlue, ///< Medium Slate Blue Preset Color
        MediumSpringGreen, ///< Medium Spring Green Preset Color
        MediumTurquoise, ///< Medium Turquoise Preset Color
        MediumVioletRed, ///< Medium Violet Red Preset Color
        MidnightBlue, ///< Midnight Blue Preset Color
        MintCream, ///< Mint Cream Preset Color
        MistyRose, ///< Misty Rose Preset Color
        Moccasin, ///< Moccasin Preset Color
        NavajoWhite, ///< Navajo White Preset Color
        Navy, ///< Navy Preset Color
        OldLace, ///< Old Lace Preset Color
        Olive, ///< Olive Preset Color
        OliveDrab, ///< Olive Drab Preset Color
        Orange, ///< Orange Preset Color
        OrangeRed, ///< Orange Red Preset Color
        Orchid, ///< Orchid Preset Color
        PaleGoldenrod, ///< Pale Goldenrod Preset Color
        PaleGreen, ///< Pale Green Preset Color
        PaleTurquoise, ///< Pale Turquoise Preset Color
        PaleVioletRed, ///< Pale Violet Red Preset Color
        PapayaWhip, ///< Papaya Whip Preset Color
        PeachPuff, ///< Peach Puff Preset Color
        Peru, ///< Peru Preset Color
        Pink, ///< Pink Preset Color
        Plum, ///< Plum Preset Color
        PowderBlue, ///< Powder Blue Preset Color
        Purple, ///< Purple Preset Color
        Red, ///< Red Preset Color
        RosyBrown, ///< Rosy Brown Preset Color
        RoyalBlue, ///< Royal Blue Preset Color
        SaddleBrown, ///< Saddle Brown Preset Color
        Salmon, ///< Salmon Preset Color
        SandyBrown, ///< Sandy Brown Preset Color
        SeaGreen, ///< Sea Green Preset Color
        SeaShell, ///< Sea Shell Preset Color
        Sienna, ///< Sienna Preset Color
        Silver, ///< Silver Preset Color
        SkyBlue, ///< Sky Blue Preset Color
        SlateBlue, ///< Slate Blue Preset Color
        SlateGray, ///< Slate Gray Preset Color
        Snow, ///< Snow Preset Color
        SpringGreen, ///< Spring Green Preset Color
        SteelBlue, ///< Steel Blue Preset Color
        Tan, ///< Tan Preset Color
        Teal, ///< Teal Preset Color
        Thistle, ///< Thistle Preset Color
        Tomato, ///< Tomato Preset Color
        Turquoise, ///< Turquoise Preset Color
        Violet, ///< Violet Preset Color
        Wheat, ///< Wheat Preset Color
        White, ///< White Preset Color
        WhiteSmoke, ///< White Smoke Preset Color
        Yellow, ///< Yellow Preset Color
        YellowGreen, ///< Yellow Green Preset Color
        DarkBlue2010, 
        DarkCyan2010, 
        DarkGoldenrod2010, 
        DarkGray2010, 
        DarkGrey2010, 
        DarkGreen2010, 
        DarkKhaki2010, 
        DarkMagenta2010, 
        DarkOliveGreen2010, 
        DarkOrange2010, 
        DarkOrchid2010, 
        DarkRed2010, 
        DarkSalmon2010, 
        DarkSeaGreen2010, 
        DarkSlateBlue2010, 
        DarkSlateGray2010, 
        DarkSlateGrey2010, 
        DarkTurquoise2010, 
        DarkViolet2010, 
        LightBlue2010, 
        LightCoral2010, 
        LightCyan2010, 
        LightGoldenrodYellow2010, 
        LightGray2010, 
        LightGrey2010, 
        LightGreen2010, 
        LightPink2010, 
        LightSalmon2010, 
        LightSeaGreen2010, 
        LightSkyBlue2010, 
        LightSlateGray2010, 
        LightSlateGrey2010, 
        LightSteelBlue2010, 
        LightYellow2010, 
        MediumAquamarine2010, 
        MediumBlue2010, 
        MediumOrchid2010, 
        MediumPurple2010, 
        MediumSeaGreen2010, 
        MediumSlateBlue2010, 
        MediumSpringGreen2010, 
        MediumTurquoise2010, 
        MediumVioletRed2010, 
        DarkGrey, 
        DimGrey, 
        DarkSlateGrey, 
        Grey, 
        LightGrey, 
        LightSlateGrey, 
        SlateGrey, 
    };

    constexpr PresetColorValues() noexcept = default;
    constexpr PresetColorValues(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

} // namespace Drawing
} // namespace OpenXml
} // namespace DocumentFormat
} // namespace ExyokiOffice
