// Copyright (c) 2026 Jakub Melka and Contributors
// SPDX-License-Identifier: MIT
// See LICENSE file in the project root for full license text.
//
// Derived from the Open-XML-SDK metadata under data/, which is
// Copyright (c) .NET Foundation and Contributors and MIT-licensed.
// See data/LICENSE and THIRD-PARTY-LICENSES.md in the project root.
// -----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by ExyokiOffice OpenXML generator.
//     Manual changes to this file may cause unexpected behaviour.
// </auto-generated>
// -----------------------------------------------------------------------------

#pragma once

#include "ExyokiOffice/OpenXMLElement.hpp"
#include "ExyokiOffice/DOM/DocumentFormat/OpenXml/EMMA.Enums.hpp"

#include <memory>
#include <span>
#include <string_view>

namespace ExyokiOffice {
namespace DocumentFormat {
namespace OpenXml {
namespace EMMA {


using OpenXMLElement = ExyokiOffice::OpenXMLElement;
using OpenXmlCompositeElement = ExyokiOffice::OpenXmlCompositeElement;
using OpenXmlPartRootElement = ExyokiOffice::OpenXmlPartRootElement;
using OpenXmlLeafElement = ExyokiOffice::OpenXmlLeafElement;
using OpenXmlLeafTextElement = ExyokiOffice::OpenXmlLeafTextElement;

/// \brief Defines the Emma Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.EMMA
/// Type QName: emma:CT_Emma
/// Element QName: emma:emma
/// Source: www_w3_org_2003_04_emma.json
class EXYOKIOFFICE_EXPORT Emma : public OpenXmlCompositeElement
{
public:
    using Ptr = std::shared_ptr<Emma>;

    inline Emma() = default;
    inline ~Emma() = default;

    /// version
    StringValue GetVersion() const;
    void SetVersion(const StringValue& value);

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the Arc Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.EMMA
/// Type QName: emma:CT_Arc
/// Element QName: emma:arc
/// Source: www_w3_org_2003_04_emma.json
class EXYOKIOFFICE_EXPORT Arc : public OpenXmlCompositeElement
{
public:
    using Ptr = std::shared_ptr<Arc>;

    inline Arc() = default;
    inline ~Arc() = default;

    /// from
    IntegerValue GetFrom() const;
    void SetFrom(const IntegerValue& value);

    /// to
    IntegerValue GetTo() const;
    void SetTo(const IntegerValue& value);

    /// start
    UInt64Value GetStart() const;
    void SetStart(const UInt64Value& value);

    /// end
    UInt64Value GetEnd() const;
    void SetEnd(const UInt64Value& value);

    /// offset-to-start
    IntegerValue GetOffsetToStart() const;
    void SetOffsetToStart(const IntegerValue& value);

    /// duration
    IntegerValue GetDuration() const;
    void SetDuration(const IntegerValue& value);

    /// confidence
    DecimalValue GetConfidence() const;
    void SetConfidence(const DecimalValue& value);

    /// cost
    DecimalValue GetCost() const;
    void SetCost(const DecimalValue& value);

    /// lang
    StringValue GetLanguage() const;
    void SetLanguage(const StringValue& value);

    /// medium
    ListValue<EnumValue<MediumValues>> GetMedium() const;
    void SetMedium(const ListValue<EnumValue<MediumValues>>& value);

    /// mode
    ListValue<StringValue> GetMode() const;
    void SetMode(const ListValue<StringValue>& value);

    /// source
    StringValue GetSource() const;
    void SetSource(const StringValue& value);

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the Node Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.EMMA
/// Type QName: emma:CT_Node
/// Element QName: emma:node
/// Source: www_w3_org_2003_04_emma.json
class EXYOKIOFFICE_EXPORT Node : public OpenXmlCompositeElement
{
public:
    using Ptr = std::shared_ptr<Node>;

    inline Node() = default;
    inline ~Node() = default;

    /// node-number
    IntegerValue GetNodeNumber() const;
    void SetNodeNumber(const IntegerValue& value);

    /// confidence
    DecimalValue GetConfidence() const;
    void SetConfidence(const DecimalValue& value);

    /// cost
    DecimalValue GetCost() const;
    void SetCost(const DecimalValue& value);

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the EndPoint Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.EMMA
/// Type QName: emma:CT_EndPoint
/// Element QName: emma:endpoint
/// Source: www_w3_org_2003_04_emma.json
class EXYOKIOFFICE_EXPORT EndPoint : public OpenXmlCompositeElement
{
public:
    using Ptr = std::shared_ptr<EndPoint>;

    inline EndPoint() = default;
    inline ~EndPoint() = default;

    /// id
    StringValue GetId() const;
    void SetId(const StringValue& value);

    /// endpoint-role
    EnumValue<EndPointRoleValues> GetEndpointRole() const;
    void SetEndpointRole(const EnumValue<EndPointRoleValues>& value);

    /// endpoint-address
    StringValue GetEndPointAddress() const;
    void SetEndPointAddress(const StringValue& value);

    /// message-id
    StringValue GetMessageId() const;
    void SetMessageId(const StringValue& value);

    /// port-num
    IntegerValue GetPortNumber() const;
    void SetPortNumber(const IntegerValue& value);

    /// port-type
    StringValue GetPortType() const;
    void SetPortType(const StringValue& value);

    /// endpoint-pair-ref
    StringValue GetEndpointPairRef() const;
    void SetEndpointPairRef(const StringValue& value);

    /// service-name
    StringValue GetServiceName() const;
    void SetServiceName(const StringValue& value);

    /// media-type
    StringValue GetMediaType() const;
    void SetMediaType(const StringValue& value);

    /// medium
    ListValue<EnumValue<MediumValues>> GetMedium() const;
    void SetMedium(const ListValue<EnumValue<MediumValues>>& value);

    /// mode
    ListValue<StringValue> GetMode() const;
    void SetMode(const ListValue<StringValue>& value);

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the EndPointInfo Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.EMMA
/// Type QName: emma:CT_EndPointInfo
/// Element QName: emma:endpoint-info
/// Source: www_w3_org_2003_04_emma.json
class EXYOKIOFFICE_EXPORT EndPointInfo : public OpenXmlCompositeElement
{
public:
    using Ptr = std::shared_ptr<EndPointInfo>;

    inline EndPointInfo() = default;
    inline ~EndPointInfo() = default;

    /// id
    StringValue GetId() const;
    void SetId(const StringValue& value);

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the Model Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.EMMA
/// Type QName: emma:CT_Model
/// Element QName: emma:model
/// Source: www_w3_org_2003_04_emma.json
class EXYOKIOFFICE_EXPORT Model : public OpenXmlCompositeElement
{
public:
    using Ptr = std::shared_ptr<Model>;

    inline Model() = default;
    inline ~Model() = default;

    /// id
    StringValue GetId() const;
    void SetId(const StringValue& value);

    /// ref
    StringValue GetReference() const;
    void SetReference(const StringValue& value);

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the Grammar Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.EMMA
/// Type QName: emma:CT_Grammar
/// Element QName: emma:grammar
/// Source: www_w3_org_2003_04_emma.json
class EXYOKIOFFICE_EXPORT Grammar : public OpenXmlLeafElement
{
public:
    using Ptr = std::shared_ptr<Grammar>;

    inline Grammar() = default;
    inline ~Grammar() = default;

    /// id
    StringValue GetId() const;
    void SetId(const StringValue& value);

    /// ref
    StringValue GetReference() const;
    void SetReference(const StringValue& value);

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the Derivation Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.EMMA
/// Type QName: emma:CT_Derivation
/// Element QName: emma:derivation
/// Source: www_w3_org_2003_04_emma.json
class EXYOKIOFFICE_EXPORT Derivation : public OpenXmlCompositeElement
{
public:
    using Ptr = std::shared_ptr<Derivation>;

    inline Derivation() = default;
    inline ~Derivation() = default;

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the GroupInfo Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.EMMA
/// Type QName: emma:CT_GroupInfo
/// Element QName: emma:group-info
/// Source: www_w3_org_2003_04_emma.json
class EXYOKIOFFICE_EXPORT GroupInfo : public OpenXmlCompositeElement
{
public:
    using Ptr = std::shared_ptr<GroupInfo>;

    inline GroupInfo() = default;
    inline ~GroupInfo() = default;

    /// ref
    StringValue GetReference() const;
    void SetReference(const StringValue& value);

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the Sequence Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.EMMA
/// Type QName: emma:CT_Sequence
/// Element QName: emma:sequence
/// Source: www_w3_org_2003_04_emma.json
class EXYOKIOFFICE_EXPORT Sequence : public OpenXmlCompositeElement
{
public:
    using Ptr = std::shared_ptr<Sequence>;

    inline Sequence() = default;
    inline ~Sequence() = default;

    /// id
    StringValue GetId() const;
    void SetId(const StringValue& value);

    /// tokens
    StringValue GetTokens() const;
    void SetTokens(const StringValue& value);

    /// process
    StringValue GetProcess() const;
    void SetProcess(const StringValue& value);

    /// lang
    StringValue GetLanguage() const;
    void SetLanguage(const StringValue& value);

    /// signal
    StringValue GetSignal() const;
    void SetSignal(const StringValue& value);

    /// signal-size
    IntegerValue GetSignalSize() const;
    void SetSignalSize(const IntegerValue& value);

    /// media-type
    StringValue GetMediaType() const;
    void SetMediaType(const StringValue& value);

    /// confidence
    DecimalValue GetConfidence() const;
    void SetConfidence(const DecimalValue& value);

    /// source
    StringValue GetSource() const;
    void SetSource(const StringValue& value);

    /// start
    UInt64Value GetStart() const;
    void SetStart(const UInt64Value& value);

    /// end
    UInt64Value GetEnd() const;
    void SetEnd(const UInt64Value& value);

    /// time-ref-uri
    StringValue GetTimeReference() const;
    void SetTimeReference(const StringValue& value);

    /// time-ref-anchor-point
    EnumValue<AnchorPointValues> GetTimeReferenceAnchorPoint() const;
    void SetTimeReferenceAnchorPoint(const EnumValue<AnchorPointValues>& value);

    /// offset-to-start
    IntegerValue GetOffsetToStart() const;
    void SetOffsetToStart(const IntegerValue& value);

    /// duration
    IntegerValue GetDuration() const;
    void SetDuration(const IntegerValue& value);

    /// medium
    ListValue<EnumValue<MediumValues>> GetMedium() const;
    void SetMedium(const ListValue<EnumValue<MediumValues>>& value);

    /// mode
    ListValue<StringValue> GetMode() const;
    void SetMode(const ListValue<StringValue>& value);

    /// function
    StringValue GetFunction() const;
    void SetFunction(const StringValue& value);

    /// verbal
    BooleanValue GetVerbal() const;
    void SetVerbal(const BooleanValue& value);

    /// cost
    DecimalValue GetCost() const;
    void SetCost(const DecimalValue& value);

    /// grammar-ref
    StringValue GetGrammarRef() const;
    void SetGrammarRef(const StringValue& value);

    /// endpoint-info-ref
    StringValue GetEndpointInfoRef() const;
    void SetEndpointInfoRef(const StringValue& value);

    /// model-ref
    StringValue GetModelRef() const;
    void SetModelRef(const StringValue& value);

    /// dialog-turn
    StringValue GetDialogTurn() const;
    void SetDialogTurn(const StringValue& value);

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the Group Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.EMMA
/// Type QName: emma:CT_Group
/// Element QName: emma:group
/// Source: www_w3_org_2003_04_emma.json
class EXYOKIOFFICE_EXPORT Group : public OpenXmlCompositeElement
{
public:
    using Ptr = std::shared_ptr<Group>;

    inline Group() = default;
    inline ~Group() = default;

    /// id
    StringValue GetId() const;
    void SetId(const StringValue& value);

    /// tokens
    StringValue GetTokens() const;
    void SetTokens(const StringValue& value);

    /// process
    StringValue GetProcess() const;
    void SetProcess(const StringValue& value);

    /// lang
    StringValue GetLanguage() const;
    void SetLanguage(const StringValue& value);

    /// signal
    StringValue GetSignal() const;
    void SetSignal(const StringValue& value);

    /// signal-size
    IntegerValue GetSignalSize() const;
    void SetSignalSize(const IntegerValue& value);

    /// media-type
    StringValue GetMediaType() const;
    void SetMediaType(const StringValue& value);

    /// confidence
    DecimalValue GetConfidence() const;
    void SetConfidence(const DecimalValue& value);

    /// source
    StringValue GetSource() const;
    void SetSource(const StringValue& value);

    /// start
    UInt64Value GetStart() const;
    void SetStart(const UInt64Value& value);

    /// end
    UInt64Value GetEnd() const;
    void SetEnd(const UInt64Value& value);

    /// time-ref-uri
    StringValue GetTimeReference() const;
    void SetTimeReference(const StringValue& value);

    /// time-ref-anchor-point
    EnumValue<AnchorPointValues> GetTimeReferenceAnchorPoint() const;
    void SetTimeReferenceAnchorPoint(const EnumValue<AnchorPointValues>& value);

    /// offset-to-start
    IntegerValue GetOffsetToStart() const;
    void SetOffsetToStart(const IntegerValue& value);

    /// duration
    IntegerValue GetDuration() const;
    void SetDuration(const IntegerValue& value);

    /// medium
    ListValue<EnumValue<MediumValues>> GetMedium() const;
    void SetMedium(const ListValue<EnumValue<MediumValues>>& value);

    /// mode
    ListValue<StringValue> GetMode() const;
    void SetMode(const ListValue<StringValue>& value);

    /// function
    StringValue GetFunction() const;
    void SetFunction(const StringValue& value);

    /// verbal
    BooleanValue GetVerbal() const;
    void SetVerbal(const BooleanValue& value);

    /// cost
    DecimalValue GetCost() const;
    void SetCost(const DecimalValue& value);

    /// grammar-ref
    StringValue GetGrammarRef() const;
    void SetGrammarRef(const StringValue& value);

    /// endpoint-info-ref
    StringValue GetEndpointInfoRef() const;
    void SetEndpointInfoRef(const StringValue& value);

    /// model-ref
    StringValue GetModelRef() const;
    void SetModelRef(const StringValue& value);

    /// dialog-turn
    StringValue GetDialogTurn() const;
    void SetDialogTurn(const StringValue& value);

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the OneOf Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.EMMA
/// Type QName: emma:CT_OneOf
/// Element QName: emma:one-of
/// Source: www_w3_org_2003_04_emma.json
class EXYOKIOFFICE_EXPORT OneOf : public OpenXmlCompositeElement
{
public:
    using Ptr = std::shared_ptr<OneOf>;

    inline OneOf() = default;
    inline ~OneOf() = default;

    /// disjunction-type
    EnumValue<DisjunctionTypeValues> GetDisjunctionType() const;
    void SetDisjunctionType(const EnumValue<DisjunctionTypeValues>& value);

    /// id
    StringValue GetId() const;
    void SetId(const StringValue& value);

    /// tokens
    StringValue GetTokens() const;
    void SetTokens(const StringValue& value);

    /// process
    StringValue GetProcess() const;
    void SetProcess(const StringValue& value);

    /// lang
    StringValue GetLanguage() const;
    void SetLanguage(const StringValue& value);

    /// signal
    StringValue GetSignal() const;
    void SetSignal(const StringValue& value);

    /// signal-size
    IntegerValue GetSignalSize() const;
    void SetSignalSize(const IntegerValue& value);

    /// media-type
    StringValue GetMediaType() const;
    void SetMediaType(const StringValue& value);

    /// confidence
    DecimalValue GetConfidence() const;
    void SetConfidence(const DecimalValue& value);

    /// source
    StringValue GetSource() const;
    void SetSource(const StringValue& value);

    /// start
    UInt64Value GetStart() const;
    void SetStart(const UInt64Value& value);

    /// end
    UInt64Value GetEnd() const;
    void SetEnd(const UInt64Value& value);

    /// time-ref-uri
    StringValue GetTimeReference() const;
    void SetTimeReference(const StringValue& value);

    /// time-ref-anchor-point
    EnumValue<AnchorPointValues> GetTimeReferenceAnchorPoint() const;
    void SetTimeReferenceAnchorPoint(const EnumValue<AnchorPointValues>& value);

    /// offset-to-start
    IntegerValue GetOffsetToStart() const;
    void SetOffsetToStart(const IntegerValue& value);

    /// duration
    IntegerValue GetDuration() const;
    void SetDuration(const IntegerValue& value);

    /// medium
    ListValue<EnumValue<MediumValues>> GetMedium() const;
    void SetMedium(const ListValue<EnumValue<MediumValues>>& value);

    /// mode
    ListValue<StringValue> GetMode() const;
    void SetMode(const ListValue<StringValue>& value);

    /// function
    StringValue GetFunction() const;
    void SetFunction(const StringValue& value);

    /// verbal
    BooleanValue GetVerbal() const;
    void SetVerbal(const BooleanValue& value);

    /// cost
    DecimalValue GetCost() const;
    void SetCost(const DecimalValue& value);

    /// grammar-ref
    StringValue GetGrammarRef() const;
    void SetGrammarRef(const StringValue& value);

    /// endpoint-info-ref
    StringValue GetEndpointInfoRef() const;
    void SetEndpointInfoRef(const StringValue& value);

    /// model-ref
    StringValue GetModelRef() const;
    void SetModelRef(const StringValue& value);

    /// dialog-turn
    StringValue GetDialogTurn() const;
    void SetDialogTurn(const StringValue& value);

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the Interpretation Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.EMMA
/// Type QName: emma:CT_Interpretation
/// Element QName: emma:interpretation
/// Source: www_w3_org_2003_04_emma.json
class EXYOKIOFFICE_EXPORT Interpretation : public OpenXmlCompositeElement
{
public:
    using Ptr = std::shared_ptr<Interpretation>;

    inline Interpretation() = default;
    inline ~Interpretation() = default;

    /// id
    StringValue GetId() const;
    void SetId(const StringValue& value);

    /// tokens
    StringValue GetTokens() const;
    void SetTokens(const StringValue& value);

    /// process
    StringValue GetProcess() const;
    void SetProcess(const StringValue& value);

    /// lang
    StringValue GetLanguage() const;
    void SetLanguage(const StringValue& value);

    /// signal
    StringValue GetSignal() const;
    void SetSignal(const StringValue& value);

    /// signal-size
    IntegerValue GetSignalSize() const;
    void SetSignalSize(const IntegerValue& value);

    /// media-type
    StringValue GetMediaType() const;
    void SetMediaType(const StringValue& value);

    /// confidence
    DecimalValue GetConfidence() const;
    void SetConfidence(const DecimalValue& value);

    /// source
    StringValue GetSource() const;
    void SetSource(const StringValue& value);

    /// start
    UInt64Value GetStart() const;
    void SetStart(const UInt64Value& value);

    /// end
    UInt64Value GetEnd() const;
    void SetEnd(const UInt64Value& value);

    /// time-ref-uri
    StringValue GetTimeReference() const;
    void SetTimeReference(const StringValue& value);

    /// time-ref-anchor-point
    EnumValue<AnchorPointValues> GetTimeReferenceAnchorPoint() const;
    void SetTimeReferenceAnchorPoint(const EnumValue<AnchorPointValues>& value);

    /// offset-to-start
    IntegerValue GetOffsetToStart() const;
    void SetOffsetToStart(const IntegerValue& value);

    /// duration
    IntegerValue GetDuration() const;
    void SetDuration(const IntegerValue& value);

    /// medium
    ListValue<EnumValue<MediumValues>> GetMedium() const;
    void SetMedium(const ListValue<EnumValue<MediumValues>>& value);

    /// mode
    ListValue<StringValue> GetMode() const;
    void SetMode(const ListValue<StringValue>& value);

    /// function
    StringValue GetFunction() const;
    void SetFunction(const StringValue& value);

    /// verbal
    BooleanValue GetVerbal() const;
    void SetVerbal(const BooleanValue& value);

    /// cost
    DecimalValue GetCost() const;
    void SetCost(const DecimalValue& value);

    /// grammar-ref
    StringValue GetGrammarRef() const;
    void SetGrammarRef(const StringValue& value);

    /// endpoint-info-ref
    StringValue GetEndpointInfoRef() const;
    void SetEndpointInfoRef(const StringValue& value);

    /// model-ref
    StringValue GetModelRef() const;
    void SetModelRef(const StringValue& value);

    /// dialog-turn
    StringValue GetDialogTurn() const;
    void SetDialogTurn(const StringValue& value);

    /// no-input
    BooleanValue GetNoInput() const;
    void SetNoInput(const BooleanValue& value);

    /// uninterpreted
    BooleanValue GetUninterpreted() const;
    void SetUninterpreted(const BooleanValue& value);

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the Literal Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.EMMA
/// Type QName: emma:CT_Literal
/// Element QName: emma:literal
/// Source: www_w3_org_2003_04_emma.json
class EXYOKIOFFICE_EXPORT Literal : public OpenXmlLeafTextElement
{
public:
    using Ptr = std::shared_ptr<Literal>;

    inline Literal() = default;
    inline ~Literal() = default;

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the Lattice Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.EMMA
/// Type QName: emma:CT_Lattice
/// Element QName: emma:lattice
/// Source: www_w3_org_2003_04_emma.json
class EXYOKIOFFICE_EXPORT Lattice : public OpenXmlCompositeElement
{
public:
    using Ptr = std::shared_ptr<Lattice>;

    inline Lattice() = default;
    inline ~Lattice() = default;

    /// initial
    IntegerValue GetInitial() const;
    void SetInitial(const IntegerValue& value);

    /// final
    ListValue<DecimalValue> GetFinal() const;
    void SetFinal(const ListValue<DecimalValue>& value);

    /// time-ref-uri
    StringValue GetTimeReference() const;
    void SetTimeReference(const StringValue& value);

    /// time-ref-anchor-point
    EnumValue<AnchorPointValues> GetTimeReferenceAnchorPoint() const;
    void SetTimeReferenceAnchorPoint(const EnumValue<AnchorPointValues>& value);

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the Info Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.EMMA
/// Type QName: emma:CT_Info
/// Element QName: emma:info
/// Source: www_w3_org_2003_04_emma.json
class EXYOKIOFFICE_EXPORT Info : public OpenXmlCompositeElement
{
public:
    using Ptr = std::shared_ptr<Info>;

    inline Info() = default;
    inline ~Info() = default;

    /// id
    StringValue GetId() const;
    void SetId(const StringValue& value);

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the DerivedFrom Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.EMMA
/// Type QName: emma:CT_DerivedFrom
/// Element QName: emma:derived-from
/// Source: www_w3_org_2003_04_emma.json
class EXYOKIOFFICE_EXPORT DerivedFrom : public OpenXmlLeafElement
{
public:
    using Ptr = std::shared_ptr<DerivedFrom>;

    inline DerivedFrom() = default;
    inline ~DerivedFrom() = default;

    /// resource
    StringValue GetResource() const;
    void SetResource(const StringValue& value);

    /// composite
    BooleanValue GetComposite() const;
    void SetComposite(const BooleanValue& value);

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

} // namespace EMMA
} // namespace OpenXml
} // namespace DocumentFormat
} // namespace ExyokiOffice
