// Copyright (c) 2026 Jakub Melka and Contributors
// SPDX-License-Identifier: MIT
// See LICENSE file in the project root for full license text.
//
// Derived from the Open-XML-SDK metadata under data/, which is
// Copyright (c) .NET Foundation and Contributors and MIT-licensed.
// See data/LICENSE and THIRD-PARTY-LICENSES.md in the project root.
// -----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by ExyokiOffice OpenXML generator.
//     Manual changes to this file may cause unexpected behaviour.
// </auto-generated>
// -----------------------------------------------------------------------------

#pragma once

#include "ExyokiOffice/OpenXMLElement.hpp"

#include <memory>
#include <span>
#include <string_view>

namespace ExyokiOffice {
namespace DocumentFormat {
namespace OpenXml {
namespace Office {
namespace Y2022 {
namespace FeaturePropertyBag {


using OpenXMLElement = ExyokiOffice::OpenXMLElement;
using OpenXmlCompositeElement = ExyokiOffice::OpenXmlCompositeElement;
using OpenXmlPartRootElement = ExyokiOffice::OpenXmlPartRootElement;
using OpenXmlLeafElement = ExyokiOffice::OpenXmlLeafElement;
using OpenXmlLeafTextElement = ExyokiOffice::OpenXmlLeafTextElement;

/// \brief Defines the Xsddouble Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office.Y2022.FeaturePropertyBag
/// Type QName: xsd:double
/// Element QName: xfpb:d
/// Source: schemas_microsoft_com_office_spreadsheetml_2022_featurepropertybag.json
class EXYOKIOFFICE_EXPORT Xsddouble : public OpenXmlLeafTextElement
{
public:
    using Ptr = std::shared_ptr<Xsddouble>;

    inline Xsddouble() = default;
    inline ~Xsddouble() = default;

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the Xsdboolean Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office.Y2022.FeaturePropertyBag
/// Type QName: xsd:boolean
/// Element QName: xfpb:b
/// Source: schemas_microsoft_com_office_spreadsheetml_2022_featurepropertybag.json
class EXYOKIOFFICE_EXPORT Xsdboolean : public OpenXmlLeafTextElement
{
public:
    using Ptr = std::shared_ptr<Xsdboolean>;

    inline Xsdboolean() = default;
    inline ~Xsdboolean() = default;

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the RelXsdstring Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office.Y2022.FeaturePropertyBag
/// Type QName: xsd:string
/// Element QName: xfpb:rel
/// Source: schemas_microsoft_com_office_spreadsheetml_2022_featurepropertybag.json
class EXYOKIOFFICE_EXPORT RelXsdstring : public OpenXmlLeafTextElement
{
public:
    using Ptr = std::shared_ptr<RelXsdstring>;

    inline RelXsdstring() = default;
    inline ~RelXsdstring() = default;

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the SXsdstring Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office.Y2022.FeaturePropertyBag
/// Type QName: xsd:string
/// Element QName: xfpb:s
/// Source: schemas_microsoft_com_office_spreadsheetml_2022_featurepropertybag.json
class EXYOKIOFFICE_EXPORT SXsdstring : public OpenXmlLeafTextElement
{
public:
    using Ptr = std::shared_ptr<SXsdstring>;

    inline SXsdstring() = default;
    inline ~SXsdstring() = default;

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the Xsdinteger Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office.Y2022.FeaturePropertyBag
/// Type QName: xsd:integer
/// Element QName: xfpb:i
/// Source: schemas_microsoft_com_office_spreadsheetml_2022_featurepropertybag.json
class EXYOKIOFFICE_EXPORT Xsdinteger : public OpenXmlLeafTextElement
{
public:
    using Ptr = std::shared_ptr<Xsdinteger>;

    inline Xsdinteger() = default;
    inline ~Xsdinteger() = default;

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the XsdunsignedInt Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office.Y2022.FeaturePropertyBag
/// Type QName: xsd:unsignedInt
/// Element QName: xfpb:bagId
/// Source: schemas_microsoft_com_office_spreadsheetml_2022_featurepropertybag.json
class EXYOKIOFFICE_EXPORT XsdunsignedInt : public OpenXmlLeafTextElement
{
public:
    using Ptr = std::shared_ptr<XsdunsignedInt>;

    inline XsdunsignedInt() = default;
    inline ~XsdunsignedInt() = default;

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the DifferentialFormatType Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office.Y2022.FeaturePropertyBag
/// Type QName: x:CT_Dxf
/// Element QName: xfpb:dxf
/// Source: schemas_microsoft_com_office_spreadsheetml_2022_featurepropertybag.json
class EXYOKIOFFICE_EXPORT DifferentialFormatType : public OpenXmlCompositeElement
{
public:
    using Ptr = std::shared_ptr<DifferentialFormatType>;

    inline DifferentialFormatType() = default;
    inline ~DifferentialFormatType() = default;

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the RelFeatureProperty Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office.Y2022.FeaturePropertyBag
/// Type QName: xfpb:CT_RelFeatureProperty
/// Element QName: xfpb:rel
/// Source: schemas_microsoft_com_office_spreadsheetml_2022_featurepropertybag.json
class EXYOKIOFFICE_EXPORT RelFeatureProperty : public OpenXmlLeafTextElement
{
public:
    using Ptr = std::shared_ptr<RelFeatureProperty>;

    inline RelFeatureProperty() = default;
    inline ~RelFeatureProperty() = default;

    /// Name of the key for the key value pair.
    StringValue GetK() const;
    void SetK(const StringValue& value);

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the DecimalFeatureProperty Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office.Y2022.FeaturePropertyBag
/// Type QName: xfpb:CT_DecimalFeatureProperty
/// Element QName: xfpb:d
/// Source: schemas_microsoft_com_office_spreadsheetml_2022_featurepropertybag.json
class EXYOKIOFFICE_EXPORT DecimalFeatureProperty : public OpenXmlLeafTextElement
{
public:
    using Ptr = std::shared_ptr<DecimalFeatureProperty>;

    inline DecimalFeatureProperty() = default;
    inline ~DecimalFeatureProperty() = default;

    /// k
    StringValue GetK() const;
    void SetK(const StringValue& value);

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the BoolFeatureProperty Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office.Y2022.FeaturePropertyBag
/// Type QName: xfpb:CT_BoolFeatureProperty
/// Element QName: xfpb:b
/// Source: schemas_microsoft_com_office_spreadsheetml_2022_featurepropertybag.json
class EXYOKIOFFICE_EXPORT BoolFeatureProperty : public OpenXmlLeafTextElement
{
public:
    using Ptr = std::shared_ptr<BoolFeatureProperty>;

    inline BoolFeatureProperty() = default;
    inline ~BoolFeatureProperty() = default;

    /// k
    StringValue GetK() const;
    void SetK(const StringValue& value);

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the StringFeatureProperty Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office.Y2022.FeaturePropertyBag
/// Type QName: xfpb:CT_StringFeatureProperty
/// Element QName: xfpb:s
/// Source: schemas_microsoft_com_office_spreadsheetml_2022_featurepropertybag.json
class EXYOKIOFFICE_EXPORT StringFeatureProperty : public OpenXmlLeafTextElement
{
public:
    using Ptr = std::shared_ptr<StringFeatureProperty>;

    inline StringFeatureProperty() = default;
    inline ~StringFeatureProperty() = default;

    /// k
    StringValue GetK() const;
    void SetK(const StringValue& value);

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the IntFeatureProperty Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office.Y2022.FeaturePropertyBag
/// Type QName: xfpb:CT_IntFeatureProperty
/// Element QName: xfpb:i
/// Source: schemas_microsoft_com_office_spreadsheetml_2022_featurepropertybag.json
class EXYOKIOFFICE_EXPORT IntFeatureProperty : public OpenXmlLeafTextElement
{
public:
    using Ptr = std::shared_ptr<IntFeatureProperty>;

    inline IntFeatureProperty() = default;
    inline ~IntFeatureProperty() = default;

    /// k
    StringValue GetK() const;
    void SetK(const StringValue& value);

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the BagFeatureProperty Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office.Y2022.FeaturePropertyBag
/// Type QName: xfpb:CT_BagFeatureProperty
/// Element QName: xfpb:bagId
/// Source: schemas_microsoft_com_office_spreadsheetml_2022_featurepropertybag.json
class EXYOKIOFFICE_EXPORT BagFeatureProperty : public OpenXmlLeafTextElement
{
public:
    using Ptr = std::shared_ptr<BagFeatureProperty>;

    inline BagFeatureProperty() = default;
    inline ~BagFeatureProperty() = default;

    /// k
    StringValue GetK() const;
    void SetK(const StringValue& value);

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the ArrayFeatureProperty Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office.Y2022.FeaturePropertyBag
/// Type QName: xfpb:CT_ArrayFeatureProperty
/// Element QName: xfpb:a
/// Source: schemas_microsoft_com_office_spreadsheetml_2022_featurepropertybag.json
class EXYOKIOFFICE_EXPORT ArrayFeatureProperty : public OpenXmlCompositeElement
{
public:
    using Ptr = std::shared_ptr<ArrayFeatureProperty>;

    inline ArrayFeatureProperty() = default;
    inline ~ArrayFeatureProperty() = default;

    /// Name of the key for the key value pair.
    StringValue GetK() const;
    void SetK(const StringValue& value);

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the ExtensionList Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office.Y2022.FeaturePropertyBag
/// Type QName: x:CT_ExtensionList
/// Element QName: xfpb:extLst
/// Source: schemas_microsoft_com_office_spreadsheetml_2022_featurepropertybag.json
class EXYOKIOFFICE_EXPORT ExtensionList : public OpenXmlCompositeElement
{
public:
    using Ptr = std::shared_ptr<ExtensionList>;

    inline ExtensionList() = default;
    inline ~ExtensionList() = default;

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the FeaturePropertyBag Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office.Y2022.FeaturePropertyBag
/// Type QName: xfpb:CT_FeaturePropertyBag
/// Element QName: xfpb:bag
/// Source: schemas_microsoft_com_office_spreadsheetml_2022_featurepropertybag.json
class EXYOKIOFFICE_EXPORT FeaturePropertyBag : public OpenXmlCompositeElement
{
public:
    using Ptr = std::shared_ptr<FeaturePropertyBag>;

    inline FeaturePropertyBag() = default;
    inline ~FeaturePropertyBag() = default;

    /// type
    StringValue GetType() const;
    void SetType(const StringValue& value);

    /// extRef
    StringValue GetExtRef() const;
    void SetExtRef(const StringValue& value);

    /// bagExtId
    UInt32Value GetBagExtId() const;
    void SetBagExtId(const UInt32Value& value);

    /// att
    StringValue GetAtt() const;
    void SetAtt(const StringValue& value);

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the BagExtensions Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office.Y2022.FeaturePropertyBag
/// Type QName: xfpb:CT_BagExtensions
/// Element QName: xfpb:bagExt
/// Source: schemas_microsoft_com_office_spreadsheetml_2022_featurepropertybag.json
class EXYOKIOFFICE_EXPORT BagExtensions : public OpenXmlCompositeElement
{
public:
    using Ptr = std::shared_ptr<BagExtensions>;

    inline BagExtensions() = default;
    inline ~BagExtensions() = default;

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the OpenXmlTableRevDxfElement Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office.Y2022.FeaturePropertyBag
/// Type QName: xfpb:CT_TableRevDxf
/// Element QName: (none)
/// Source: schemas_microsoft_com_office_spreadsheetml_2022_featurepropertybag.json
class EXYOKIOFFICE_EXPORT OpenXmlTableRevDxfElement : public OpenXmlCompositeElement
{
public:
    using Ptr = std::shared_ptr<OpenXmlTableRevDxfElement>;

    inline OpenXmlTableRevDxfElement() = default;
    inline ~OpenXmlTableRevDxfElement() = default;

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the ColumnTotalsRevDxfTableRevDxf Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office.Y2022.FeaturePropertyBag
/// Type QName: xfpb:CT_TableRevDxf
/// Element QName: xfpb:columnTotalsRevDxf
/// Source: schemas_microsoft_com_office_spreadsheetml_2022_featurepropertybag.json
class EXYOKIOFFICE_EXPORT ColumnTotalsRevDxfTableRevDxf : public OpenXmlTableRevDxfElement
{
public:
    using Ptr = std::shared_ptr<ColumnTotalsRevDxfTableRevDxf>;

    inline ColumnTotalsRevDxfTableRevDxf() = default;
    inline ~ColumnTotalsRevDxfTableRevDxf() = default;

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the ColumnBodyRevDxfTableRevDxf Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office.Y2022.FeaturePropertyBag
/// Type QName: xfpb:CT_TableRevDxf
/// Element QName: xfpb:columnBodyRevDxf
/// Source: schemas_microsoft_com_office_spreadsheetml_2022_featurepropertybag.json
class EXYOKIOFFICE_EXPORT ColumnBodyRevDxfTableRevDxf : public OpenXmlTableRevDxfElement
{
public:
    using Ptr = std::shared_ptr<ColumnBodyRevDxfTableRevDxf>;

    inline ColumnBodyRevDxfTableRevDxf() = default;
    inline ~ColumnBodyRevDxfTableRevDxf() = default;

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the ColumnHeaderRevDxfTableRevDxf Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office.Y2022.FeaturePropertyBag
/// Type QName: xfpb:CT_TableRevDxf
/// Element QName: xfpb:columnHeaderRevDxf
/// Source: schemas_microsoft_com_office_spreadsheetml_2022_featurepropertybag.json
class EXYOKIOFFICE_EXPORT ColumnHeaderRevDxfTableRevDxf : public OpenXmlTableRevDxfElement
{
public:
    using Ptr = std::shared_ptr<ColumnHeaderRevDxfTableRevDxf>;

    inline ColumnHeaderRevDxfTableRevDxf() = default;
    inline ~ColumnHeaderRevDxfTableRevDxf() = default;

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the TotalsRowBorderRevDxfTableRevDxf Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office.Y2022.FeaturePropertyBag
/// Type QName: xfpb:CT_TableRevDxf
/// Element QName: xfpb:totalsRowBorderRevDxf
/// Source: schemas_microsoft_com_office_spreadsheetml_2022_featurepropertybag.json
class EXYOKIOFFICE_EXPORT TotalsRowBorderRevDxfTableRevDxf : public OpenXmlTableRevDxfElement
{
public:
    using Ptr = std::shared_ptr<TotalsRowBorderRevDxfTableRevDxf>;

    inline TotalsRowBorderRevDxfTableRevDxf() = default;
    inline ~TotalsRowBorderRevDxfTableRevDxf() = default;

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the TableBorderRevDxfTableRevDxf Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office.Y2022.FeaturePropertyBag
/// Type QName: xfpb:CT_TableRevDxf
/// Element QName: xfpb:tableBorderRevDxf
/// Source: schemas_microsoft_com_office_spreadsheetml_2022_featurepropertybag.json
class EXYOKIOFFICE_EXPORT TableBorderRevDxfTableRevDxf : public OpenXmlTableRevDxfElement
{
public:
    using Ptr = std::shared_ptr<TableBorderRevDxfTableRevDxf>;

    inline TableBorderRevDxfTableRevDxf() = default;
    inline ~TableBorderRevDxfTableRevDxf() = default;

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the HeaderRowBorderRevDxfTableRevDxf Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office.Y2022.FeaturePropertyBag
/// Type QName: xfpb:CT_TableRevDxf
/// Element QName: xfpb:headerRowBorderRevDxf
/// Source: schemas_microsoft_com_office_spreadsheetml_2022_featurepropertybag.json
class EXYOKIOFFICE_EXPORT HeaderRowBorderRevDxfTableRevDxf : public OpenXmlTableRevDxfElement
{
public:
    using Ptr = std::shared_ptr<HeaderRowBorderRevDxfTableRevDxf>;

    inline HeaderRowBorderRevDxfTableRevDxf() = default;
    inline ~HeaderRowBorderRevDxfTableRevDxf() = default;

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the TotalsRowRevDxfTableRevDxf Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office.Y2022.FeaturePropertyBag
/// Type QName: xfpb:CT_TableRevDxf
/// Element QName: xfpb:totalsRowRevDxf
/// Source: schemas_microsoft_com_office_spreadsheetml_2022_featurepropertybag.json
class EXYOKIOFFICE_EXPORT TotalsRowRevDxfTableRevDxf : public OpenXmlTableRevDxfElement
{
public:
    using Ptr = std::shared_ptr<TotalsRowRevDxfTableRevDxf>;

    inline TotalsRowRevDxfTableRevDxf() = default;
    inline ~TotalsRowRevDxfTableRevDxf() = default;

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the DataRevDxfTableRevDxf Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office.Y2022.FeaturePropertyBag
/// Type QName: xfpb:CT_TableRevDxf
/// Element QName: xfpb:dataRevDxf
/// Source: schemas_microsoft_com_office_spreadsheetml_2022_featurepropertybag.json
class EXYOKIOFFICE_EXPORT DataRevDxfTableRevDxf : public OpenXmlTableRevDxfElement
{
public:
    using Ptr = std::shared_ptr<DataRevDxfTableRevDxf>;

    inline DataRevDxfTableRevDxf() = default;
    inline ~DataRevDxfTableRevDxf() = default;

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the HeaderRowRevDxfTableRevDxf Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office.Y2022.FeaturePropertyBag
/// Type QName: xfpb:CT_TableRevDxf
/// Element QName: xfpb:headerRowRevDxf
/// Source: schemas_microsoft_com_office_spreadsheetml_2022_featurepropertybag.json
class EXYOKIOFFICE_EXPORT HeaderRowRevDxfTableRevDxf : public OpenXmlTableRevDxfElement
{
public:
    using Ptr = std::shared_ptr<HeaderRowRevDxfTableRevDxf>;

    inline HeaderRowRevDxfTableRevDxf() = default;
    inline ~HeaderRowRevDxfTableRevDxf() = default;

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the RevDxf Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office.Y2022.FeaturePropertyBag
/// Type QName: xfpb:CT_RevDxf
/// Element QName: xfpb:revdxf
/// Source: schemas_microsoft_com_office_spreadsheetml_2022_featurepropertybag.json
class EXYOKIOFFICE_EXPORT RevDxf : public OpenXmlCompositeElement
{
public:
    using Ptr = std::shared_ptr<RevDxf>;

    inline RevDxf() = default;
    inline ~RevDxf() = default;

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the DXFComplement Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office.Y2022.FeaturePropertyBag
/// Type QName: xfpb:CT_DXFComplement
/// Element QName: xfpb:DXFComplement
/// Source: schemas_microsoft_com_office_spreadsheetml_2022_featurepropertybag.json
class EXYOKIOFFICE_EXPORT DXFComplement : public OpenXmlLeafElement
{
public:
    using Ptr = std::shared_ptr<DXFComplement>;

    inline DXFComplement() = default;
    inline ~DXFComplement() = default;

    /// i
    UInt32Value GetI() const;
    void SetI(const UInt32Value& value);

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the XfComplement Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office.Y2022.FeaturePropertyBag
/// Type QName: xfpb:CT_XfComplement
/// Element QName: xfpb:xfComplement
/// Source: schemas_microsoft_com_office_spreadsheetml_2022_featurepropertybag.json
class EXYOKIOFFICE_EXPORT XfComplement : public OpenXmlLeafElement
{
public:
    using Ptr = std::shared_ptr<XfComplement>;

    inline XfComplement() = default;
    inline ~XfComplement() = default;

    /// i
    UInt32Value GetI() const;
    void SetI(const UInt32Value& value);

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the OpenXmlFeaturePropertyBagsElement Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office.Y2022.FeaturePropertyBag
/// Type QName: xfpb:CT_FeaturePropertyBags
/// Element QName: (none)
/// Source: schemas_microsoft_com_office_spreadsheetml_2022_featurepropertybag.json
class EXYOKIOFFICE_EXPORT OpenXmlFeaturePropertyBagsElement : public OpenXmlCompositeElement
{
public:
    using Ptr = std::shared_ptr<OpenXmlFeaturePropertyBagsElement>;

    inline OpenXmlFeaturePropertyBagsElement() = default;
    inline ~OpenXmlFeaturePropertyBagsElement() = default;

    /// count
    UInt32Value GetCount() const;
    void SetCount(const UInt32Value& value);

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the FpbsFeaturePropertyBags Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office.Y2022.FeaturePropertyBag
/// Type QName: xfpb:CT_FeaturePropertyBags
/// Element QName: xfpb:fpbs
/// Source: schemas_microsoft_com_office_spreadsheetml_2022_featurepropertybag.json
class EXYOKIOFFICE_EXPORT FpbsFeaturePropertyBags : public OpenXmlFeaturePropertyBagsElement
{
public:
    using Ptr = std::shared_ptr<FpbsFeaturePropertyBags>;

    inline FpbsFeaturePropertyBags() = default;
    inline ~FpbsFeaturePropertyBags() = default;

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the FeaturePropertyBags Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office.Y2022.FeaturePropertyBag
/// Type QName: xfpb:CT_FeaturePropertyBags
/// Element QName: xfpb:FeaturePropertyBags
/// Source: schemas_microsoft_com_office_spreadsheetml_2022_featurepropertybag.json
class EXYOKIOFFICE_EXPORT FeaturePropertyBags : public OpenXmlCompositeElement
{
public:
    using Ptr = std::shared_ptr<FeaturePropertyBags>;

    inline FeaturePropertyBags() = default;
    inline ~FeaturePropertyBags() = default;

    /// count
    UInt32Value GetCount() const;
    void SetCount(const UInt32Value& value);

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

} // namespace FeaturePropertyBag
} // namespace Y2022
} // namespace Office
} // namespace OpenXml
} // namespace DocumentFormat
} // namespace ExyokiOffice
