// Copyright (c) 2026 Jakub Melka and Collaborators
// SPDX-License-Identifier: MIT
// See LICENSE file in the project root for full license text.
// -----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by ExyokiOffice OpenXML generator.
//     Manual changes to this file may cause unexpected behaviour.
// </auto-generated>
// -----------------------------------------------------------------------------

#pragma once

#include "ExyokiOffice/OpenXMLElement.hpp"
#include "ExyokiOffice/DOM/DocumentFormat/OpenXml/Drawing.Enums.hpp"

#include <memory>
#include <span>
#include <string_view>

namespace ExyokiOffice {
namespace DocumentFormat {
namespace OpenXml {
namespace Office2010 {
namespace Drawing {
namespace Charts {


using OpenXMLElement = ExyokiOffice::OpenXMLElement;
using OpenXmlCompositeElement = ExyokiOffice::OpenXmlCompositeElement;
using OpenXmlPartRootElement = ExyokiOffice::OpenXmlPartRootElement;
using OpenXmlLeafElement = ExyokiOffice::OpenXmlLeafElement;
using OpenXmlLeafTextElement = ExyokiOffice::OpenXmlLeafTextElement;

/// \brief Defines the ShowSketchButton Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office2010.Drawing.Charts
/// Type QName: c14:CT_BooleanTrue
/// Element QName: c14:showSketchBtn
/// Source: schemas_microsoft_com_office_drawing_2007_8_2_chart.json
class EXYOKIOFFICE_EXPORT ShowSketchButton : public OpenXmlLeafElement
{
public:
    using Ptr = std::shared_ptr<ShowSketchButton>;

    inline ShowSketchButton() = default;
    inline ~ShowSketchButton() = default;

    /// val
    BooleanValue GetVal() const;
    void SetVal(const BooleanValue& value);

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the BooleanFalseType Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office2010.Drawing.Charts
/// Type QName: c14:CT_BooleanFalse
/// Element QName: (none)
/// Source: schemas_microsoft_com_office_drawing_2007_8_2_chart.json
class EXYOKIOFFICE_EXPORT BooleanFalseType : public OpenXmlLeafElement
{
public:
    using Ptr = std::shared_ptr<BooleanFalseType>;

    inline BooleanFalseType() = default;
    inline ~BooleanFalseType() = default;

    /// val
    BooleanValue GetVal() const;
    void SetVal(const BooleanValue& value);

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the InSketchMode Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office2010.Drawing.Charts
/// Type QName: c14:CT_BooleanFalse
/// Element QName: c14:inSketchMode
/// Source: schemas_microsoft_com_office_drawing_2007_8_2_chart.json
class EXYOKIOFFICE_EXPORT InSketchMode : public BooleanFalseType
{
public:
    using Ptr = std::shared_ptr<InSketchMode>;

    inline InSketchMode() = default;
    inline ~InSketchMode() = default;

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the DropZonesVisible Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office2010.Drawing.Charts
/// Type QName: c14:CT_BooleanFalse
/// Element QName: c14:dropZonesVisible
/// Source: schemas_microsoft_com_office_drawing_2007_8_2_chart.json
class EXYOKIOFFICE_EXPORT DropZonesVisible : public BooleanFalseType
{
public:
    using Ptr = std::shared_ptr<DropZonesVisible>;

    inline DropZonesVisible() = default;
    inline ~DropZonesVisible() = default;

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the DropZoneSeries Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office2010.Drawing.Charts
/// Type QName: c14:CT_BooleanFalse
/// Element QName: c14:dropZoneSeries
/// Source: schemas_microsoft_com_office_drawing_2007_8_2_chart.json
class EXYOKIOFFICE_EXPORT DropZoneSeries : public BooleanFalseType
{
public:
    using Ptr = std::shared_ptr<DropZoneSeries>;

    inline DropZoneSeries() = default;
    inline ~DropZoneSeries() = default;

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the DropZoneData Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office2010.Drawing.Charts
/// Type QName: c14:CT_BooleanFalse
/// Element QName: c14:dropZoneData
/// Source: schemas_microsoft_com_office_drawing_2007_8_2_chart.json
class EXYOKIOFFICE_EXPORT DropZoneData : public BooleanFalseType
{
public:
    using Ptr = std::shared_ptr<DropZoneData>;

    inline DropZoneData() = default;
    inline ~DropZoneData() = default;

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the DropZoneCategories Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office2010.Drawing.Charts
/// Type QName: c14:CT_BooleanFalse
/// Element QName: c14:dropZoneCategories
/// Source: schemas_microsoft_com_office_drawing_2007_8_2_chart.json
class EXYOKIOFFICE_EXPORT DropZoneCategories : public BooleanFalseType
{
public:
    using Ptr = std::shared_ptr<DropZoneCategories>;

    inline DropZoneCategories() = default;
    inline ~DropZoneCategories() = default;

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the DropZoneFilter Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office2010.Drawing.Charts
/// Type QName: c14:CT_BooleanFalse
/// Element QName: c14:dropZoneFilter
/// Source: schemas_microsoft_com_office_drawing_2007_8_2_chart.json
class EXYOKIOFFICE_EXPORT DropZoneFilter : public BooleanFalseType
{
public:
    using Ptr = std::shared_ptr<DropZoneFilter>;

    inline DropZoneFilter() = default;
    inline ~DropZoneFilter() = default;

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the ShapeProperties Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office2010.Drawing.Charts
/// Type QName: a:CT_ShapeProperties
/// Element QName: c14:spPr
/// Source: schemas_microsoft_com_office_drawing_2007_8_2_chart.json
class EXYOKIOFFICE_EXPORT ShapeProperties : public OpenXmlCompositeElement
{
public:
    using Ptr = std::shared_ptr<ShapeProperties>;

    inline ShapeProperties() = default;
    inline ~ShapeProperties() = default;

    /// Black and White Mode
    EnumValue<ExyokiOffice::DocumentFormat::OpenXml::Drawing::BlackWhiteModeValues> GetBlackWhiteMode() const;
    void SetBlackWhiteMode(const EnumValue<ExyokiOffice::DocumentFormat::OpenXml::Drawing::BlackWhiteModeValues>& value);

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the Style Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office2010.Drawing.Charts
/// Type QName: c14:CT_Style
/// Element QName: c14:style
/// Source: schemas_microsoft_com_office_drawing_2007_8_2_chart.json
class EXYOKIOFFICE_EXPORT Style : public OpenXmlLeafElement
{
public:
    using Ptr = std::shared_ptr<Style>;

    inline Style() = default;
    inline ~Style() = default;

    /// val
    ByteValue GetVal() const;
    void SetVal(const ByteValue& value);

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the InvertSolidFillFormat Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office2010.Drawing.Charts
/// Type QName: c14:CT_InvertSolidFillFmt
/// Element QName: c14:invertSolidFillFmt
/// Source: schemas_microsoft_com_office_drawing_2007_8_2_chart.json
class EXYOKIOFFICE_EXPORT InvertSolidFillFormat : public OpenXmlCompositeElement
{
public:
    using Ptr = std::shared_ptr<InvertSolidFillFormat>;

    inline InvertSolidFillFormat() = default;
    inline ~InvertSolidFillFormat() = default;

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the SketchOptions Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office2010.Drawing.Charts
/// Type QName: c14:CT_SketchOptions
/// Element QName: c14:sketchOptions
/// Source: schemas_microsoft_com_office_drawing_2007_8_2_chart.json
class EXYOKIOFFICE_EXPORT SketchOptions : public OpenXmlCompositeElement
{
public:
    using Ptr = std::shared_ptr<SketchOptions>;

    inline SketchOptions() = default;
    inline ~SketchOptions() = default;

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

/// \brief Defines the PivotOptions Class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office2010.Drawing.Charts
/// Type QName: c14:CT_PivotOptions
/// Element QName: c14:pivotOptions
/// Source: schemas_microsoft_com_office_drawing_2007_8_2_chart.json
class EXYOKIOFFICE_EXPORT PivotOptions : public OpenXmlCompositeElement
{
public:
    using Ptr = std::shared_ptr<PivotOptions>;

    inline PivotOptions() = default;
    inline ~PivotOptions() = default;

    static const ExyokiOffice::OpenXMLElementClass* StaticMetaClass() noexcept;
    const ExyokiOffice::OpenXMLElementClass* ElementMetaClass() const noexcept override;
};

} // namespace Charts
} // namespace Drawing
} // namespace Office2010
} // namespace OpenXml
} // namespace DocumentFormat
} // namespace ExyokiOffice
