// Copyright (c) 2026 Jakub Melka and Contributors
// SPDX-License-Identifier: MIT
// See LICENSE file in the project root for full license text.
//
// Derived from the Open-XML-SDK metadata under data/, which is
// Copyright (c) .NET Foundation and Contributors and MIT-licensed.
// See data/LICENSE and THIRD-PARTY-LICENSES.md in the project root.
// -----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by ExyokiOffice OpenXML generator.
//     Manual changes to this file may cause unexpected behaviour.
// </auto-generated>
// -----------------------------------------------------------------------------

#include "ExyokiOffice/DOM/DocumentFormat/OpenXml/Office2021/MipLabelMetaData.hpp"
#include "ExyokiOffice/FileFormatVersions.h"
#include "ExyokiOffice/StandardTypes.hpp"

#include <array>
#include <memory>
#include <optional>
#include <span>
#include <string_view>
#include <utility>
#include <vector>

namespace ExyokiOffice {
namespace DocumentFormat {
namespace OpenXml {
namespace Office2021 {
namespace MipLabelMetaData {

ExyokiOffice::MetadataParticlePtr CreateClassificationExtensionListParticleMetadata()
{
    auto particleNode0 = std::make_shared<ExyokiOffice::MetadataSequenceParticle>(0, std::optional<ExyokiOffice::UInt32>{1}, ExyokiOffice::OpenXml::FileFormatVersions::Office2007, false);
    auto particleNode1 = std::make_shared<ExyokiOffice::MetadataElementParticle>(ExyokiOffice::OpenXmlQualifiedName("http://schemas.microsoft.com/office/2020/mipLabelMetadata", "ext"), "ExyokiOffice::DocumentFormat::OpenXml::Office2021::MipLabelMetaData::ClassificationExtension", "CT_ClassificationExtension/clbl:ext", 0, std::optional<ExyokiOffice::UInt32>{}, ExyokiOffice::OpenXml::FileFormatVersions::Office2021);
    particleNode0->AddChild(particleNode1);
    return particleNode0;
}

namespace {
class ClassificationExtensionListMetaClass final : public ExyokiOffice::OpenXMLElementClass
{
public:
    const ExyokiOffice::OpenXMLElementClass* GetBaseMetaClass() const noexcept override
    {
        return OpenXmlCompositeElement::StaticMetaClass();
    }

    ExyokiOffice::OpenXmlQualifiedName QualifiedName() const noexcept override
    {
        return ExyokiOffice::OpenXmlQualifiedName("http://schemas.microsoft.com/office/2020/mipLabelMetadata", "extLst");
    }

    ExyokiOffice::OpenXmlQualifiedName TypeQualifiedName() const noexcept override
    {
        return ExyokiOffice::OpenXmlQualifiedName("http://schemas.microsoft.com/office/2020/mipLabelMetadata", "CT_ClassificationExtensionList");
    }

    ExyokiOffice::OpenXml::FileFormatVersions GetVersion() const noexcept override
    {
        return ExyokiOffice::OpenXml::FileFormatVersions::Office2021;
    }

    ExyokiOffice::OpenXmlElementClassFlags GetFlags() const noexcept override
    {
        return ExyokiOffice::OpenXmlElementClassFlags{};
    }

    std::shared_ptr<ExyokiOffice::OpenXMLElement> Create() const override
    {
        return std::make_shared<ClassificationExtensionList>();
    }

    void ConfigureMetadata(ExyokiOffice::MetadataBuilder& builder) const override
    {
        builder.SetSchemaName("schemas_microsoft_com_office_2020_mipLabelMetadata.json");
        builder.SetAvailability(ExyokiOffice::OpenXml::FileFormatVersions::Office2021);
        builder.SetParticleTree(CreateClassificationExtensionListParticleMetadata());
    }
};
} // namespace

const ExyokiOffice::OpenXMLElementClass* ClassificationExtensionList::StaticMetaClass() noexcept
{
    static const ClassificationExtensionListMetaClass kMeta{};
    return &kMeta;
}

const ExyokiOffice::OpenXMLElementClass* ClassificationExtensionList::ElementMetaClass() const noexcept
{
    return ClassificationExtensionList::StaticMetaClass();
}

namespace {
class ClassificationLabelMetaClass final : public ExyokiOffice::OpenXMLElementClass
{
public:
    const ExyokiOffice::OpenXMLElementClass* GetBaseMetaClass() const noexcept override
    {
        return OpenXmlLeafElement::StaticMetaClass();
    }

    ExyokiOffice::OpenXmlQualifiedName QualifiedName() const noexcept override
    {
        return ExyokiOffice::OpenXmlQualifiedName("http://schemas.microsoft.com/office/2020/mipLabelMetadata", "label");
    }

    ExyokiOffice::OpenXmlQualifiedName TypeQualifiedName() const noexcept override
    {
        return ExyokiOffice::OpenXmlQualifiedName("http://schemas.microsoft.com/office/2020/mipLabelMetadata", "CT_ClassificationLabel");
    }

    ExyokiOffice::OpenXml::FileFormatVersions GetVersion() const noexcept override
    {
        return ExyokiOffice::OpenXml::FileFormatVersions::Office2021;
    }

    std::span<const ExyokiOffice::OpenXmlAttribute> GetAttributes() const noexcept override
    {
        static constexpr std::array<ExyokiOffice::OpenXmlAttribute, 9> kAttributes = {
            ExyokiOffice::OpenXmlAttribute(ExyokiOffice::OpenXmlQualifiedName("", "id"), "StringValue", ExyokiOffice::OpenXml::FileFormatVersions::Office2021, "id"),
            ExyokiOffice::OpenXmlAttribute(ExyokiOffice::OpenXmlQualifiedName("", "enabled"), "BooleanValue", ExyokiOffice::OpenXml::FileFormatVersions::Office2021, "enabled"),
            ExyokiOffice::OpenXmlAttribute(ExyokiOffice::OpenXmlQualifiedName("", "setDate"), "StringValue", ExyokiOffice::OpenXml::FileFormatVersions::Office2021, "setDate"),
            ExyokiOffice::OpenXmlAttribute(ExyokiOffice::OpenXmlQualifiedName("", "method"), "StringValue", ExyokiOffice::OpenXml::FileFormatVersions::Office2021, "method"),
            ExyokiOffice::OpenXmlAttribute(ExyokiOffice::OpenXmlQualifiedName("", "name"), "StringValue", ExyokiOffice::OpenXml::FileFormatVersions::Office2021, "name"),
            ExyokiOffice::OpenXmlAttribute(ExyokiOffice::OpenXmlQualifiedName("", "siteId"), "StringValue", ExyokiOffice::OpenXml::FileFormatVersions::Office2021, "siteId"),
            ExyokiOffice::OpenXmlAttribute(ExyokiOffice::OpenXmlQualifiedName("", "actionId"), "StringValue", ExyokiOffice::OpenXml::FileFormatVersions::Office2021, "actionId"),
            ExyokiOffice::OpenXmlAttribute(ExyokiOffice::OpenXmlQualifiedName("", "contentBits"), "UInt32Value", ExyokiOffice::OpenXml::FileFormatVersions::Office2021, "contentBits"),
            ExyokiOffice::OpenXmlAttribute(ExyokiOffice::OpenXmlQualifiedName("", "removed"), "BooleanValue", ExyokiOffice::OpenXml::FileFormatVersions::Office2021, "removed"),
        };
        return kAttributes;
    }

    ExyokiOffice::OpenXmlElementClassFlags GetFlags() const noexcept override
    {
        return ExyokiOffice::OpenXmlElementClassFlags{ExyokiOffice::OpenXmlElementClassFlag::IsLeafElement};
    }

    std::shared_ptr<ExyokiOffice::OpenXMLElement> Create() const override
    {
        return std::make_shared<ClassificationLabel>();
    }

    void ConfigureMetadata(ExyokiOffice::MetadataBuilder& builder) const override
    {
        builder.SetSchemaName("schemas_microsoft_com_office_2020_mipLabelMetadata.json");
        builder.SetAvailability(ExyokiOffice::OpenXml::FileFormatVersions::Office2021);
        auto& metadataAttribute0 = builder.AddAttribute(ExyokiOffice::OpenXmlQualifiedName("", "id"), "Id", "StringValue", ExyokiOffice::OpenXml::FileFormatVersions::Office2021, "id");
        metadataAttribute0.Validators.push_back(std::make_shared<ExyokiOffice::MetadataRequiredConstraint>(ExyokiOffice::OpenXmlQualifiedName("", "id"), "Id", true));
        auto& metadataAttribute1 = builder.AddAttribute(ExyokiOffice::OpenXmlQualifiedName("", "enabled"), "Enabled", "BooleanValue", ExyokiOffice::OpenXml::FileFormatVersions::Office2021, "enabled");
        metadataAttribute1.Validators.push_back(std::make_shared<ExyokiOffice::MetadataRequiredConstraint>(ExyokiOffice::OpenXmlQualifiedName("", "enabled"), "Enabled", true));
        auto& metadataAttribute2 = builder.AddAttribute(ExyokiOffice::OpenXmlQualifiedName("", "setDate"), "SetDate", "StringValue", ExyokiOffice::OpenXml::FileFormatVersions::Office2021, "setDate");
        auto& metadataAttribute3 = builder.AddAttribute(ExyokiOffice::OpenXmlQualifiedName("", "method"), "Method", "StringValue", ExyokiOffice::OpenXml::FileFormatVersions::Office2021, "method");
        metadataAttribute3.Validators.push_back(std::make_shared<ExyokiOffice::MetadataRequiredConstraint>(ExyokiOffice::OpenXmlQualifiedName("", "method"), "Method", true));
        auto& metadataAttribute4 = builder.AddAttribute(ExyokiOffice::OpenXmlQualifiedName("", "name"), "Name", "StringValue", ExyokiOffice::OpenXml::FileFormatVersions::Office2021, "name");
        auto& metadataAttribute5 = builder.AddAttribute(ExyokiOffice::OpenXmlQualifiedName("", "siteId"), "SiteId", "StringValue", ExyokiOffice::OpenXml::FileFormatVersions::Office2021, "siteId");
        metadataAttribute5.Validators.push_back(std::make_shared<ExyokiOffice::MetadataRequiredConstraint>(ExyokiOffice::OpenXmlQualifiedName("", "siteId"), "SiteId", true));
        metadataAttribute5.Validators.push_back(std::make_shared<ExyokiOffice::MetadataStringConstraint>(ExyokiOffice::OpenXmlQualifiedName("", "siteId"), "SiteId", std::optional<ExyokiOffice::Size>{}, std::optional<ExyokiOffice::Size>{}, std::optional<ExyokiOffice::Size>{}, std::optional<std::string>{std::string("\\{[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}\\}")}, true, false, false, false, false));
        auto& metadataAttribute6 = builder.AddAttribute(ExyokiOffice::OpenXmlQualifiedName("", "actionId"), "ActionId", "StringValue", ExyokiOffice::OpenXml::FileFormatVersions::Office2021, "actionId");
        auto& metadataAttribute7 = builder.AddAttribute(ExyokiOffice::OpenXmlQualifiedName("", "contentBits"), "ContentBits", "UInt32Value", ExyokiOffice::OpenXml::FileFormatVersions::Office2021, "contentBits");
        auto& metadataAttribute8 = builder.AddAttribute(ExyokiOffice::OpenXmlQualifiedName("", "removed"), "Removed", "BooleanValue", ExyokiOffice::OpenXml::FileFormatVersions::Office2021, "removed");
        metadataAttribute8.Validators.push_back(std::make_shared<ExyokiOffice::MetadataRequiredConstraint>(ExyokiOffice::OpenXmlQualifiedName("", "removed"), "Removed", true));
    }
};
} // namespace

const ExyokiOffice::OpenXMLElementClass* ClassificationLabel::StaticMetaClass() noexcept
{
    static const ClassificationLabelMetaClass kMeta{};
    return &kMeta;
}

const ExyokiOffice::OpenXMLElementClass* ClassificationLabel::ElementMetaClass() const noexcept
{
    return ClassificationLabel::StaticMetaClass();
}

StringValue ClassificationLabel::GetId() const
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "id"));
    return GetAttributeValue<StringValue>(kAttribute);
}

void ClassificationLabel::SetId(const StringValue& value)
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "id"));
    SetAttributeValue(kAttribute, value);
}

BooleanValue ClassificationLabel::GetEnabled() const
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "enabled"));
    return GetAttributeValue<BooleanValue>(kAttribute);
}

void ClassificationLabel::SetEnabled(const BooleanValue& value)
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "enabled"));
    SetAttributeValue(kAttribute, value);
}

StringValue ClassificationLabel::GetSetDate() const
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "setDate"));
    return GetAttributeValue<StringValue>(kAttribute);
}

void ClassificationLabel::SetSetDate(const StringValue& value)
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "setDate"));
    SetAttributeValue(kAttribute, value);
}

StringValue ClassificationLabel::GetMethod() const
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "method"));
    return GetAttributeValue<StringValue>(kAttribute);
}

void ClassificationLabel::SetMethod(const StringValue& value)
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "method"));
    SetAttributeValue(kAttribute, value);
}

StringValue ClassificationLabel::GetName() const
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "name"));
    return GetAttributeValue<StringValue>(kAttribute);
}

void ClassificationLabel::SetName(const StringValue& value)
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "name"));
    SetAttributeValue(kAttribute, value);
}

StringValue ClassificationLabel::GetSiteId() const
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "siteId"));
    return GetAttributeValue<StringValue>(kAttribute);
}

void ClassificationLabel::SetSiteId(const StringValue& value)
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "siteId"));
    SetAttributeValue(kAttribute, value);
}

StringValue ClassificationLabel::GetActionId() const
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "actionId"));
    return GetAttributeValue<StringValue>(kAttribute);
}

void ClassificationLabel::SetActionId(const StringValue& value)
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "actionId"));
    SetAttributeValue(kAttribute, value);
}

UInt32Value ClassificationLabel::GetContentBits() const
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "contentBits"));
    return GetAttributeValue<UInt32Value>(kAttribute);
}

void ClassificationLabel::SetContentBits(const UInt32Value& value)
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "contentBits"));
    SetAttributeValue(kAttribute, value);
}

BooleanValue ClassificationLabel::GetRemoved() const
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "removed"));
    return GetAttributeValue<BooleanValue>(kAttribute);
}

void ClassificationLabel::SetRemoved(const BooleanValue& value)
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "removed"));
    SetAttributeValue(kAttribute, value);
}

ExyokiOffice::MetadataParticlePtr CreateClassificationExtensionParticleMetadata()
{
    auto particleNode0 = std::make_shared<ExyokiOffice::MetadataSequenceParticle>(0, std::optional<ExyokiOffice::UInt32>{1}, ExyokiOffice::OpenXml::FileFormatVersions::Office2007, false);
    auto particleNode1 = std::make_shared<ExyokiOffice::MetadataAnyParticle>("", 0, std::optional<ExyokiOffice::UInt32>{1}, ExyokiOffice::OpenXml::FileFormatVersions::Office2007);
    particleNode0->AddChild(particleNode1);
    return particleNode0;
}

namespace {
class ClassificationExtensionMetaClass final : public ExyokiOffice::OpenXMLElementClass
{
public:
    const ExyokiOffice::OpenXMLElementClass* GetBaseMetaClass() const noexcept override
    {
        return OpenXmlCompositeElement::StaticMetaClass();
    }

    ExyokiOffice::OpenXmlQualifiedName QualifiedName() const noexcept override
    {
        return ExyokiOffice::OpenXmlQualifiedName("http://schemas.microsoft.com/office/2020/mipLabelMetadata", "ext");
    }

    ExyokiOffice::OpenXmlQualifiedName TypeQualifiedName() const noexcept override
    {
        return ExyokiOffice::OpenXmlQualifiedName("http://schemas.microsoft.com/office/2020/mipLabelMetadata", "CT_ClassificationExtension");
    }

    ExyokiOffice::OpenXml::FileFormatVersions GetVersion() const noexcept override
    {
        return ExyokiOffice::OpenXml::FileFormatVersions::Office2021;
    }

    std::span<const ExyokiOffice::OpenXmlAttribute> GetAttributes() const noexcept override
    {
        static constexpr std::array<ExyokiOffice::OpenXmlAttribute, 1> kAttributes = {
            ExyokiOffice::OpenXmlAttribute(ExyokiOffice::OpenXmlQualifiedName("", "uri"), "StringValue", ExyokiOffice::OpenXml::FileFormatVersions::Office2021, "uri"),
        };
        return kAttributes;
    }

    ExyokiOffice::OpenXmlElementClassFlags GetFlags() const noexcept override
    {
        return ExyokiOffice::OpenXmlElementClassFlags{};
    }

    std::shared_ptr<ExyokiOffice::OpenXMLElement> Create() const override
    {
        return std::make_shared<ClassificationExtension>();
    }

    void ConfigureMetadata(ExyokiOffice::MetadataBuilder& builder) const override
    {
        builder.SetSchemaName("schemas_microsoft_com_office_2020_mipLabelMetadata.json");
        builder.SetAvailability(ExyokiOffice::OpenXml::FileFormatVersions::Office2021);
        auto& metadataAttribute0 = builder.AddAttribute(ExyokiOffice::OpenXmlQualifiedName("", "uri"), "Uri", "StringValue", ExyokiOffice::OpenXml::FileFormatVersions::Office2021, "uri");
        metadataAttribute0.Validators.push_back(std::make_shared<ExyokiOffice::MetadataRequiredConstraint>(ExyokiOffice::OpenXmlQualifiedName("", "uri"), "Uri", true));
        metadataAttribute0.Validators.push_back(std::make_shared<ExyokiOffice::MetadataStringConstraint>(ExyokiOffice::OpenXmlQualifiedName("", "uri"), "Uri", std::optional<ExyokiOffice::Size>{}, std::optional<ExyokiOffice::Size>{}, std::optional<ExyokiOffice::Size>{}, std::optional<std::string>{}, true, false, false, false, false));
        builder.SetParticleTree(CreateClassificationExtensionParticleMetadata());
    }
};
} // namespace

const ExyokiOffice::OpenXMLElementClass* ClassificationExtension::StaticMetaClass() noexcept
{
    static const ClassificationExtensionMetaClass kMeta{};
    return &kMeta;
}

const ExyokiOffice::OpenXMLElementClass* ClassificationExtension::ElementMetaClass() const noexcept
{
    return ClassificationExtension::StaticMetaClass();
}

StringValue ClassificationExtension::GetUri() const
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "uri"));
    return GetAttributeValue<StringValue>(kAttribute);
}

void ClassificationExtension::SetUri(const StringValue& value)
{
    constexpr ExyokiOffice::OpenXmlQualifiedName kAttribute(ExyokiOffice::OpenXmlQualifiedName("", "uri"));
    SetAttributeValue(kAttribute, value);
}

ExyokiOffice::MetadataParticlePtr CreateClassificationLabelListParticleMetadata()
{
    auto particleNode0 = std::make_shared<ExyokiOffice::MetadataSequenceParticle>(0, std::optional<ExyokiOffice::UInt32>{1}, ExyokiOffice::OpenXml::FileFormatVersions::Office2007, false);
    auto particleNode1 = std::make_shared<ExyokiOffice::MetadataElementParticle>(ExyokiOffice::OpenXmlQualifiedName("http://schemas.microsoft.com/office/2020/mipLabelMetadata", "label"), "ExyokiOffice::DocumentFormat::OpenXml::Office2021::MipLabelMetaData::ClassificationLabel", "CT_ClassificationLabel/clbl:label", 0, std::optional<ExyokiOffice::UInt32>{}, ExyokiOffice::OpenXml::FileFormatVersions::Office2021);
    particleNode0->AddChild(particleNode1);
    auto particleNode2 = std::make_shared<ExyokiOffice::MetadataElementParticle>(ExyokiOffice::OpenXmlQualifiedName("http://schemas.microsoft.com/office/2020/mipLabelMetadata", "extLst"), "ExyokiOffice::DocumentFormat::OpenXml::Office2021::MipLabelMetaData::ClassificationExtensionList", "CT_ClassificationExtensionList/clbl:extLst", 0, std::optional<ExyokiOffice::UInt32>{1}, ExyokiOffice::OpenXml::FileFormatVersions::Office2021);
    particleNode0->AddChild(particleNode2);
    return particleNode0;
}

namespace {
class ClassificationLabelListMetaClass final : public ExyokiOffice::OpenXMLElementClass
{
public:
    const ExyokiOffice::OpenXMLElementClass* GetBaseMetaClass() const noexcept override
    {
        return OpenXmlCompositeElement::StaticMetaClass();
    }

    ExyokiOffice::OpenXmlQualifiedName QualifiedName() const noexcept override
    {
        return ExyokiOffice::OpenXmlQualifiedName("http://schemas.microsoft.com/office/2020/mipLabelMetadata", "labelList");
    }

    ExyokiOffice::OpenXmlQualifiedName TypeQualifiedName() const noexcept override
    {
        return ExyokiOffice::OpenXmlQualifiedName("http://schemas.microsoft.com/office/2020/mipLabelMetadata", "CT_ClassificationLabelList");
    }

    ExyokiOffice::OpenXml::FileFormatVersions GetVersion() const noexcept override
    {
        return ExyokiOffice::OpenXml::FileFormatVersions::Office2021;
    }

    ExyokiOffice::OpenXmlElementClassFlags GetFlags() const noexcept override
    {
        return ExyokiOffice::OpenXmlElementClassFlags{};
    }

    std::shared_ptr<ExyokiOffice::OpenXMLElement> Create() const override
    {
        return std::make_shared<ClassificationLabelList>();
    }

    void ConfigureMetadata(ExyokiOffice::MetadataBuilder& builder) const override
    {
        builder.SetSchemaName("schemas_microsoft_com_office_2020_mipLabelMetadata.json");
        builder.SetAvailability(ExyokiOffice::OpenXml::FileFormatVersions::Office2021);
        builder.SetParticleTree(CreateClassificationLabelListParticleMetadata());
    }
};
} // namespace

const ExyokiOffice::OpenXMLElementClass* ClassificationLabelList::StaticMetaClass() noexcept
{
    static const ClassificationLabelListMetaClass kMeta{};
    return &kMeta;
}

const ExyokiOffice::OpenXMLElementClass* ClassificationLabelList::ElementMetaClass() const noexcept
{
    return ClassificationLabelList::StaticMetaClass();
}

} // namespace MipLabelMetaData
} // namespace Office2021
} // namespace OpenXml
} // namespace DocumentFormat
} // namespace ExyokiOffice
