// Copyright (c) 2026 Jakub Melka and Contributors
// SPDX-License-Identifier: MIT
// See LICENSE file in the project root for full license text.
//
// Derived from the Open-XML-SDK metadata under data/, which is
// Copyright (c) .NET Foundation and Contributors and MIT-licensed.
// See data/LICENSE and THIRD-PARTY-LICENSES.md in the project root.
// -----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by ExyokiOffice OpenXML generator.
//     Manual changes to this file may cause unexpected behaviour.
// </auto-generated>
// -----------------------------------------------------------------------------

#pragma once

#include "ExyokiOffice/OpenXMLElement.hpp"

namespace ExyokiOffice {
namespace DocumentFormat {
namespace OpenXml {
namespace Office2016 {
namespace Drawing {
namespace ChartDrawing {


/// \brief Represents the FormulaDirection class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office2016.Drawing.ChartDrawing
/// Type QName: cx:ST_FormulaDirection
/// Element QName: (none)
/// Source: schemas_microsoft_com_office_drawing_2014_chartex.json
class FormulaDirection : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        col, 
        row, 
    };

    constexpr FormulaDirection() noexcept = default;
    constexpr FormulaDirection(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Represents the StringDimensionType class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office2016.Drawing.ChartDrawing
/// Type QName: cx:ST_StringDimensionType
/// Element QName: (none)
/// Source: schemas_microsoft_com_office_drawing_2014_chartex.json
class StringDimensionType : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        cat, 
        colorStr, 
        entityId, 
    };

    constexpr StringDimensionType() noexcept = default;
    constexpr StringDimensionType(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Represents the NumericDimensionType class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office2016.Drawing.ChartDrawing
/// Type QName: cx:ST_NumericDimensionType
/// Element QName: (none)
/// Source: schemas_microsoft_com_office_drawing_2014_chartex.json
class NumericDimensionType : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        val, 
        x, 
        y, 
        size, 
        colorVal, 
    };

    constexpr NumericDimensionType() noexcept = default;
    constexpr NumericDimensionType(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Represents the SidePos class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office2016.Drawing.ChartDrawing
/// Type QName: cx:ST_SidePos
/// Element QName: (none)
/// Source: schemas_microsoft_com_office_drawing_2014_chartex.json
class SidePos : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        l, 
        t, 
        r, 
        b, 
    };

    constexpr SidePos() noexcept = default;
    constexpr SidePos(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Represents the PosAlign class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office2016.Drawing.ChartDrawing
/// Type QName: cx:ST_PosAlign
/// Element QName: (none)
/// Source: schemas_microsoft_com_office_drawing_2014_chartex.json
class PosAlign : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        min, 
        ctr, 
        max, 
    };

    constexpr PosAlign() noexcept = default;
    constexpr PosAlign(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Represents the AxisUnit class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office2016.Drawing.ChartDrawing
/// Type QName: cx:ST_AxisUnit
/// Element QName: (none)
/// Source: schemas_microsoft_com_office_drawing_2014_chartex.json
class AxisUnit : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        hundreds, 
        thousands, 
        tenThousands, 
        hundredThousands, 
        millions, 
        tenMillions, 
        hundredMillions, 
        billions, 
        trillions, 
        percentage, 
    };

    constexpr AxisUnit() noexcept = default;
    constexpr AxisUnit(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Represents the TickMarksType class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office2016.Drawing.ChartDrawing
/// Type QName: cx:ST_TickMarksType
/// Element QName: (none)
/// Source: schemas_microsoft_com_office_drawing_2014_chartex.json
class TickMarksType : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        in, 
        out, 
        cross, 
        none, 
    };

    constexpr TickMarksType() noexcept = default;
    constexpr TickMarksType(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Represents the SeriesLayout class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office2016.Drawing.ChartDrawing
/// Type QName: cx:ST_SeriesLayout
/// Element QName: (none)
/// Source: schemas_microsoft_com_office_drawing_2014_chartex.json
class SeriesLayout : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        boxWhisker, 
        clusteredColumn, 
        funnel, 
        paretoLine, 
        regionMap, 
        sunburst, 
        treemap, 
        waterfall, 
    };

    constexpr SeriesLayout() noexcept = default;
    constexpr SeriesLayout(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Represents the ParentLabelLayoutVal class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office2016.Drawing.ChartDrawing
/// Type QName: cx:ST_ParentLabelLayout
/// Element QName: (none)
/// Source: schemas_microsoft_com_office_drawing_2014_chartex.json
class ParentLabelLayoutVal : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        none, 
        banner, 
        overlapping, 
    };

    constexpr ParentLabelLayoutVal() noexcept = default;
    constexpr ParentLabelLayoutVal(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Represents the RegionLabelLayoutEnum class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office2016.Drawing.ChartDrawing
/// Type QName: cx:ST_RegionLabelLayout
/// Element QName: (none)
/// Source: schemas_microsoft_com_office_drawing_2014_chartex.json
class RegionLabelLayoutEnum : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        none, 
        bestFitOnly, 
        showAll, 
    };

    constexpr RegionLabelLayoutEnum() noexcept = default;
    constexpr RegionLabelLayoutEnum(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Represents the IntervalClosedSide class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office2016.Drawing.ChartDrawing
/// Type QName: cx:ST_IntervalClosedSide
/// Element QName: (none)
/// Source: schemas_microsoft_com_office_drawing_2014_chartex.json
class IntervalClosedSide : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        l, 
        r, 
    };

    constexpr IntervalClosedSide() noexcept = default;
    constexpr IntervalClosedSide(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Represents the EntityTypeEnum class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office2016.Drawing.ChartDrawing
/// Type QName: cx:ST_EntityType
/// Element QName: (none)
/// Source: schemas_microsoft_com_office_drawing_2014_chartex.json
class EntityTypeEnum : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        Address, 
        AdminDistrict, 
        AdminDistrict2, 
        AdminDistrict3, 
        Continent, 
        CountryRegion, 
        Locality, 
        Ocean, 
        Planet, 
        PostalCode, 
        Region, 
        Unsupported, 
    };

    constexpr EntityTypeEnum() noexcept = default;
    constexpr EntityTypeEnum(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Represents the GeoProjectionType class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office2016.Drawing.ChartDrawing
/// Type QName: cx:ST_GeoProjectionType
/// Element QName: (none)
/// Source: schemas_microsoft_com_office_drawing_2014_chartex.json
class GeoProjectionType : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        mercator, 
        miller, 
        robinson, 
        albers, 
    };

    constexpr GeoProjectionType() noexcept = default;
    constexpr GeoProjectionType(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Represents the GeoMappingLevel class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office2016.Drawing.ChartDrawing
/// Type QName: cx:ST_GeoMappingLevel
/// Element QName: (none)
/// Source: schemas_microsoft_com_office_drawing_2014_chartex.json
class GeoMappingLevel : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        dataOnly, 
        postalCode, 
        county, 
        state, 
        countryRegion, 
        countryRegionList, 
        world, 
    };

    constexpr GeoMappingLevel() noexcept = default;
    constexpr GeoMappingLevel(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Represents the QuartileMethod class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office2016.Drawing.ChartDrawing
/// Type QName: cx:ST_QuartileMethod
/// Element QName: (none)
/// Source: schemas_microsoft_com_office_drawing_2014_chartex.json
class QuartileMethod : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        inclusive, 
        exclusive, 
    };

    constexpr QuartileMethod() noexcept = default;
    constexpr QuartileMethod(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Represents the DataLabelPos class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office2016.Drawing.ChartDrawing
/// Type QName: cx:ST_DataLabelPos
/// Element QName: (none)
/// Source: schemas_microsoft_com_office_drawing_2014_chartex.json
class DataLabelPos : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        bestFit, 
        b, 
        ctr, 
        inBase, 
        inEnd, 
        l, 
        outEnd, 
        r, 
        t, 
    };

    constexpr DataLabelPos() noexcept = default;
    constexpr DataLabelPos(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

/// \brief Represents the PageOrientation class.
///
/// Namespace: ExyokiOffice.DocumentFormat.OpenXml.Office2016.Drawing.ChartDrawing
/// Type QName: cx:ST_PageOrientation
/// Element QName: (none)
/// Source: schemas_microsoft_com_office_drawing_2014_chartex.json
class PageOrientation : public ExyokiOffice::OpenXmlEnum
{
public:
    enum Value
    {
        NotDefinedEnumValue = 0,
        InvalidEnumValue,
        default_, 
        portrait, 
        landscape, 
    };

    constexpr PageOrientation() noexcept = default;
    constexpr PageOrientation(Value value) noexcept : m_value(value) {}

    constexpr operator Value() const noexcept { return m_value; }
    constexpr bool IsValid() const noexcept { return m_value != NotDefinedEnumValue && m_value != InvalidEnumValue; }
    constexpr bool isUndefined() const noexcept { return m_value == NotDefinedEnumValue; }
    constexpr bool isInvalid() const noexcept { return m_value == InvalidEnumValue; }

    constexpr Value GetValue() const noexcept { return m_value; }
    void SetValue(Value value) noexcept { m_value = value; }

    static EXYOKIOFFICE_EXPORT const ExyokiOffice::OpenXmlMetaEnum* GetMetaEnum() noexcept;

private:
    Value m_value = NotDefinedEnumValue;
};

} // namespace ChartDrawing
} // namespace Drawing
} // namespace Office2016
} // namespace OpenXml
} // namespace DocumentFormat
} // namespace ExyokiOffice
