// Copyright (c) 2026 Jakub Melka and Collaborators
// SPDX-License-Identifier: MIT
// See LICENSE file in the project root for full license text.
// -----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by ExyokiOffice OpenXML generator.
//     Manual changes to this file may cause unexpected behaviour.
// </auto-generated>
// -----------------------------------------------------------------------------

#include "doctest.h"

#include "DomTestSupport.hpp"

#include "ExyokiOffice/DOM/DocumentFormat/OpenXml/Office/SpreadSheetML/Y2022/PivotVersionInfo.hpp"
#include "ExyokiOffice/StandardTypes.hpp"

#include <cstdint>
#include <string_view>
#include <vector>

namespace EoNs = ExyokiOffice::DocumentFormat::OpenXml::Office::SpreadSheetML::Y2022::PivotVersionInfo;

TEST_SUITE("DocumentFormat.OpenXml.Office.SpreadSheetML.Y2022.PivotVersionInfo.DomGeneratedTests")
{
    TEST_CASE("LastUpdateFeatureXsdstring typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::LastUpdateFeatureXsdstring>();
        REQUIRE(hosted.element != nullptr);
    }

    TEST_CASE("LastRefreshFeatureXsdstring typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::LastRefreshFeatureXsdstring>();
        REQUIRE(hosted.element != nullptr);
    }

    TEST_CASE("RequiredFeatureXsdstring typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::RequiredFeatureXsdstring>();
        REQUIRE(hosted.element != nullptr);
    }

    TEST_CASE("PivotVersionInfo typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::PivotVersionInfo>();
        REQUIRE(hosted.element != nullptr);
    }

    TEST_CASE("CacheVersionInfo typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::CacheVersionInfo>();
        REQUIRE(hosted.element != nullptr);
    }

}
