// Copyright (c) 2026 Jakub Melka and Contributors
// SPDX-License-Identifier: MIT
// See LICENSE file in the project root for full license text.
//
// Derived from the Open-XML-SDK metadata under data/, which is
// Copyright (c) .NET Foundation and Contributors and MIT-licensed.
// See data/LICENSE and THIRD-PARTY-LICENSES.md in the project root.
// -----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by ExyokiOffice OpenXML generator.
//     Manual changes to this file may cause unexpected behaviour.
// </auto-generated>
// -----------------------------------------------------------------------------

#include "doctest.h"

#include "DomTestSupport.hpp"

#include "ExyokiOffice/DOM/DocumentFormat/OpenXml/Office/Drawing/Y2021/OEmbed.hpp"
#include "ExyokiOffice/StandardTypes.hpp"

#include <cstdint>
#include <string_view>
#include <vector>

namespace EoNs = ExyokiOffice::DocumentFormat::OpenXml::Office::Drawing::Y2021::OEmbed;

TEST_SUITE("DocumentFormat.OpenXml.Office.Drawing.Y2021.OEmbed.DomGeneratedTests")
{
    TEST_CASE("OfficeArtExtensionList typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::OfficeArtExtensionList>();
        REQUIRE(hosted.element != nullptr);
    }

    TEST_CASE("OEmbedShared typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::OEmbedShared>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetSrcUrl(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetSrcUrl().IsDefined());
        hosted.element->SetType(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetType().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::StringValue sampleSrcUrl = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetSrcUrl(sampleSrcUrl);
        CHECK(hosted.element->GetSrcUrl() == sampleSrcUrl);
        const ExyokiOffice::StringValue sampleType = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetType(sampleType);
        CHECK(hosted.element->GetType() == sampleType);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetSrcUrl() == sampleSrcUrl);
        CHECK(reloaded.element->GetType() == sampleType);
    }

}
