// Copyright (c) 2026 Jakub Melka and Collaborators
// SPDX-License-Identifier: MIT
// See LICENSE file in the project root for full license text.
// -----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by ExyokiOffice OpenXML generator.
//     Manual changes to this file may cause unexpected behaviour.
// </auto-generated>
// -----------------------------------------------------------------------------

#include "doctest.h"

#include "DomTestSupport.hpp"

#include "ExyokiOffice/DOM/DocumentFormat/OpenXml/Office/Y2022/RichValueRel.hpp"
#include "ExyokiOffice/StandardTypes.hpp"

#include <cstdint>
#include <string_view>
#include <vector>

namespace EoNs = ExyokiOffice::DocumentFormat::OpenXml::Office::Y2022::RichValueRel;

TEST_SUITE("DocumentFormat.OpenXml.Office.Y2022.RichValueRel.DomGeneratedTests")
{
    TEST_CASE("ExtensionList typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::ExtensionList>();
        REQUIRE(hosted.element != nullptr);
    }

    TEST_CASE("RichValueRelRelationship typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::RichValueRelRelationship>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetId(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetId().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::StringValue sampleId = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetId(sampleId);
        CHECK(hosted.element->GetId() == sampleId);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetId() == sampleId);
    }

    TEST_CASE("RichValueRels typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::RichValueRels>();
        REQUIRE(hosted.element != nullptr);
    }

}
