// Copyright (c) 2026 Jakub Melka and Collaborators
// SPDX-License-Identifier: MIT
// See LICENSE file in the project root for full license text.
// -----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by ExyokiOffice OpenXML generator.
//     Manual changes to this file may cause unexpected behaviour.
// </auto-generated>
// -----------------------------------------------------------------------------

#include "doctest.h"

#include "DomTestSupport.hpp"

#include "ExyokiOffice/DOM/DocumentFormat/OpenXml/Office2013/Excel.hpp"
#include "ExyokiOffice/StandardTypes.hpp"

#include <cstdint>
#include <string_view>
#include <vector>

namespace EoNs = ExyokiOffice::DocumentFormat::OpenXml::Office2013::Excel;

TEST_SUITE("DocumentFormat.OpenXml.Office2013.Excel.DomGeneratedTests")
{
    TEST_CASE("PivotRow typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::PivotRow>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetReference(ExyokiOffice::UInt32Value{});
        CHECK_FALSE(hosted.element->GetReference().IsDefined());
        hosted.element->SetCount(ExyokiOffice::UInt32Value{});
        CHECK_FALSE(hosted.element->GetCount().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::UInt32Value sampleReference = ExyokiOffice::UInt32Value(static_cast<ExyokiOffice::UInt32>(1));
        hosted.element->SetReference(sampleReference);
        CHECK(hosted.element->GetReference() == sampleReference);
        const ExyokiOffice::UInt32Value sampleCount = ExyokiOffice::UInt32Value(static_cast<ExyokiOffice::UInt32>(1));
        hosted.element->SetCount(sampleCount);
        CHECK(hosted.element->GetCount() == sampleCount);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetReference() == sampleReference);
        CHECK(reloaded.element->GetCount() == sampleCount);
    }

    TEST_CASE("TimelineState typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::TimelineState>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetSingleRangeFilterState(ExyokiOffice::BooleanValue{});
        CHECK_FALSE(hosted.element->GetSingleRangeFilterState().IsDefined());
        hosted.element->SetMinimalRefreshVersion(ExyokiOffice::UInt32Value{});
        CHECK_FALSE(hosted.element->GetMinimalRefreshVersion().IsDefined());
        hosted.element->SetLastRefreshVersion(ExyokiOffice::UInt32Value{});
        CHECK_FALSE(hosted.element->GetLastRefreshVersion().IsDefined());
        hosted.element->SetPivotCacheId(ExyokiOffice::UInt32Value{});
        CHECK_FALSE(hosted.element->GetPivotCacheId().IsDefined());
        hosted.element->SetFilterType(ExyokiOffice::EnumValue<ExyokiOffice::DocumentFormat::OpenXml::Spreadsheet::PivotFilterValues>{});
        CHECK_FALSE(hosted.element->GetFilterType().IsDefined());
        hosted.element->SetFilterId(ExyokiOffice::UInt32Value{});
        CHECK_FALSE(hosted.element->GetFilterId().IsDefined());
        hosted.element->SetFilterTabId(ExyokiOffice::UInt32Value{});
        CHECK_FALSE(hosted.element->GetFilterTabId().IsDefined());
        hosted.element->SetFilterPivotName(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetFilterPivotName().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::BooleanValue sampleSingleRangeFilterState = ExyokiOffice::BooleanValue(true);
        hosted.element->SetSingleRangeFilterState(sampleSingleRangeFilterState);
        CHECK(hosted.element->GetSingleRangeFilterState() == sampleSingleRangeFilterState);
        const ExyokiOffice::UInt32Value sampleMinimalRefreshVersion = ExyokiOffice::UInt32Value(static_cast<ExyokiOffice::UInt32>(1));
        hosted.element->SetMinimalRefreshVersion(sampleMinimalRefreshVersion);
        CHECK(hosted.element->GetMinimalRefreshVersion() == sampleMinimalRefreshVersion);
        const ExyokiOffice::UInt32Value sampleLastRefreshVersion = ExyokiOffice::UInt32Value(static_cast<ExyokiOffice::UInt32>(1));
        hosted.element->SetLastRefreshVersion(sampleLastRefreshVersion);
        CHECK(hosted.element->GetLastRefreshVersion() == sampleLastRefreshVersion);
        const ExyokiOffice::UInt32Value samplePivotCacheId = ExyokiOffice::UInt32Value(static_cast<ExyokiOffice::UInt32>(1));
        hosted.element->SetPivotCacheId(samplePivotCacheId);
        CHECK(hosted.element->GetPivotCacheId() == samplePivotCacheId);
        const ExyokiOffice::EnumValue<ExyokiOffice::DocumentFormat::OpenXml::Spreadsheet::PivotFilterValues> sampleFilterType = ExyokiOffice::EnumValue<ExyokiOffice::DocumentFormat::OpenXml::Spreadsheet::PivotFilterValues>(ExyokiOffice::DocumentFormat::OpenXml::Spreadsheet::PivotFilterValues::Unknown);
        hosted.element->SetFilterType(sampleFilterType);
        CHECK(hosted.element->GetFilterType() == sampleFilterType);
        const ExyokiOffice::UInt32Value sampleFilterId = ExyokiOffice::UInt32Value(static_cast<ExyokiOffice::UInt32>(1));
        hosted.element->SetFilterId(sampleFilterId);
        CHECK(hosted.element->GetFilterId() == sampleFilterId);
        const ExyokiOffice::UInt32Value sampleFilterTabId = ExyokiOffice::UInt32Value(static_cast<ExyokiOffice::UInt32>(1));
        hosted.element->SetFilterTabId(sampleFilterTabId);
        CHECK(hosted.element->GetFilterTabId() == sampleFilterTabId);
        const ExyokiOffice::StringValue sampleFilterPivotName = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetFilterPivotName(sampleFilterPivotName);
        CHECK(hosted.element->GetFilterPivotName() == sampleFilterPivotName);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetSingleRangeFilterState() == sampleSingleRangeFilterState);
        CHECK(reloaded.element->GetMinimalRefreshVersion() == sampleMinimalRefreshVersion);
        CHECK(reloaded.element->GetLastRefreshVersion() == sampleLastRefreshVersion);
        CHECK(reloaded.element->GetPivotCacheId() == samplePivotCacheId);
        CHECK(reloaded.element->GetFilterType() == sampleFilterType);
        CHECK(reloaded.element->GetFilterId() == sampleFilterId);
        CHECK(reloaded.element->GetFilterTabId() == sampleFilterTabId);
        CHECK(reloaded.element->GetFilterPivotName() == sampleFilterPivotName);
    }

    TEST_CASE("TimelineCachePivotTables typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::TimelineCachePivotTables>();
        REQUIRE(hosted.element != nullptr);
    }

    TEST_CASE("AutoFilter typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::AutoFilter>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetReference(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetReference().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::StringValue sampleReference = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetReference(sampleReference);
        CHECK(hosted.element->GetReference() == sampleReference);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetReference() == sampleReference);
    }

    TEST_CASE("BoundsTimelineRange typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::BoundsTimelineRange>();
        REQUIRE(hosted.element != nullptr);
    }

    TEST_CASE("SelectionTimelineRange typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::SelectionTimelineRange>();
        REQUIRE(hosted.element != nullptr);
    }

    TEST_CASE("TimelineCachePivotTable typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::TimelineCachePivotTable>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetTabId(ExyokiOffice::UInt32Value{});
        CHECK_FALSE(hosted.element->GetTabId().IsDefined());
        hosted.element->SetName(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetName().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::UInt32Value sampleTabId = ExyokiOffice::UInt32Value(static_cast<ExyokiOffice::UInt32>(1));
        hosted.element->SetTabId(sampleTabId);
        CHECK(hosted.element->GetTabId() == sampleTabId);
        const ExyokiOffice::StringValue sampleName = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetName(sampleName);
        CHECK(hosted.element->GetName() == sampleName);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetTabId() == sampleTabId);
        CHECK(reloaded.element->GetName() == sampleName);
    }

    TEST_CASE("Timeline typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::Timeline>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetName(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetName().IsDefined());
        hosted.element->SetCache(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetCache().IsDefined());
        hosted.element->SetCaption(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetCaption().IsDefined());
        hosted.element->SetShowHeader(ExyokiOffice::BooleanValue{});
        CHECK_FALSE(hosted.element->GetShowHeader().IsDefined());
        hosted.element->SetShowSelectionLabel(ExyokiOffice::BooleanValue{});
        CHECK_FALSE(hosted.element->GetShowSelectionLabel().IsDefined());
        hosted.element->SetShowTimeLevel(ExyokiOffice::BooleanValue{});
        CHECK_FALSE(hosted.element->GetShowTimeLevel().IsDefined());
        hosted.element->SetShowHorizontalScrollbar(ExyokiOffice::BooleanValue{});
        CHECK_FALSE(hosted.element->GetShowHorizontalScrollbar().IsDefined());
        hosted.element->SetLevel(ExyokiOffice::UInt32Value{});
        CHECK_FALSE(hosted.element->GetLevel().IsDefined());
        hosted.element->SetSelectionLevel(ExyokiOffice::UInt32Value{});
        CHECK_FALSE(hosted.element->GetSelectionLevel().IsDefined());
        hosted.element->SetScrollPosition(ExyokiOffice::DateTimeValue{});
        CHECK_FALSE(hosted.element->GetScrollPosition().IsDefined());
        hosted.element->SetStyle(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetStyle().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::StringValue sampleName = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetName(sampleName);
        CHECK(hosted.element->GetName() == sampleName);
        const ExyokiOffice::StringValue sampleCache = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetCache(sampleCache);
        CHECK(hosted.element->GetCache() == sampleCache);
        const ExyokiOffice::StringValue sampleCaption = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetCaption(sampleCaption);
        CHECK(hosted.element->GetCaption() == sampleCaption);
        const ExyokiOffice::BooleanValue sampleShowHeader = ExyokiOffice::BooleanValue(true);
        hosted.element->SetShowHeader(sampleShowHeader);
        CHECK(hosted.element->GetShowHeader() == sampleShowHeader);
        const ExyokiOffice::BooleanValue sampleShowSelectionLabel = ExyokiOffice::BooleanValue(true);
        hosted.element->SetShowSelectionLabel(sampleShowSelectionLabel);
        CHECK(hosted.element->GetShowSelectionLabel() == sampleShowSelectionLabel);
        const ExyokiOffice::BooleanValue sampleShowTimeLevel = ExyokiOffice::BooleanValue(true);
        hosted.element->SetShowTimeLevel(sampleShowTimeLevel);
        CHECK(hosted.element->GetShowTimeLevel() == sampleShowTimeLevel);
        const ExyokiOffice::BooleanValue sampleShowHorizontalScrollbar = ExyokiOffice::BooleanValue(true);
        hosted.element->SetShowHorizontalScrollbar(sampleShowHorizontalScrollbar);
        CHECK(hosted.element->GetShowHorizontalScrollbar() == sampleShowHorizontalScrollbar);
        const ExyokiOffice::UInt32Value sampleLevel = ExyokiOffice::UInt32Value(static_cast<ExyokiOffice::UInt32>(1));
        hosted.element->SetLevel(sampleLevel);
        CHECK(hosted.element->GetLevel() == sampleLevel);
        const ExyokiOffice::UInt32Value sampleSelectionLevel = ExyokiOffice::UInt32Value(static_cast<ExyokiOffice::UInt32>(1));
        hosted.element->SetSelectionLevel(sampleSelectionLevel);
        CHECK(hosted.element->GetSelectionLevel() == sampleSelectionLevel);
        const ExyokiOffice::DateTimeValue sampleScrollPosition = ExyokiOffice::DateTimeValue(std::string_view("2020-01-01T00:00:00Z"));
        hosted.element->SetScrollPosition(sampleScrollPosition);
        CHECK(hosted.element->GetScrollPosition() == sampleScrollPosition);
        const ExyokiOffice::StringValue sampleStyle = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetStyle(sampleStyle);
        CHECK(hosted.element->GetStyle() == sampleStyle);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetName() == sampleName);
        CHECK(reloaded.element->GetCache() == sampleCache);
        CHECK(reloaded.element->GetCaption() == sampleCaption);
        CHECK(reloaded.element->GetShowHeader() == sampleShowHeader);
        CHECK(reloaded.element->GetShowSelectionLabel() == sampleShowSelectionLabel);
        CHECK(reloaded.element->GetShowTimeLevel() == sampleShowTimeLevel);
        CHECK(reloaded.element->GetShowHorizontalScrollbar() == sampleShowHorizontalScrollbar);
        CHECK(reloaded.element->GetLevel() == sampleLevel);
        CHECK(reloaded.element->GetSelectionLevel() == sampleSelectionLevel);
        CHECK(reloaded.element->GetScrollPosition() == sampleScrollPosition);
        CHECK(reloaded.element->GetStyle() == sampleStyle);
    }

    TEST_CASE("SurveyQuestion typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::SurveyQuestion>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetBinding(ExyokiOffice::UInt32Value{});
        CHECK_FALSE(hosted.element->GetBinding().IsDefined());
        hosted.element->SetText(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetText().IsDefined());
        hosted.element->SetType(ExyokiOffice::EnumValue<ExyokiOffice::DocumentFormat::OpenXml::Office2013::Excel::QuestionType>{});
        CHECK_FALSE(hosted.element->GetType().IsDefined());
        hosted.element->SetFormat(ExyokiOffice::EnumValue<ExyokiOffice::DocumentFormat::OpenXml::Office2013::Excel::QuestionFormat>{});
        CHECK_FALSE(hosted.element->GetFormat().IsDefined());
        hosted.element->SetHelpText(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetHelpText().IsDefined());
        hosted.element->SetRequired(ExyokiOffice::BooleanValue{});
        CHECK_FALSE(hosted.element->GetRequired().IsDefined());
        hosted.element->SetDefaultValue(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetDefaultValue().IsDefined());
        hosted.element->SetDecimalPlaces(ExyokiOffice::UInt32Value{});
        CHECK_FALSE(hosted.element->GetDecimalPlaces().IsDefined());
        hosted.element->SetRowSource(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetRowSource().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::UInt32Value sampleBinding = ExyokiOffice::UInt32Value(static_cast<ExyokiOffice::UInt32>(1));
        hosted.element->SetBinding(sampleBinding);
        CHECK(hosted.element->GetBinding() == sampleBinding);
        const ExyokiOffice::StringValue sampleText = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetText(sampleText);
        CHECK(hosted.element->GetText() == sampleText);
        const ExyokiOffice::EnumValue<ExyokiOffice::DocumentFormat::OpenXml::Office2013::Excel::QuestionType> sampleType = ExyokiOffice::EnumValue<ExyokiOffice::DocumentFormat::OpenXml::Office2013::Excel::QuestionType>(ExyokiOffice::DocumentFormat::OpenXml::Office2013::Excel::QuestionType::checkBox);
        hosted.element->SetType(sampleType);
        CHECK(hosted.element->GetType() == sampleType);
        const ExyokiOffice::EnumValue<ExyokiOffice::DocumentFormat::OpenXml::Office2013::Excel::QuestionFormat> sampleFormat = ExyokiOffice::EnumValue<ExyokiOffice::DocumentFormat::OpenXml::Office2013::Excel::QuestionFormat>(ExyokiOffice::DocumentFormat::OpenXml::Office2013::Excel::QuestionFormat::generalDate);
        hosted.element->SetFormat(sampleFormat);
        CHECK(hosted.element->GetFormat() == sampleFormat);
        const ExyokiOffice::StringValue sampleHelpText = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetHelpText(sampleHelpText);
        CHECK(hosted.element->GetHelpText() == sampleHelpText);
        const ExyokiOffice::BooleanValue sampleRequired = ExyokiOffice::BooleanValue(true);
        hosted.element->SetRequired(sampleRequired);
        CHECK(hosted.element->GetRequired() == sampleRequired);
        const ExyokiOffice::StringValue sampleDefaultValue = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetDefaultValue(sampleDefaultValue);
        CHECK(hosted.element->GetDefaultValue() == sampleDefaultValue);
        const ExyokiOffice::UInt32Value sampleDecimalPlaces = ExyokiOffice::UInt32Value(static_cast<ExyokiOffice::UInt32>(1));
        hosted.element->SetDecimalPlaces(sampleDecimalPlaces);
        CHECK(hosted.element->GetDecimalPlaces() == sampleDecimalPlaces);
        const ExyokiOffice::StringValue sampleRowSource = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetRowSource(sampleRowSource);
        CHECK(hosted.element->GetRowSource() == sampleRowSource);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetBinding() == sampleBinding);
        CHECK(reloaded.element->GetText() == sampleText);
        CHECK(reloaded.element->GetType() == sampleType);
        CHECK(reloaded.element->GetFormat() == sampleFormat);
        CHECK(reloaded.element->GetHelpText() == sampleHelpText);
        CHECK(reloaded.element->GetRequired() == sampleRequired);
        CHECK(reloaded.element->GetDefaultValue() == sampleDefaultValue);
        CHECK(reloaded.element->GetDecimalPlaces() == sampleDecimalPlaces);
        CHECK(reloaded.element->GetRowSource() == sampleRowSource);
    }

    TEST_CASE("SurveyQuestions typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::SurveyQuestions>();
        REQUIRE(hosted.element != nullptr);
    }

    TEST_CASE("QuestionPrSurveyElementPr typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::QuestionPrSurveyElementPr>();
        REQUIRE(hosted.element != nullptr);
    }

    TEST_CASE("QuestionsPrSurveyElementPr typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::QuestionsPrSurveyElementPr>();
        REQUIRE(hosted.element != nullptr);
    }

    TEST_CASE("DescriptionPrSurveyElementPr typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::DescriptionPrSurveyElementPr>();
        REQUIRE(hosted.element != nullptr);
    }

    TEST_CASE("TitlePrSurveyElementPr typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::TitlePrSurveyElementPr>();
        REQUIRE(hosted.element != nullptr);
    }

    TEST_CASE("SurveyPrSurveyElementPr typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::SurveyPrSurveyElementPr>();
        REQUIRE(hosted.element != nullptr);
    }

    TEST_CASE("SlicerCacheOlapLevelName typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::SlicerCacheOlapLevelName>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetUniqueName(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetUniqueName().IsDefined());
        hosted.element->SetCount(ExyokiOffice::UInt32Value{});
        CHECK_FALSE(hosted.element->GetCount().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::StringValue sampleUniqueName = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetUniqueName(sampleUniqueName);
        CHECK(hosted.element->GetUniqueName() == sampleUniqueName);
        const ExyokiOffice::UInt32Value sampleCount = ExyokiOffice::UInt32Value(static_cast<ExyokiOffice::UInt32>(1));
        hosted.element->SetCount(sampleCount);
        CHECK(hosted.element->GetCount() == sampleCount);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetUniqueName() == sampleUniqueName);
        CHECK(reloaded.element->GetCount() == sampleCount);
    }

    TEST_CASE("ServerFormat typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::ServerFormat>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetCulture(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetCulture().IsDefined());
        hosted.element->SetFormat(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetFormat().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::StringValue sampleCulture = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetCulture(sampleCulture);
        CHECK(hosted.element->GetCulture() == sampleCulture);
        const ExyokiOffice::StringValue sampleFormat = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetFormat(sampleFormat);
        CHECK(hosted.element->GetFormat() == sampleFormat);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetCulture() == sampleCulture);
        CHECK(reloaded.element->GetFormat() == sampleFormat);
    }

    TEST_CASE("PivotTableServerFormats typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::PivotTableServerFormats>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetCount(ExyokiOffice::UInt32Value{});
        CHECK_FALSE(hosted.element->GetCount().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::UInt32Value sampleCount = ExyokiOffice::UInt32Value(static_cast<ExyokiOffice::UInt32>(1));
        hosted.element->SetCount(sampleCount);
        CHECK(hosted.element->GetCount() == sampleCount);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetCount() == sampleCount);
    }

    TEST_CASE("PivotValueCellExtra typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::PivotValueCellExtra>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetFormatIndex(ExyokiOffice::UInt32Value{});
        CHECK_FALSE(hosted.element->GetFormatIndex().IsDefined());
        hosted.element->SetBackgroundColor(ExyokiOffice::HexBinaryValue{});
        CHECK_FALSE(hosted.element->GetBackgroundColor().IsDefined());
        hosted.element->SetForegroundColor(ExyokiOffice::HexBinaryValue{});
        CHECK_FALSE(hosted.element->GetForegroundColor().IsDefined());
        hosted.element->SetItalic(ExyokiOffice::BooleanValue{});
        CHECK_FALSE(hosted.element->GetItalic().IsDefined());
        hosted.element->SetUnderline(ExyokiOffice::BooleanValue{});
        CHECK_FALSE(hosted.element->GetUnderline().IsDefined());
        hosted.element->SetStrikethrough(ExyokiOffice::BooleanValue{});
        CHECK_FALSE(hosted.element->GetStrikethrough().IsDefined());
        hosted.element->SetBold(ExyokiOffice::BooleanValue{});
        CHECK_FALSE(hosted.element->GetBold().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::UInt32Value sampleFormatIndex = ExyokiOffice::UInt32Value(static_cast<ExyokiOffice::UInt32>(1));
        hosted.element->SetFormatIndex(sampleFormatIndex);
        CHECK(hosted.element->GetFormatIndex() == sampleFormatIndex);
        const ExyokiOffice::HexBinaryValue sampleBackgroundColor = ExyokiOffice::HexBinaryValue(std::vector<ExyokiOffice::UInt8>{0x00, 0xFF});
        hosted.element->SetBackgroundColor(sampleBackgroundColor);
        CHECK(hosted.element->GetBackgroundColor() == sampleBackgroundColor);
        const ExyokiOffice::HexBinaryValue sampleForegroundColor = ExyokiOffice::HexBinaryValue(std::vector<ExyokiOffice::UInt8>{0x00, 0xFF});
        hosted.element->SetForegroundColor(sampleForegroundColor);
        CHECK(hosted.element->GetForegroundColor() == sampleForegroundColor);
        const ExyokiOffice::BooleanValue sampleItalic = ExyokiOffice::BooleanValue(true);
        hosted.element->SetItalic(sampleItalic);
        CHECK(hosted.element->GetItalic() == sampleItalic);
        const ExyokiOffice::BooleanValue sampleUnderline = ExyokiOffice::BooleanValue(true);
        hosted.element->SetUnderline(sampleUnderline);
        CHECK(hosted.element->GetUnderline() == sampleUnderline);
        const ExyokiOffice::BooleanValue sampleStrikethrough = ExyokiOffice::BooleanValue(true);
        hosted.element->SetStrikethrough(sampleStrikethrough);
        CHECK(hosted.element->GetStrikethrough() == sampleStrikethrough);
        const ExyokiOffice::BooleanValue sampleBold = ExyokiOffice::BooleanValue(true);
        hosted.element->SetBold(sampleBold);
        CHECK(hosted.element->GetBold() == sampleBold);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetFormatIndex() == sampleFormatIndex);
        CHECK(reloaded.element->GetBackgroundColor() == sampleBackgroundColor);
        CHECK(reloaded.element->GetForegroundColor() == sampleForegroundColor);
        CHECK(reloaded.element->GetItalic() == sampleItalic);
        CHECK(reloaded.element->GetUnderline() == sampleUnderline);
        CHECK(reloaded.element->GetStrikethrough() == sampleStrikethrough);
        CHECK(reloaded.element->GetBold() == sampleBold);
    }

    TEST_CASE("Xstring typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::Xstring>();
        REQUIRE(hosted.element != nullptr);
    }

    TEST_CASE("PivotValueCell typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::PivotValueCell>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetItem(ExyokiOffice::UInt32Value{});
        CHECK_FALSE(hosted.element->GetItem().IsDefined());
        hosted.element->SetText(ExyokiOffice::EnumValue<ExyokiOffice::DocumentFormat::OpenXml::Office2013::Excel::SXVCellType>{});
        CHECK_FALSE(hosted.element->GetText().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::UInt32Value sampleItem = ExyokiOffice::UInt32Value(static_cast<ExyokiOffice::UInt32>(1));
        hosted.element->SetItem(sampleItem);
        CHECK(hosted.element->GetItem() == sampleItem);
        const ExyokiOffice::EnumValue<ExyokiOffice::DocumentFormat::OpenXml::Office2013::Excel::SXVCellType> sampleText = ExyokiOffice::EnumValue<ExyokiOffice::DocumentFormat::OpenXml::Office2013::Excel::SXVCellType>(ExyokiOffice::DocumentFormat::OpenXml::Office2013::Excel::SXVCellType::Boolean);
        hosted.element->SetText(sampleText);
        CHECK(hosted.element->GetText() == sampleText);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetItem() == sampleItem);
        CHECK(reloaded.element->GetText() == sampleText);
    }

    TEST_CASE("ModelRelationships typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::ModelRelationships>();
        REQUIRE(hosted.element != nullptr);
    }

    TEST_CASE("ModelTables typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::ModelTables>();
        REQUIRE(hosted.element != nullptr);
    }

    TEST_CASE("ModelRelationship typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::ModelRelationship>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetFromTable(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetFromTable().IsDefined());
        hosted.element->SetFromColumn(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetFromColumn().IsDefined());
        hosted.element->SetToTable(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetToTable().IsDefined());
        hosted.element->SetToColumn(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetToColumn().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::StringValue sampleFromTable = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetFromTable(sampleFromTable);
        CHECK(hosted.element->GetFromTable() == sampleFromTable);
        const ExyokiOffice::StringValue sampleFromColumn = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetFromColumn(sampleFromColumn);
        CHECK(hosted.element->GetFromColumn() == sampleFromColumn);
        const ExyokiOffice::StringValue sampleToTable = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetToTable(sampleToTable);
        CHECK(hosted.element->GetToTable() == sampleToTable);
        const ExyokiOffice::StringValue sampleToColumn = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetToColumn(sampleToColumn);
        CHECK(hosted.element->GetToColumn() == sampleToColumn);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetFromTable() == sampleFromTable);
        CHECK(reloaded.element->GetFromColumn() == sampleFromColumn);
        CHECK(reloaded.element->GetToTable() == sampleToTable);
        CHECK(reloaded.element->GetToColumn() == sampleToColumn);
    }

    TEST_CASE("ModelTable typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::ModelTable>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetId(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetId().IsDefined());
        hosted.element->SetName(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetName().IsDefined());
        hosted.element->SetConnection(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetConnection().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::StringValue sampleId = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetId(sampleId);
        CHECK(hosted.element->GetId() == sampleId);
        const ExyokiOffice::StringValue sampleName = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetName(sampleName);
        CHECK(hosted.element->GetName() == sampleName);
        const ExyokiOffice::StringValue sampleConnection = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetConnection(sampleConnection);
        CHECK(hosted.element->GetConnection() == sampleConnection);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetId() == sampleId);
        CHECK(reloaded.element->GetName() == sampleName);
        CHECK(reloaded.element->GetConnection() == sampleConnection);
    }

    TEST_CASE("CachedUniqueName typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::CachedUniqueName>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetIndex(ExyokiOffice::UInt32Value{});
        CHECK_FALSE(hosted.element->GetIndex().IsDefined());
        hosted.element->SetName(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetName().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::UInt32Value sampleIndex = ExyokiOffice::UInt32Value(static_cast<ExyokiOffice::UInt32>(1));
        hosted.element->SetIndex(sampleIndex);
        CHECK(hosted.element->GetIndex() == sampleIndex);
        const ExyokiOffice::StringValue sampleName = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetName(sampleName);
        CHECK(hosted.element->GetName() == sampleName);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetIndex() == sampleIndex);
        CHECK(reloaded.element->GetName() == sampleName);
    }

    TEST_CASE("ExtensionList typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::ExtensionList>();
        REQUIRE(hosted.element != nullptr);
    }

    TEST_CASE("FieldListActiveTabTopLevelEntity typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::FieldListActiveTabTopLevelEntity>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetName(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetName().IsDefined());
        hosted.element->SetType(ExyokiOffice::UInt32Value{});
        CHECK_FALSE(hosted.element->GetType().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::StringValue sampleName = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetName(sampleName);
        CHECK(hosted.element->GetName() == sampleName);
        const ExyokiOffice::UInt32Value sampleType = ExyokiOffice::UInt32Value(static_cast<ExyokiOffice::UInt32>(1));
        hosted.element->SetType(sampleType);
        CHECK(hosted.element->GetType() == sampleType);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetName() == sampleName);
        CHECK(reloaded.element->GetType() == sampleType);
    }

    TEST_CASE("DataFeedProperties typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::DataFeedProperties>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetConnection(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetConnection().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::StringValue sampleConnection = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetConnection(sampleConnection);
        CHECK(hosted.element->GetConnection() == sampleConnection);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetConnection() == sampleConnection);
    }

    TEST_CASE("OleDbPrpoperties typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::OleDbPrpoperties>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetConnection(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetConnection().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::StringValue sampleConnection = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetConnection(sampleConnection);
        CHECK(hosted.element->GetConnection() == sampleConnection);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetConnection() == sampleConnection);
    }

    TEST_CASE("RangeProperties typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::RangeProperties>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetSourceName(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetSourceName().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::StringValue sampleSourceName = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetSourceName(sampleSourceName);
        CHECK(hosted.element->GetSourceName() == sampleSourceName);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetSourceName() == sampleSourceName);
    }

    TEST_CASE("ModelTextProperties typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::ModelTextProperties>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetHeaders(ExyokiOffice::BooleanValue{});
        CHECK_FALSE(hosted.element->GetHeaders().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::BooleanValue sampleHeaders = ExyokiOffice::BooleanValue(true);
        hosted.element->SetHeaders(sampleHeaders);
        CHECK(hosted.element->GetHeaders() == sampleHeaders);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetHeaders() == sampleHeaders);
    }

    TEST_CASE("TextProperties typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::TextProperties>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetPrompt(ExyokiOffice::BooleanValue{});
        CHECK_FALSE(hosted.element->GetPrompt().IsDefined());
        hosted.element->SetFileType(ExyokiOffice::EnumValue<ExyokiOffice::DocumentFormat::OpenXml::Spreadsheet::FileTypeValues>{});
        CHECK_FALSE(hosted.element->GetFileType().IsDefined());
        hosted.element->SetCodePage(ExyokiOffice::UInt32Value{});
        CHECK_FALSE(hosted.element->GetCodePage().IsDefined());
        hosted.element->SetTextCharacterSet(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetTextCharacterSet().IsDefined());
        hosted.element->SetFirstRow(ExyokiOffice::UInt32Value{});
        CHECK_FALSE(hosted.element->GetFirstRow().IsDefined());
        hosted.element->SetSourceFile(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetSourceFile().IsDefined());
        hosted.element->SetDelimited(ExyokiOffice::BooleanValue{});
        CHECK_FALSE(hosted.element->GetDelimited().IsDefined());
        hosted.element->SetDecimal(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetDecimal().IsDefined());
        hosted.element->SetThousands(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetThousands().IsDefined());
        hosted.element->SetTabAsDelimiter(ExyokiOffice::BooleanValue{});
        CHECK_FALSE(hosted.element->GetTabAsDelimiter().IsDefined());
        hosted.element->SetSpace(ExyokiOffice::BooleanValue{});
        CHECK_FALSE(hosted.element->GetSpace().IsDefined());
        hosted.element->SetComma(ExyokiOffice::BooleanValue{});
        CHECK_FALSE(hosted.element->GetComma().IsDefined());
        hosted.element->SetSemicolon(ExyokiOffice::BooleanValue{});
        CHECK_FALSE(hosted.element->GetSemicolon().IsDefined());
        hosted.element->SetConsecutive(ExyokiOffice::BooleanValue{});
        CHECK_FALSE(hosted.element->GetConsecutive().IsDefined());
        hosted.element->SetQualifier(ExyokiOffice::EnumValue<ExyokiOffice::DocumentFormat::OpenXml::Spreadsheet::QualifierValues>{});
        CHECK_FALSE(hosted.element->GetQualifier().IsDefined());
        hosted.element->SetDelimiter(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetDelimiter().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::BooleanValue samplePrompt = ExyokiOffice::BooleanValue(true);
        hosted.element->SetPrompt(samplePrompt);
        CHECK(hosted.element->GetPrompt() == samplePrompt);
        const ExyokiOffice::EnumValue<ExyokiOffice::DocumentFormat::OpenXml::Spreadsheet::FileTypeValues> sampleFileType = ExyokiOffice::EnumValue<ExyokiOffice::DocumentFormat::OpenXml::Spreadsheet::FileTypeValues>(ExyokiOffice::DocumentFormat::OpenXml::Spreadsheet::FileTypeValues::Mac);
        hosted.element->SetFileType(sampleFileType);
        CHECK(hosted.element->GetFileType() == sampleFileType);
        const ExyokiOffice::UInt32Value sampleCodePage = ExyokiOffice::UInt32Value(static_cast<ExyokiOffice::UInt32>(1));
        hosted.element->SetCodePage(sampleCodePage);
        CHECK(hosted.element->GetCodePage() == sampleCodePage);
        const ExyokiOffice::StringValue sampleTextCharacterSet = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetTextCharacterSet(sampleTextCharacterSet);
        CHECK(hosted.element->GetTextCharacterSet() == sampleTextCharacterSet);
        const ExyokiOffice::UInt32Value sampleFirstRow = ExyokiOffice::UInt32Value(static_cast<ExyokiOffice::UInt32>(1));
        hosted.element->SetFirstRow(sampleFirstRow);
        CHECK(hosted.element->GetFirstRow() == sampleFirstRow);
        const ExyokiOffice::StringValue sampleSourceFile = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetSourceFile(sampleSourceFile);
        CHECK(hosted.element->GetSourceFile() == sampleSourceFile);
        const ExyokiOffice::BooleanValue sampleDelimited = ExyokiOffice::BooleanValue(true);
        hosted.element->SetDelimited(sampleDelimited);
        CHECK(hosted.element->GetDelimited() == sampleDelimited);
        const ExyokiOffice::StringValue sampleDecimal = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetDecimal(sampleDecimal);
        CHECK(hosted.element->GetDecimal() == sampleDecimal);
        const ExyokiOffice::StringValue sampleThousands = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetThousands(sampleThousands);
        CHECK(hosted.element->GetThousands() == sampleThousands);
        const ExyokiOffice::BooleanValue sampleTabAsDelimiter = ExyokiOffice::BooleanValue(true);
        hosted.element->SetTabAsDelimiter(sampleTabAsDelimiter);
        CHECK(hosted.element->GetTabAsDelimiter() == sampleTabAsDelimiter);
        const ExyokiOffice::BooleanValue sampleSpace = ExyokiOffice::BooleanValue(true);
        hosted.element->SetSpace(sampleSpace);
        CHECK(hosted.element->GetSpace() == sampleSpace);
        const ExyokiOffice::BooleanValue sampleComma = ExyokiOffice::BooleanValue(true);
        hosted.element->SetComma(sampleComma);
        CHECK(hosted.element->GetComma() == sampleComma);
        const ExyokiOffice::BooleanValue sampleSemicolon = ExyokiOffice::BooleanValue(true);
        hosted.element->SetSemicolon(sampleSemicolon);
        CHECK(hosted.element->GetSemicolon() == sampleSemicolon);
        const ExyokiOffice::BooleanValue sampleConsecutive = ExyokiOffice::BooleanValue(true);
        hosted.element->SetConsecutive(sampleConsecutive);
        CHECK(hosted.element->GetConsecutive() == sampleConsecutive);
        const ExyokiOffice::EnumValue<ExyokiOffice::DocumentFormat::OpenXml::Spreadsheet::QualifierValues> sampleQualifier = ExyokiOffice::EnumValue<ExyokiOffice::DocumentFormat::OpenXml::Spreadsheet::QualifierValues>(ExyokiOffice::DocumentFormat::OpenXml::Spreadsheet::QualifierValues::DoubleQuote);
        hosted.element->SetQualifier(sampleQualifier);
        CHECK(hosted.element->GetQualifier() == sampleQualifier);
        const ExyokiOffice::StringValue sampleDelimiter = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetDelimiter(sampleDelimiter);
        CHECK(hosted.element->GetDelimiter() == sampleDelimiter);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetPrompt() == samplePrompt);
        CHECK(reloaded.element->GetFileType() == sampleFileType);
        CHECK(reloaded.element->GetCodePage() == sampleCodePage);
        CHECK(reloaded.element->GetTextCharacterSet() == sampleTextCharacterSet);
        CHECK(reloaded.element->GetFirstRow() == sampleFirstRow);
        CHECK(reloaded.element->GetSourceFile() == sampleSourceFile);
        CHECK(reloaded.element->GetDelimited() == sampleDelimited);
        CHECK(reloaded.element->GetDecimal() == sampleDecimal);
        CHECK(reloaded.element->GetThousands() == sampleThousands);
        CHECK(reloaded.element->GetTabAsDelimiter() == sampleTabAsDelimiter);
        CHECK(reloaded.element->GetSpace() == sampleSpace);
        CHECK(reloaded.element->GetComma() == sampleComma);
        CHECK(reloaded.element->GetSemicolon() == sampleSemicolon);
        CHECK(reloaded.element->GetConsecutive() == sampleConsecutive);
        CHECK(reloaded.element->GetQualifier() == sampleQualifier);
        CHECK(reloaded.element->GetDelimiter() == sampleDelimiter);
    }

    TEST_CASE("DbCommand typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::DbCommand>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetText(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetText().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::StringValue sampleText = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetText(sampleText);
        CHECK(hosted.element->GetText() == sampleText);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetText() == sampleText);
    }

    TEST_CASE("DbTables typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::DbTables>();
        REQUIRE(hosted.element != nullptr);
    }

    TEST_CASE("DbTable typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::DbTable>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetName(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetName().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::StringValue sampleName = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetName(sampleName);
        CHECK(hosted.element->GetName() == sampleName);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetName() == sampleName);
    }

    TEST_CASE("TimelineStyleElements typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::TimelineStyleElements>();
        REQUIRE(hosted.element != nullptr);
    }

    TEST_CASE("TimelineStyleElement typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::TimelineStyleElement>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetType(ExyokiOffice::EnumValue<ExyokiOffice::DocumentFormat::OpenXml::Office2013::Excel::TimelineStyleType>{});
        CHECK_FALSE(hosted.element->GetType().IsDefined());
        hosted.element->SetFormatId(ExyokiOffice::UInt32Value{});
        CHECK_FALSE(hosted.element->GetFormatId().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::EnumValue<ExyokiOffice::DocumentFormat::OpenXml::Office2013::Excel::TimelineStyleType> sampleType = ExyokiOffice::EnumValue<ExyokiOffice::DocumentFormat::OpenXml::Office2013::Excel::TimelineStyleType>(ExyokiOffice::DocumentFormat::OpenXml::Office2013::Excel::TimelineStyleType::SelectionLabel);
        hosted.element->SetType(sampleType);
        CHECK(hosted.element->GetType() == sampleType);
        const ExyokiOffice::UInt32Value sampleFormatId = ExyokiOffice::UInt32Value(static_cast<ExyokiOffice::UInt32>(1));
        hosted.element->SetFormatId(sampleFormatId);
        CHECK(hosted.element->GetFormatId() == sampleFormatId);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetType() == sampleType);
        CHECK(reloaded.element->GetFormatId() == sampleFormatId);
    }

    TEST_CASE("TimelineStyle typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::TimelineStyle>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetName(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetName().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::StringValue sampleName = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetName(sampleName);
        CHECK(hosted.element->GetName() == sampleName);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetName() == sampleName);
    }

    TEST_CASE("TimelineReference typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::TimelineReference>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetId(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetId().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::StringValue sampleId = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetId(sampleId);
        CHECK(hosted.element->GetId() == sampleId);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetId() == sampleId);
    }

    TEST_CASE("TimelineCacheReference typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::TimelineCacheReference>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetId(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetId().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::StringValue sampleId = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetId(sampleId);
        CHECK(hosted.element->GetId() == sampleId);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetId() == sampleId);
    }

    TEST_CASE("WebExtension typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::WebExtension>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetApplicationReference(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetApplicationReference().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::StringValue sampleApplicationReference = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetApplicationReference(sampleApplicationReference);
        CHECK(hosted.element->GetApplicationReference() == sampleApplicationReference);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetApplicationReference() == sampleApplicationReference);
    }

    TEST_CASE("PivotTableReference typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::PivotTableReference>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetId(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetId().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::StringValue sampleId = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetId(sampleId);
        CHECK(hosted.element->GetId() == sampleId);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetId() == sampleId);
    }

    TEST_CASE("TimelineCacheDefinition typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::TimelineCacheDefinition>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetName(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetName().IsDefined());
        hosted.element->SetSourceName(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetSourceName().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::StringValue sampleName = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetName(sampleName);
        CHECK(hosted.element->GetName() == sampleName);
        const ExyokiOffice::StringValue sampleSourceName = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetSourceName(sampleSourceName);
        CHECK(hosted.element->GetSourceName() == sampleSourceName);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetName() == sampleName);
        CHECK(reloaded.element->GetSourceName() == sampleSourceName);
    }

    TEST_CASE("Timelines typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::Timelines>();
        REQUIRE(hosted.element != nullptr);
    }

    TEST_CASE("Survey typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::Survey>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetId(ExyokiOffice::UInt32Value{});
        CHECK_FALSE(hosted.element->GetId().IsDefined());
        hosted.element->SetGuid(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetGuid().IsDefined());
        hosted.element->SetTitle(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetTitle().IsDefined());
        hosted.element->SetDescription(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetDescription().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::UInt32Value sampleId = ExyokiOffice::UInt32Value(static_cast<ExyokiOffice::UInt32>(1));
        hosted.element->SetId(sampleId);
        CHECK(hosted.element->GetId() == sampleId);
        const ExyokiOffice::StringValue sampleGuid = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetGuid(sampleGuid);
        CHECK(hosted.element->GetGuid() == sampleGuid);
        const ExyokiOffice::StringValue sampleTitle = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetTitle(sampleTitle);
        CHECK(hosted.element->GetTitle() == sampleTitle);
        const ExyokiOffice::StringValue sampleDescription = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetDescription(sampleDescription);
        CHECK(hosted.element->GetDescription() == sampleDescription);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetId() == sampleId);
        CHECK(reloaded.element->GetGuid() == sampleGuid);
        CHECK(reloaded.element->GetTitle() == sampleTitle);
        CHECK(reloaded.element->GetDescription() == sampleDescription);
    }

    TEST_CASE("SlicerCachePivotTables typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::SlicerCachePivotTables>();
        REQUIRE(hosted.element != nullptr);
    }

    TEST_CASE("SlicerCacheHideItemsWithNoData typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::SlicerCacheHideItemsWithNoData>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetCount(ExyokiOffice::UInt32Value{});
        CHECK_FALSE(hosted.element->GetCount().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::UInt32Value sampleCount = ExyokiOffice::UInt32Value(static_cast<ExyokiOffice::UInt32>(1));
        hosted.element->SetCount(sampleCount);
        CHECK(hosted.element->GetCount() == sampleCount);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetCount() == sampleCount);
    }

    TEST_CASE("TableSlicerCache typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::TableSlicerCache>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetTableId(ExyokiOffice::UInt32Value{});
        CHECK_FALSE(hosted.element->GetTableId().IsDefined());
        hosted.element->SetColumn(ExyokiOffice::UInt32Value{});
        CHECK_FALSE(hosted.element->GetColumn().IsDefined());
        hosted.element->SetSortOrder(ExyokiOffice::EnumValue<ExyokiOffice::DocumentFormat::OpenXml::Office2010::Excel::TabularSlicerCacheSortOrderValues>{});
        CHECK_FALSE(hosted.element->GetSortOrder().IsDefined());
        hosted.element->SetCustomListSort(ExyokiOffice::BooleanValue{});
        CHECK_FALSE(hosted.element->GetCustomListSort().IsDefined());
        hosted.element->SetCrossFilter(ExyokiOffice::EnumValue<ExyokiOffice::DocumentFormat::OpenXml::Office2010::Excel::SlicerCacheCrossFilterValues>{});
        CHECK_FALSE(hosted.element->GetCrossFilter().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::UInt32Value sampleTableId = ExyokiOffice::UInt32Value(static_cast<ExyokiOffice::UInt32>(1));
        hosted.element->SetTableId(sampleTableId);
        CHECK(hosted.element->GetTableId() == sampleTableId);
        const ExyokiOffice::UInt32Value sampleColumn = ExyokiOffice::UInt32Value(static_cast<ExyokiOffice::UInt32>(1));
        hosted.element->SetColumn(sampleColumn);
        CHECK(hosted.element->GetColumn() == sampleColumn);
        const ExyokiOffice::EnumValue<ExyokiOffice::DocumentFormat::OpenXml::Office2010::Excel::TabularSlicerCacheSortOrderValues> sampleSortOrder = ExyokiOffice::EnumValue<ExyokiOffice::DocumentFormat::OpenXml::Office2010::Excel::TabularSlicerCacheSortOrderValues>(ExyokiOffice::DocumentFormat::OpenXml::Office2010::Excel::TabularSlicerCacheSortOrderValues::Ascending);
        hosted.element->SetSortOrder(sampleSortOrder);
        CHECK(hosted.element->GetSortOrder() == sampleSortOrder);
        const ExyokiOffice::BooleanValue sampleCustomListSort = ExyokiOffice::BooleanValue(true);
        hosted.element->SetCustomListSort(sampleCustomListSort);
        CHECK(hosted.element->GetCustomListSort() == sampleCustomListSort);
        const ExyokiOffice::EnumValue<ExyokiOffice::DocumentFormat::OpenXml::Office2010::Excel::SlicerCacheCrossFilterValues> sampleCrossFilter = ExyokiOffice::EnumValue<ExyokiOffice::DocumentFormat::OpenXml::Office2010::Excel::SlicerCacheCrossFilterValues>(ExyokiOffice::DocumentFormat::OpenXml::Office2010::Excel::SlicerCacheCrossFilterValues::None);
        hosted.element->SetCrossFilter(sampleCrossFilter);
        CHECK(hosted.element->GetCrossFilter() == sampleCrossFilter);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetTableId() == sampleTableId);
        CHECK(reloaded.element->GetColumn() == sampleColumn);
        CHECK(reloaded.element->GetSortOrder() == sampleSortOrder);
        CHECK(reloaded.element->GetCustomListSort() == sampleCustomListSort);
        CHECK(reloaded.element->GetCrossFilter() == sampleCrossFilter);
    }

    TEST_CASE("SlicerCaches typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::SlicerCaches>();
        REQUIRE(hosted.element != nullptr);
    }

    TEST_CASE("MovingPeriodState typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::MovingPeriodState>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetReferenceDateBegin(ExyokiOffice::DateTimeValue{});
        CHECK_FALSE(hosted.element->GetReferenceDateBegin().IsDefined());
        hosted.element->SetReferencePeriod(ExyokiOffice::EnumValue<ExyokiOffice::DocumentFormat::OpenXml::Office2013::Excel::MovingPeriodStep>{});
        CHECK_FALSE(hosted.element->GetReferencePeriod().IsDefined());
        hosted.element->SetReferenceMultiple(ExyokiOffice::UInt32Value{});
        CHECK_FALSE(hosted.element->GetReferenceMultiple().IsDefined());
        hosted.element->SetMovingPeriod(ExyokiOffice::EnumValue<ExyokiOffice::DocumentFormat::OpenXml::Office2013::Excel::MovingPeriodStep>{});
        CHECK_FALSE(hosted.element->GetMovingPeriod().IsDefined());
        hosted.element->SetMovingMultiple(ExyokiOffice::UInt32Value{});
        CHECK_FALSE(hosted.element->GetMovingMultiple().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::DateTimeValue sampleReferenceDateBegin = ExyokiOffice::DateTimeValue(std::string_view("2020-01-01T00:00:00Z"));
        hosted.element->SetReferenceDateBegin(sampleReferenceDateBegin);
        CHECK(hosted.element->GetReferenceDateBegin() == sampleReferenceDateBegin);
        const ExyokiOffice::EnumValue<ExyokiOffice::DocumentFormat::OpenXml::Office2013::Excel::MovingPeriodStep> sampleReferencePeriod = ExyokiOffice::EnumValue<ExyokiOffice::DocumentFormat::OpenXml::Office2013::Excel::MovingPeriodStep>(ExyokiOffice::DocumentFormat::OpenXml::Office2013::Excel::MovingPeriodStep::year);
        hosted.element->SetReferencePeriod(sampleReferencePeriod);
        CHECK(hosted.element->GetReferencePeriod() == sampleReferencePeriod);
        const ExyokiOffice::UInt32Value sampleReferenceMultiple = ExyokiOffice::UInt32Value(static_cast<ExyokiOffice::UInt32>(1));
        hosted.element->SetReferenceMultiple(sampleReferenceMultiple);
        CHECK(hosted.element->GetReferenceMultiple() == sampleReferenceMultiple);
        const ExyokiOffice::EnumValue<ExyokiOffice::DocumentFormat::OpenXml::Office2013::Excel::MovingPeriodStep> sampleMovingPeriod = ExyokiOffice::EnumValue<ExyokiOffice::DocumentFormat::OpenXml::Office2013::Excel::MovingPeriodStep>(ExyokiOffice::DocumentFormat::OpenXml::Office2013::Excel::MovingPeriodStep::year);
        hosted.element->SetMovingPeriod(sampleMovingPeriod);
        CHECK(hosted.element->GetMovingPeriod() == sampleMovingPeriod);
        const ExyokiOffice::UInt32Value sampleMovingMultiple = ExyokiOffice::UInt32Value(static_cast<ExyokiOffice::UInt32>(1));
        hosted.element->SetMovingMultiple(sampleMovingMultiple);
        CHECK(hosted.element->GetMovingMultiple() == sampleMovingMultiple);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetReferenceDateBegin() == sampleReferenceDateBegin);
        CHECK(reloaded.element->GetReferencePeriod() == sampleReferencePeriod);
        CHECK(reloaded.element->GetReferenceMultiple() == sampleReferenceMultiple);
        CHECK(reloaded.element->GetMovingPeriod() == sampleMovingPeriod);
        CHECK(reloaded.element->GetMovingMultiple() == sampleMovingMultiple);
    }

    TEST_CASE("DataField typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::DataField>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetIsCountDistinct(ExyokiOffice::BooleanValue{});
        CHECK_FALSE(hosted.element->GetIsCountDistinct().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::BooleanValue sampleIsCountDistinct = ExyokiOffice::BooleanValue(true);
        hosted.element->SetIsCountDistinct(sampleIsCountDistinct);
        CHECK(hosted.element->GetIsCountDistinct() == sampleIsCountDistinct);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetIsCountDistinct() == sampleIsCountDistinct);
    }

    TEST_CASE("PivotCacheDecoupled typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::PivotCacheDecoupled>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetDecoupled(ExyokiOffice::BooleanValue{});
        CHECK_FALSE(hosted.element->GetDecoupled().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::BooleanValue sampleDecoupled = ExyokiOffice::BooleanValue(true);
        hosted.element->SetDecoupled(sampleDecoupled);
        CHECK(hosted.element->GetDecoupled() == sampleDecoupled);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetDecoupled() == sampleDecoupled);
    }

    TEST_CASE("PivotTableData typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::PivotTableData>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetRowCount(ExyokiOffice::UInt32Value{});
        CHECK_FALSE(hosted.element->GetRowCount().IsDefined());
        hosted.element->SetColumnCount(ExyokiOffice::UInt32Value{});
        CHECK_FALSE(hosted.element->GetColumnCount().IsDefined());
        hosted.element->SetCacheId(ExyokiOffice::UInt32Value{});
        CHECK_FALSE(hosted.element->GetCacheId().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::UInt32Value sampleRowCount = ExyokiOffice::UInt32Value(static_cast<ExyokiOffice::UInt32>(1));
        hosted.element->SetRowCount(sampleRowCount);
        CHECK(hosted.element->GetRowCount() == sampleRowCount);
        const ExyokiOffice::UInt32Value sampleColumnCount = ExyokiOffice::UInt32Value(static_cast<ExyokiOffice::UInt32>(1));
        hosted.element->SetColumnCount(sampleColumnCount);
        CHECK(hosted.element->GetColumnCount() == sampleColumnCount);
        const ExyokiOffice::UInt32Value sampleCacheId = ExyokiOffice::UInt32Value(static_cast<ExyokiOffice::UInt32>(1));
        hosted.element->SetCacheId(sampleCacheId);
        CHECK(hosted.element->GetCacheId() == sampleCacheId);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetRowCount() == sampleRowCount);
        CHECK(reloaded.element->GetColumnCount() == sampleColumnCount);
        CHECK(reloaded.element->GetCacheId() == sampleCacheId);
    }

    TEST_CASE("DataModel typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::DataModel>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetMinVersionLoad(ExyokiOffice::ByteValue{});
        CHECK_FALSE(hosted.element->GetMinVersionLoad().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::ByteValue sampleMinVersionLoad = ExyokiOffice::ByteValue(static_cast<ExyokiOffice::UInt8>(1));
        hosted.element->SetMinVersionLoad(sampleMinVersionLoad);
        CHECK(hosted.element->GetMinVersionLoad() == sampleMinVersionLoad);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetMinVersionLoad() == sampleMinVersionLoad);
    }

    TEST_CASE("PivotCacheIdVersion typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::PivotCacheIdVersion>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetCacheIdSupportedVersion(ExyokiOffice::ByteValue{});
        CHECK_FALSE(hosted.element->GetCacheIdSupportedVersion().IsDefined());
        hosted.element->SetCacheIdCreatedVersion(ExyokiOffice::ByteValue{});
        CHECK_FALSE(hosted.element->GetCacheIdCreatedVersion().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::ByteValue sampleCacheIdSupportedVersion = ExyokiOffice::ByteValue(static_cast<ExyokiOffice::UInt8>(1));
        hosted.element->SetCacheIdSupportedVersion(sampleCacheIdSupportedVersion);
        CHECK(hosted.element->GetCacheIdSupportedVersion() == sampleCacheIdSupportedVersion);
        const ExyokiOffice::ByteValue sampleCacheIdCreatedVersion = ExyokiOffice::ByteValue(static_cast<ExyokiOffice::UInt8>(1));
        hosted.element->SetCacheIdCreatedVersion(sampleCacheIdCreatedVersion);
        CHECK(hosted.element->GetCacheIdCreatedVersion() == sampleCacheIdCreatedVersion);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetCacheIdSupportedVersion() == sampleCacheIdSupportedVersion);
        CHECK(reloaded.element->GetCacheIdCreatedVersion() == sampleCacheIdCreatedVersion);
    }

    TEST_CASE("TimelinePivotCacheDefinition typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::TimelinePivotCacheDefinition>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetTimelineData(ExyokiOffice::BooleanValue{});
        CHECK_FALSE(hosted.element->GetTimelineData().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::BooleanValue sampleTimelineData = ExyokiOffice::BooleanValue(true);
        hosted.element->SetTimelineData(sampleTimelineData);
        CHECK(hosted.element->GetTimelineData() == sampleTimelineData);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetTimelineData() == sampleTimelineData);
    }

    TEST_CASE("CacheHierarchy typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::CacheHierarchy>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetAggregatedColumn(ExyokiOffice::Int32Value{});
        CHECK_FALSE(hosted.element->GetAggregatedColumn().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::Int32Value sampleAggregatedColumn = ExyokiOffice::Int32Value(static_cast<ExyokiOffice::Int32>(1));
        hosted.element->SetAggregatedColumn(sampleAggregatedColumn);
        CHECK(hosted.element->GetAggregatedColumn() == sampleAggregatedColumn);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetAggregatedColumn() == sampleAggregatedColumn);
    }

    TEST_CASE("CachedUniqueNames typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::CachedUniqueNames>();
        REQUIRE(hosted.element != nullptr);
    }

    TEST_CASE("PivotFilter typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::PivotFilter>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetUseWholeDay(ExyokiOffice::BooleanValue{});
        CHECK_FALSE(hosted.element->GetUseWholeDay().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::BooleanValue sampleUseWholeDay = ExyokiOffice::BooleanValue(true);
        hosted.element->SetUseWholeDay(sampleUseWholeDay);
        CHECK(hosted.element->GetUseWholeDay() == sampleUseWholeDay);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetUseWholeDay() == sampleUseWholeDay);
    }

    TEST_CASE("PivotTableUISettings typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::PivotTableUISettings>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetSourceDataName(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetSourceDataName().IsDefined());
        hosted.element->SetRelNeededHidden(ExyokiOffice::BooleanValue{});
        CHECK_FALSE(hosted.element->GetRelNeededHidden().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::StringValue sampleSourceDataName = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetSourceDataName(sampleSourceDataName);
        CHECK(hosted.element->GetSourceDataName() == sampleSourceDataName);
        const ExyokiOffice::BooleanValue sampleRelNeededHidden = ExyokiOffice::BooleanValue(true);
        hosted.element->SetRelNeededHidden(sampleRelNeededHidden);
        CHECK(hosted.element->GetRelNeededHidden() == sampleRelNeededHidden);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetSourceDataName() == sampleSourceDataName);
        CHECK(reloaded.element->GetRelNeededHidden() == sampleRelNeededHidden);
    }

    TEST_CASE("CalculatedMember typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::CalculatedMember>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetMeasureGroup(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetMeasureGroup().IsDefined());
        hosted.element->SetNumberFormat(ExyokiOffice::EnumValue<ExyokiOffice::DocumentFormat::OpenXml::Office2013::Excel::CalculatedMemberNumberFormat>{});
        CHECK_FALSE(hosted.element->GetNumberFormat().IsDefined());
        hosted.element->SetMeasure(ExyokiOffice::BooleanValue{});
        CHECK_FALSE(hosted.element->GetMeasure().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::StringValue sampleMeasureGroup = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetMeasureGroup(sampleMeasureGroup);
        CHECK(hosted.element->GetMeasureGroup() == sampleMeasureGroup);
        const ExyokiOffice::EnumValue<ExyokiOffice::DocumentFormat::OpenXml::Office2013::Excel::CalculatedMemberNumberFormat> sampleNumberFormat = ExyokiOffice::EnumValue<ExyokiOffice::DocumentFormat::OpenXml::Office2013::Excel::CalculatedMemberNumberFormat>(ExyokiOffice::DocumentFormat::OpenXml::Office2013::Excel::CalculatedMemberNumberFormat::Default);
        hosted.element->SetNumberFormat(sampleNumberFormat);
        CHECK(hosted.element->GetNumberFormat() == sampleNumberFormat);
        const ExyokiOffice::BooleanValue sampleMeasure = ExyokiOffice::BooleanValue(true);
        hosted.element->SetMeasure(sampleMeasure);
        CHECK(hosted.element->GetMeasure() == sampleMeasure);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetMeasureGroup() == sampleMeasureGroup);
        CHECK(reloaded.element->GetNumberFormat() == sampleNumberFormat);
        CHECK(reloaded.element->GetMeasure() == sampleMeasure);
    }

    TEST_CASE("Connection typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::Connection>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetId(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetId().IsDefined());
        hosted.element->SetModel(ExyokiOffice::BooleanValue{});
        CHECK_FALSE(hosted.element->GetModel().IsDefined());
        hosted.element->SetExcludeFromRefreshAll(ExyokiOffice::BooleanValue{});
        CHECK_FALSE(hosted.element->GetExcludeFromRefreshAll().IsDefined());
        hosted.element->SetAutoDelete(ExyokiOffice::BooleanValue{});
        CHECK_FALSE(hosted.element->GetAutoDelete().IsDefined());
        hosted.element->SetUsedByAddin(ExyokiOffice::BooleanValue{});
        CHECK_FALSE(hosted.element->GetUsedByAddin().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::StringValue sampleId = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetId(sampleId);
        CHECK(hosted.element->GetId() == sampleId);
        const ExyokiOffice::BooleanValue sampleModel = ExyokiOffice::BooleanValue(true);
        hosted.element->SetModel(sampleModel);
        CHECK(hosted.element->GetModel() == sampleModel);
        const ExyokiOffice::BooleanValue sampleExcludeFromRefreshAll = ExyokiOffice::BooleanValue(true);
        hosted.element->SetExcludeFromRefreshAll(sampleExcludeFromRefreshAll);
        CHECK(hosted.element->GetExcludeFromRefreshAll() == sampleExcludeFromRefreshAll);
        const ExyokiOffice::BooleanValue sampleAutoDelete = ExyokiOffice::BooleanValue(true);
        hosted.element->SetAutoDelete(sampleAutoDelete);
        CHECK(hosted.element->GetAutoDelete() == sampleAutoDelete);
        const ExyokiOffice::BooleanValue sampleUsedByAddin = ExyokiOffice::BooleanValue(true);
        hosted.element->SetUsedByAddin(sampleUsedByAddin);
        CHECK(hosted.element->GetUsedByAddin() == sampleUsedByAddin);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetId() == sampleId);
        CHECK(reloaded.element->GetModel() == sampleModel);
        CHECK(reloaded.element->GetExcludeFromRefreshAll() == sampleExcludeFromRefreshAll);
        CHECK(reloaded.element->GetAutoDelete() == sampleAutoDelete);
        CHECK(reloaded.element->GetUsedByAddin() == sampleUsedByAddin);
    }

    TEST_CASE("DifferentialFormats typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::DifferentialFormats>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetCount(ExyokiOffice::UInt32Value{});
        CHECK_FALSE(hosted.element->GetCount().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::UInt32Value sampleCount = ExyokiOffice::UInt32Value(static_cast<ExyokiOffice::UInt32>(1));
        hosted.element->SetCount(sampleCount);
        CHECK(hosted.element->GetCount() == sampleCount);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetCount() == sampleCount);
    }

    TEST_CASE("TimelineStyles typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::TimelineStyles>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetDefaultTimelineStyle(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetDefaultTimelineStyle().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::StringValue sampleDefaultTimelineStyle = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetDefaultTimelineStyle(sampleDefaultTimelineStyle);
        CHECK(hosted.element->GetDefaultTimelineStyle() == sampleDefaultTimelineStyle);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetDefaultTimelineStyle() == sampleDefaultTimelineStyle);
    }

    TEST_CASE("WorkbookProperties typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::WorkbookProperties>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetChartTrackingReferenceBase(ExyokiOffice::BooleanValue{});
        CHECK_FALSE(hosted.element->GetChartTrackingReferenceBase().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::BooleanValue sampleChartTrackingReferenceBase = ExyokiOffice::BooleanValue(true);
        hosted.element->SetChartTrackingReferenceBase(sampleChartTrackingReferenceBase);
        CHECK(hosted.element->GetChartTrackingReferenceBase() == sampleChartTrackingReferenceBase);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetChartTrackingReferenceBase() == sampleChartTrackingReferenceBase);
    }

    TEST_CASE("TimelineReferences typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::TimelineReferences>();
        REQUIRE(hosted.element != nullptr);
    }

    TEST_CASE("TimelineCacheReferences typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::TimelineCacheReferences>();
        REQUIRE(hosted.element != nullptr);
    }

    TEST_CASE("WebExtensions typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::WebExtensions>();
        REQUIRE(hosted.element != nullptr);
    }

    TEST_CASE("QueryTable typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::QueryTable>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetClipped(ExyokiOffice::BooleanValue{});
        CHECK_FALSE(hosted.element->GetClipped().IsDefined());
        hosted.element->SetSourceDataName(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetSourceDataName().IsDefined());
        hosted.element->SetDrillThrough(ExyokiOffice::BooleanValue{});
        CHECK_FALSE(hosted.element->GetDrillThrough().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::BooleanValue sampleClipped = ExyokiOffice::BooleanValue(true);
        hosted.element->SetClipped(sampleClipped);
        CHECK(hosted.element->GetClipped() == sampleClipped);
        const ExyokiOffice::StringValue sampleSourceDataName = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetSourceDataName(sampleSourceDataName);
        CHECK(hosted.element->GetSourceDataName() == sampleSourceDataName);
        const ExyokiOffice::BooleanValue sampleDrillThrough = ExyokiOffice::BooleanValue(true);
        hosted.element->SetDrillThrough(sampleDrillThrough);
        CHECK(hosted.element->GetDrillThrough() == sampleDrillThrough);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetClipped() == sampleClipped);
        CHECK(reloaded.element->GetSourceDataName() == sampleSourceDataName);
        CHECK(reloaded.element->GetDrillThrough() == sampleDrillThrough);
    }

    TEST_CASE("PivotTableReferences typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::PivotTableReferences>();
        REQUIRE(hosted.element != nullptr);
    }

    TEST_CASE("TimelineCachePivotCaches typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::TimelineCachePivotCaches>();
        REQUIRE(hosted.element != nullptr);
    }

    TEST_CASE("PivotCaches typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::PivotCaches>();
        REQUIRE(hosted.element != nullptr);
    }

}
