// Copyright (c) 2026 Jakub Melka and Contributors
// SPDX-License-Identifier: MIT
// See LICENSE file in the project root for full license text.
//
// Derived from the Open-XML-SDK metadata under data/, which is
// Copyright (c) .NET Foundation and Contributors and MIT-licensed.
// See data/LICENSE and THIRD-PARTY-LICENSES.md in the project root.
// -----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by ExyokiOffice OpenXML generator.
//     Manual changes to this file may cause unexpected behaviour.
// </auto-generated>
// -----------------------------------------------------------------------------

#include "doctest.h"

#include "DomTestSupport.hpp"

#include "ExyokiOffice/DOM/DocumentFormat/OpenXml/Office/SpreadSheetML/Y2023/Pivot2023Calculation.hpp"
#include "ExyokiOffice/StandardTypes.hpp"

#include <cstdint>
#include <string_view>
#include <vector>

namespace EoNs = ExyokiOffice::DocumentFormat::OpenXml::Office::SpreadSheetML::Y2023::Pivot2023Calculation;

TEST_SUITE("DocumentFormat.OpenXml.Office.SpreadSheetML.Y2023.Pivot2023Calculation.DomGeneratedTests")
{
    TEST_CASE("PivotSubtotalType typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::PivotSubtotalType>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetSubtotalType(ExyokiOffice::EnumValue<ExyokiOffice::DocumentFormat::OpenXml::Office::SpreadSheetML::Y2023::Pivot2023Calculation::AggregationType>{});
        CHECK_FALSE(hosted.element->GetSubtotalType().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::EnumValue<ExyokiOffice::DocumentFormat::OpenXml::Office::SpreadSheetML::Y2023::Pivot2023Calculation::AggregationType> sampleSubtotalType = ExyokiOffice::EnumValue<ExyokiOffice::DocumentFormat::OpenXml::Office::SpreadSheetML::Y2023::Pivot2023Calculation::AggregationType>(ExyokiOffice::DocumentFormat::OpenXml::Office::SpreadSheetML::Y2023::Pivot2023Calculation::AggregationType::distinctCount);
        hosted.element->SetSubtotalType(sampleSubtotalType);
        CHECK(hosted.element->GetSubtotalType() == sampleSubtotalType);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetSubtotalType() == sampleSubtotalType);
    }

    TEST_CASE("SubtotalLineItemPivotItemSubtotal typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::SubtotalLineItemPivotItemSubtotal>();
        REQUIRE(hosted.element != nullptr);
    }

    TEST_CASE("SubtotalPivotItemSubtotal typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::SubtotalPivotItemSubtotal>();
        REQUIRE(hosted.element != nullptr);
    }

    TEST_CASE("PivotTableSubtotalLineItems typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::PivotTableSubtotalLineItems>();
        REQUIRE(hosted.element != nullptr);
    }

    TEST_CASE("PivotAreaReferenceSubtotals typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::PivotAreaReferenceSubtotals>();
        REQUIRE(hosted.element != nullptr);
    }

    TEST_CASE("PivotFieldSubtotals typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::PivotFieldSubtotals>();
        REQUIRE(hosted.element != nullptr);
    }

    TEST_CASE("FeatureSupport typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::FeatureSupport>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetFeatureName(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetFeatureName().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::StringValue sampleFeatureName = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetFeatureName(sampleFeatureName);
        CHECK(hosted.element->GetFeatureName() == sampleFeatureName);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetFeatureName() == sampleFeatureName);
    }

    TEST_CASE("AggregationInfo typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::AggregationInfo>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetAggregationType(ExyokiOffice::EnumValue<ExyokiOffice::DocumentFormat::OpenXml::Office::SpreadSheetML::Y2023::Pivot2023Calculation::AggregationType>{});
        CHECK_FALSE(hosted.element->GetAggregationType().IsDefined());
        hosted.element->SetSourceField(ExyokiOffice::UInt32Value{});
        CHECK_FALSE(hosted.element->GetSourceField().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::EnumValue<ExyokiOffice::DocumentFormat::OpenXml::Office::SpreadSheetML::Y2023::Pivot2023Calculation::AggregationType> sampleAggregationType = ExyokiOffice::EnumValue<ExyokiOffice::DocumentFormat::OpenXml::Office::SpreadSheetML::Y2023::Pivot2023Calculation::AggregationType>(ExyokiOffice::DocumentFormat::OpenXml::Office::SpreadSheetML::Y2023::Pivot2023Calculation::AggregationType::distinctCount);
        hosted.element->SetAggregationType(sampleAggregationType);
        CHECK(hosted.element->GetAggregationType() == sampleAggregationType);
        const ExyokiOffice::UInt32Value sampleSourceField = ExyokiOffice::UInt32Value(static_cast<ExyokiOffice::UInt32>(1));
        hosted.element->SetSourceField(sampleSourceField);
        CHECK(hosted.element->GetSourceField() == sampleSourceField);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetAggregationType() == sampleAggregationType);
        CHECK(reloaded.element->GetSourceField() == sampleSourceField);
    }

}
