// Copyright (c) 2026 Jakub Melka and Collaborators
// SPDX-License-Identifier: MIT
// See LICENSE file in the project root for full license text.
// -----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by ExyokiOffice OpenXML generator.
//     Manual changes to this file may cause unexpected behaviour.
// </auto-generated>
// -----------------------------------------------------------------------------

#include "doctest.h"

#include "DomTestSupport.hpp"

#include "ExyokiOffice/DOM/DocumentFormat/OpenXml/Office/SpreadSheetML/Y2025/PivotDataSource.hpp"
#include "ExyokiOffice/StandardTypes.hpp"

#include <cstdint>
#include <string_view>
#include <vector>

namespace EoNs = ExyokiOffice::DocumentFormat::OpenXml::Office::SpreadSheetML::Y2025::PivotDataSource;

TEST_SUITE("DocumentFormat.OpenXml.Office.SpreadSheetML.Y2025.PivotDataSource.DomGeneratedTests")
{
    TEST_CASE("PivotCacheDataSource typed accessors round-trip [unit] [metadata] [dom-generated]")
    {
        auto hosted = DomTest::HostElement<EoNs::PivotCacheDataSource>();
        REQUIRE(hosted.element != nullptr);

        // Undefined contract: every typed accessor links and honours IsDefined().
        hosted.element->SetRef(ExyokiOffice::StringValue{});
        CHECK_FALSE(hosted.element->GetRef().IsDefined());

        // Typed value round-trip through real XML serialization.
        const ExyokiOffice::StringValue sampleRef = ExyokiOffice::StringValue(std::string_view("eo-sample"));
        hosted.element->SetRef(sampleRef);
        CHECK(hosted.element->GetRef() == sampleRef);
        const auto reloaded = hosted.RoundTrip();
        REQUIRE(reloaded.element != nullptr);
        CHECK(reloaded.element->GetRef() == sampleRef);
    }

}
